import { describe, expect, it } from "vitest";
import { HttpTester } from "./test-host.js";

/**
 * Tests for the ExtensibleEnumFile component.
 *
 * These tests verify that the emitter correctly generates C# readonly partial
 * structs for extensible (non-fixed) TypeSpec enums. Extensible enums are
 * represented as structs implementing IEquatable<T> to allow custom values
 * beyond the predefined set.
 *
 * Why these tests matter:
 * - Extensible enums are fundamentally different from fixed enums (struct vs enum).
 * - Validates the full pipeline: TypeSpec union → TCGC SdkEnumType → ExtensibleEnumFile → C# output.
 * - Ensures string vs numeric backing type differences are handled correctly.
 * - Verifies operators, equality, and conversion patterns match the legacy emitter.
 *
 * TypeSpec unions with literal members are modeled as extensible enums by TCGC.
 * For example, `union DaysOfWeek { string, Monday: "Monday" }` produces an
 * SdkEnumType with isFixed=false.
 */
describe("ExtensibleEnumFile", () => {
  /**
   * Validates that a basic string-backed extensible enum generates a readonly
   * partial struct implementing IEquatable<T>. This is the foundational smoke
   * test for the extensible enum generation pipeline.
   */
  it("generates a readonly partial struct for a string-backed extensible enum", async () => {
    const [{ outputs }, diagnostics] = await HttpTester.compileAndDiagnose(`
      using TypeSpec.Http;

      @service
      namespace TestNamespace;

      union DaysOfWeek {
        string,
        Monday: "Monday",
        Tuesday: "Tuesday",
        Wednesday: "Wednesday",
      }

      @route("/test")
      op test(@query day: DaysOfWeek): void;
    `);

    expect(diagnostics).toHaveLength(0);

    const enumFileKey = Object.keys(outputs).find((k) =>
      k.includes("DaysOfWeek"),
    );
    expect(enumFileKey).toBeDefined();
    const enumFile = outputs[enumFileKey!];
    expect(enumFile).toBeDefined();

    // Core struct declaration
    expect(enumFile).toContain(
      "public readonly partial struct DaysOfWeek : IEquatable<DaysOfWeek>",
    );
  });

  /**
   * Validates that the auto-generated file header is present, including the
   * `// <auto-generated/>` marker and `#nullable disable` directive.
   * This matches the legacy emitter's golden file format.
   */
  it("includes the standard auto-generated header and using directives", async () => {
    const [{ outputs }, diagnostics] = await HttpTester.compileAndDiagnose(`
      using TypeSpec.Http;

      @service
      namespace TestNamespace;

      union Color {
        string,
        Red: "Red",
        Green: "Green",
        Blue: "Blue",
      }

      @route("/test")
      op test(@query color: Color): void;
    `);

    expect(diagnostics).toHaveLength(0);

    const enumFileKey = Object.keys(outputs).find((k) => k.includes("Color"));
    expect(enumFileKey).toBeDefined();
    const enumFile = outputs[enumFileKey!];

    expect(enumFile).toContain("// <auto-generated/>");
    expect(enumFile).toContain("#nullable disable");
    expect(enumFile).toContain("using System;");
    expect(enumFile).toContain("using System.ComponentModel;");
  });

  /**
   * Validates that the _value field and private const value fields are
   * generated correctly. The _value field stores the underlying value,
   * and each predefined member gets a const field with a "Value" suffix.
   */
  it("generates _value field and const value fields for string enums", async () => {
    const [{ outputs }, diagnostics] = await HttpTester.compileAndDiagnose(`
      using TypeSpec.Http;

      @service
      namespace TestNamespace;

      union Direction {
        string,
        North: "North",
        South: "South",
      }

      @route("/test")
      op test(@query dir: Direction): void;
    `);

    expect(diagnostics).toHaveLength(0);

    const enumFileKey = Object.keys(outputs).find((k) =>
      k.includes("Direction"),
    );
    expect(enumFileKey).toBeDefined();
    const enumFile = outputs[enumFileKey!];

    expect(enumFile).toContain("private readonly string _value;");
    expect(enumFile).toContain('private const string NorthValue = "North";');
    expect(enumFile).toContain('private const string SouthValue = "South";');
  });

  /**
   * Validates that the constructor includes Argument.AssertNotNull for
   * string-backed enums. This is critical for null safety — string is a
   * reference type, so the constructor must validate the input.
   */
  it("generates constructor with AssertNotNull for string-backed enums", async () => {
    const [{ outputs }, diagnostics] = await HttpTester.compileAndDiagnose(`
      using TypeSpec.Http;

      @service
      namespace TestNamespace;

      union Status {
        string,
        Active: "Active",
        Inactive: "Inactive",
      }

      @route("/test")
      op test(@query status: Status): void;
    `);

    expect(diagnostics).toHaveLength(0);

    const enumFileKey = Object.keys(outputs).find((k) => k.includes("Status"));
    expect(enumFileKey).toBeDefined();
    const enumFile = outputs[enumFileKey!];

    expect(enumFile).toContain("public Status(string value)");
    expect(enumFile).toContain("Argument.AssertNotNull(value, nameof(value));");
    expect(enumFile).toContain("_value = value;");
  });

  /**
   * Validates that static properties are generated for each predefined
   * enum member. Properties use auto-property syntax with initializers
   * that reference the const value fields.
   */
  it("generates static properties for each member", async () => {
    const [{ outputs }, diagnostics] = await HttpTester.compileAndDiagnose(`
      using TypeSpec.Http;

      @service
      namespace TestNamespace;

      union Priority {
        string,
        Low: "Low",
        Medium: "Medium",
        High: "High",
      }

      @route("/test")
      op test(@query priority: Priority): void;
    `);

    expect(diagnostics).toHaveLength(0);

    const enumFileKey = Object.keys(outputs).find((k) =>
      k.includes("Priority"),
    );
    expect(enumFileKey).toBeDefined();
    const enumFile = outputs[enumFileKey!];

    expect(enumFile).toContain(
      "public static Priority Low { get; } = new Priority(LowValue);",
    );
    expect(enumFile).toContain(
      "public static Priority Medium { get; } = new Priority(MediumValue);",
    );
    expect(enumFile).toContain(
      "public static Priority High { get; } = new Priority(HighValue);",
    );
  });

  /**
   * Validates that equality operators (== and !=) are generated.
   * Both operators delegate to the Equals instance method, which is
   * the standard pattern for IEquatable<T> implementations.
   */
  it("generates equality operators", async () => {
    const [{ outputs }, diagnostics] = await HttpTester.compileAndDiagnose(`
      using TypeSpec.Http;

      @service
      namespace TestNamespace;

      union Size {
        string,
        Small: "Small",
        Large: "Large",
      }

      @route("/test")
      op test(@query size: Size): void;
    `);

    expect(diagnostics).toHaveLength(0);

    const enumFileKey = Object.keys(outputs).find((k) => k.includes("Size"));
    expect(enumFileKey).toBeDefined();
    const enumFile = outputs[enumFileKey!];

    expect(enumFile).toContain(
      "public static bool operator ==(Size left, Size right) => left.Equals(right);",
    );
    expect(enumFile).toContain(
      "public static bool operator !=(Size left, Size right) => !left.Equals(right);",
    );
  });

  /**
   * Validates that implicit conversion operators are generated.
   * String-backed enums get both a non-nullable and nullable variant.
   * The nullable variant handles null input by returning null instead
   * of throwing.
   */
  it("generates implicit conversion with nullable variant for string enums", async () => {
    const [{ outputs }, diagnostics] = await HttpTester.compileAndDiagnose(`
      using TypeSpec.Http;

      @service
      namespace TestNamespace;

      union Format {
        string,
        Json: "Json",
        Xml: "Xml",
      }

      @route("/test")
      op test(@query format: Format): void;
    `);

    expect(diagnostics).toHaveLength(0);

    const enumFileKey = Object.keys(outputs).find((k) => k.includes("Format"));
    expect(enumFileKey).toBeDefined();
    const enumFile = outputs[enumFileKey!];

    // Non-nullable implicit operator
    expect(enumFile).toContain(
      "public static implicit operator Format(string value) => new Format(value);",
    );
    // Nullable implicit operator (string-backed only)
    expect(enumFile).toContain(
      "public static implicit operator Format?(string value) => value == null ? null : new Format(value);",
    );
  });

  /**
   * Validates that the Equals methods are generated correctly for string
   * enums. The string comparison uses InvariantCultureIgnoreCase to match
   * the legacy emitter behavior. The Equals(object) override is decorated
   * with [EditorBrowsable(Never)] to discourage direct use.
   */
  it("generates case-insensitive Equals for string enums", async () => {
    const [{ outputs }, diagnostics] = await HttpTester.compileAndDiagnose(`
      using TypeSpec.Http;

      @service
      namespace TestNamespace;

      union Mode {
        string,
        Auto: "Auto",
        Manual: "Manual",
      }

      @route("/test")
      op test(@query mode: Mode): void;
    `);

    expect(diagnostics).toHaveLength(0);

    const enumFileKey = Object.keys(outputs).find((k) => k.includes("Mode"));
    expect(enumFileKey).toBeDefined();
    const enumFile = outputs[enumFileKey!];

    // Equals(object) with EditorBrowsable
    expect(enumFile).toContain("[EditorBrowsable(EditorBrowsableState.Never)]");
    expect(enumFile).toContain(
      "public override bool Equals(object obj) => obj is Mode other && Equals(other);",
    );
    // Equals(T) with case-insensitive comparison
    expect(enumFile).toContain(
      "public bool Equals(Mode other) => string.Equals(_value, other._value, StringComparison.InvariantCultureIgnoreCase);",
    );
  });

  /**
   * Validates that GetHashCode uses StringComparer.InvariantCultureIgnoreCase
   * for string-backed enums, consistent with the case-insensitive Equals.
   * Also validates that ToString returns _value directly for string enums.
   */
  it("generates correct GetHashCode and ToString for string enums", async () => {
    const [{ outputs }, diagnostics] = await HttpTester.compileAndDiagnose(`
      using TypeSpec.Http;

      @service
      namespace TestNamespace;

      union Level {
        string,
        Info: "Info",
        Warn: "Warn",
      }

      @route("/test")
      op test(@query level: Level): void;
    `);

    expect(diagnostics).toHaveLength(0);

    const enumFileKey = Object.keys(outputs).find((k) => k.includes("Level"));
    expect(enumFileKey).toBeDefined();
    const enumFile = outputs[enumFileKey!];

    expect(enumFile).toContain(
      "StringComparer.InvariantCultureIgnoreCase.GetHashCode(_value)",
    );
    expect(enumFile).toContain("public override string ToString() => _value;");
  });

  /**
   * Validates that int-backed extensible enums are generated correctly.
   * Key differences from string-backed:
   * - No Argument.AssertNotNull (int is a value type)
   * - No nullable implicit operator
   * - Direct value comparison in Equals (not case-insensitive)
   * - Uses CultureInfo.InvariantCulture in ToString
   * - Includes System.Globalization using directive
   */
  it("generates int-backed extensible enum correctly", async () => {
    const [{ outputs }, diagnostics] = await HttpTester.compileAndDiagnose(`
      using TypeSpec.Http;

      @service
      namespace TestNamespace;

      union Priority {
        int32,
        Low: 1,
        High: 2,
        Critical: 10,
      }

      @route("/test")
      op test(@query priority: Priority): void;
    `);

    expect(diagnostics).toHaveLength(0);

    const enumFileKey = Object.keys(outputs).find((k) =>
      k.includes("Priority"),
    );
    expect(enumFileKey).toBeDefined();
    const enumFile = outputs[enumFileKey!];

    // Int type fields
    expect(enumFile).toContain("private readonly int _value;");
    expect(enumFile).toContain("private const int LowValue = 1;");
    expect(enumFile).toContain("private const int HighValue = 2;");
    expect(enumFile).toContain("private const int CriticalValue = 10;");

    // No AssertNotNull for value types
    expect(enumFile).not.toContain("AssertNotNull");

    // Int constructor
    expect(enumFile).toContain("public Priority(int value)");

    // Static properties
    expect(enumFile).toContain(
      "public static Priority Low { get; } = new Priority(LowValue);",
    );

    // Implicit conversion (no nullable variant)
    expect(enumFile).toContain(
      "public static implicit operator Priority(int value) => new Priority(value);",
    );
    expect(enumFile).not.toContain("Priority?");

    // Direct equality comparison
    expect(enumFile).toContain(
      "public bool Equals(Priority other) => Equals(_value, other._value);",
    );

    // Value-type GetHashCode
    expect(enumFile).toContain("_value.GetHashCode()");

    // CultureInfo.InvariantCulture in ToString
    expect(enumFile).toContain("using System.Globalization;");
    expect(enumFile).toContain(
      "public override string ToString() => _value.ToString(CultureInfo.InvariantCulture);",
    );
  });

  /**
   * Validates that float-backed extensible enums use the correct C# type
   * (float) and literal suffixes (F). This ensures the value type mapping
   * and literal formatting are correct for float32.
   */
  it("generates float-backed extensible enum with correct type and literals", async () => {
    const [{ outputs }, diagnostics] = await HttpTester.compileAndDiagnose(`
      using TypeSpec.Http;

      @service
      namespace TestNamespace;

      union Temperature {
        float32,
        Cold: 32.5,
        Warm: 72.0,
        Hot: 100.5,
      }

      @route("/test")
      op test(@query temp: Temperature): void;
    `);

    expect(diagnostics).toHaveLength(0);

    const enumFileKey = Object.keys(outputs).find((k) =>
      k.includes("Temperature"),
    );
    expect(enumFileKey).toBeDefined();
    const enumFile = outputs[enumFileKey!];

    // Float type
    expect(enumFile).toContain("private readonly float _value;");

    // Float literals with F suffix
    expect(enumFile).toContain("private const float ColdValue = 32.5F;");
    expect(enumFile).toContain("private const float WarmValue = 72F;");
    expect(enumFile).toContain("private const float HotValue = 100.5F;");

    // Float constructor
    expect(enumFile).toContain("public Temperature(float value)");

    // No AssertNotNull for value types
    expect(enumFile).not.toContain("AssertNotNull");
  });

  /**
   * Validates that the generated file is placed at the correct path and
   * wrapped in the correct namespace. The file should be generated at
   * `src/Generated/Models/{EnumName}.cs` within the service namespace.
   */
  it("generates file at correct path with correct namespace", async () => {
    const [{ outputs }, diagnostics] = await HttpTester.compileAndDiagnose(`
      using TypeSpec.Http;

      @service
      namespace MyService;

      union Region {
        string,
        East: "East",
        West: "West",
      }

      @route("/test")
      op test(@query region: Region): void;
    `);

    expect(diagnostics).toHaveLength(0);

    const enumFileKey = Object.keys(outputs).find((k) => k.includes("Region"));
    expect(enumFileKey).toBeDefined();
    expect(enumFileKey).toContain("src/Generated/Models/Region.cs");

    const enumFile = outputs[enumFileKey!];
    expect(enumFile).toContain("namespace MyService");
  });

  /**
   * Validates that no extensible enum files are generated when the TypeSpec
   * input has only fixed enums (standard enum declarations). This ensures
   * the emitter correctly distinguishes between fixed and extensible enums.
   */
  it("produces no extensible enum files for fixed enums", async () => {
    const [{ outputs }, diagnostics] = await HttpTester.compileAndDiagnose(`
      using TypeSpec.Http;

      @service
      namespace TestNamespace;

      enum FixedDays {
        Monday,
        Tuesday,
      }

      @route("/test")
      op test(@query day: FixedDays): void;
    `);

    expect(diagnostics).toHaveLength(0);

    // Should have enum files for fixed enums but no struct-based extensible files
    const structFiles = Object.keys(outputs).filter((k) => {
      const content = outputs[k];
      return content.includes("readonly partial struct");
    });
    expect(structFiles).toHaveLength(0);
  });
});
