import { describe, expect, it } from "vitest";
import { HttpTester } from "./test-host.js";

/**
 * Tests for the FixedEnumFile component.
 *
 * These tests verify that the emitter correctly generates C# enum declarations
 * for non-extensible (fixed) TypeSpec enums. Fixed enums map to standard C#
 * `enum` types with XML doc comments on each member.
 *
 * Why these tests matter:
 * - Enum generation is the first concrete code-generation component in the emitter.
 * - Validates the full pipeline: TypeSpec → TCGC → FixedEnumFile → C# output.
 * - Ensures doc comment fallback logic matches the legacy generator behavior.
 * - Verifies file path, namespace, and formatting conventions.
 */
describe("FixedEnumFile", () => {
  /**
   * Validates that a basic string-backed TypeSpec enum compiles and generates
   * a C# source file at the expected path. This is the simplest smoke test
   * for the full enum generation pipeline.
   */
  it("generates a file for a string-backed fixed enum", async () => {
    const [{ outputs }, diagnostics] = await HttpTester.compileAndDiagnose(`
      using TypeSpec.Http;

      @service
      namespace TestNamespace;

      enum DaysOfWeek {
        Monday,
        Tuesday,
        Wednesday,
      }

      @route("/test")
      op test(@query day: DaysOfWeek): void;
    `);

    expect(diagnostics).toHaveLength(0);

    // The enum file should be generated at the Models subdirectory
    const enumFileKey = Object.keys(outputs).find((k) =>
      k.includes("DaysOfWeek"),
    );
    expect(enumFileKey).toBeDefined();
    const enumFile = outputs[enumFileKey!];
    expect(enumFile).toBeDefined();

    // Verify the enum declaration structure
    expect(enumFile).toContain("public enum DaysOfWeek");
    expect(enumFile).toContain("Monday");
    expect(enumFile).toContain("Tuesday");
    expect(enumFile).toContain("Wednesday");
  });

  /**
   * Validates that the auto-generated file header is present, including the
   * `// <auto-generated/>` marker and `#nullable disable` directive.
   * This matches the legacy emitter's golden file format.
   */
  it("includes the standard auto-generated header", async () => {
    const [{ outputs }, diagnostics] = await HttpTester.compileAndDiagnose(`
      using TypeSpec.Http;

      @service
      namespace TestNamespace;

      enum Color {
        Red,
        Green,
        Blue,
      }

      @route("/test")
      op test(@query color: Color): void;
    `);

    expect(diagnostics).toHaveLength(0);

    const enumFileKey = Object.keys(outputs).find((k) =>
      k.includes("Color"),
    );
    expect(enumFileKey).toBeDefined();
    const enumFile = outputs[enumFileKey!];

    expect(enumFile).toContain("// <auto-generated/>");
    expect(enumFile).toContain("#nullable disable");
  });

  /**
   * Validates that XML doc comments are generated for each enum member.
   * When no explicit @doc decorator is used, the member name followed by
   * a period is used as the summary — matching legacy DocHelpers behavior.
   */
  it("generates XML doc comments for members", async () => {
    const [{ outputs }, diagnostics] = await HttpTester.compileAndDiagnose(`
      using TypeSpec.Http;

      @service
      namespace TestNamespace;

      enum Season {
        Spring,
        Summer,
        Autumn,
        Winter,
      }

      @route("/test")
      op test(@query season: Season): void;
    `);

    expect(diagnostics).toHaveLength(0);

    const enumFileKey = Object.keys(outputs).find((k) =>
      k.includes("Season"),
    );
    expect(enumFileKey).toBeDefined();
    const enumFile = outputs[enumFileKey!];

    // Each member should have a summary doc comment with fallback to name
    expect(enumFile).toContain("/// <summary> Spring. </summary>");
    expect(enumFile).toContain("/// <summary> Summer. </summary>");
    expect(enumFile).toContain("/// <summary> Autumn. </summary>");
    expect(enumFile).toContain("/// <summary> Winter. </summary>");
  });

  /**
   * Validates that the generated file is placed in the correct namespace.
   * The namespace comes from the TCGC SdkEnumType.namespace property.
   */
  it("wraps the enum in the correct namespace", async () => {
    const [{ outputs }, diagnostics] = await HttpTester.compileAndDiagnose(`
      using TypeSpec.Http;

      @service
      namespace MyService;

      enum Priority {
        Low,
        Medium,
        High,
      }

      @route("/test")
      op test(@query priority: Priority): void;
    `);

    expect(diagnostics).toHaveLength(0);

    const enumFileKey = Object.keys(outputs).find((k) =>
      k.includes("Priority"),
    );
    expect(enumFileKey).toBeDefined();
    const enumFile = outputs[enumFileKey!];

    expect(enumFile).toContain("namespace MyService");
  });

  /**
   * Validates that string-backed enums have no explicit initialization values.
   * In C#, string-backed fixed enums use serialization extension methods
   * rather than explicit values (which C# enums don't support for strings).
   */
  it("does not emit initialization values for string-backed enums", async () => {
    const [{ outputs }, diagnostics] = await HttpTester.compileAndDiagnose(`
      using TypeSpec.Http;

      @service
      namespace TestNamespace;

      enum Fruit {
        Apple,
        Banana,
        Cherry,
      }

      @route("/test")
      op test(@query fruit: Fruit): void;
    `);

    expect(diagnostics).toHaveLength(0);

    const enumFileKey = Object.keys(outputs).find((k) =>
      k.includes("Fruit"),
    );
    expect(enumFileKey).toBeDefined();
    const enumFile = outputs[enumFileKey!];

    // String-backed enums should not have "=" assignments
    expect(enumFile).not.toMatch(/Apple\s*=/);
    expect(enumFile).not.toMatch(/Banana\s*=/);
    expect(enumFile).not.toMatch(/Cherry\s*=/);
  });

  /**
   * Validates that no enum files are generated when the TypeSpec input has
   * no enum definitions. This ensures the emitter doesn't produce empty
   * or spurious output files.
   */
  it("produces no enum files when no enums exist", async () => {
    const [{ outputs }, diagnostics] = await HttpTester.compileAndDiagnose(`
      op test(): void;
    `);

    expect(diagnostics).toHaveLength(0);
    expect(Object.keys(outputs)).toHaveLength(0);
  });

  /**
   * Validates that @doc decorators on enum members are used for XML doc
   * comments instead of the fallback member name. This ensures explicit
   * documentation takes precedence.
   */
  it("uses @doc decorator content for member doc comments", async () => {
    const [{ outputs }, diagnostics] = await HttpTester.compileAndDiagnose(`
      using TypeSpec.Http;

      @service
      namespace TestNamespace;

      enum Status {
        @doc("The operation is currently active.")
        Active,
        @doc("The operation has been paused.")
        Paused,
      }

      @route("/test")
      op test(@query status: Status): void;
    `);

    expect(diagnostics).toHaveLength(0);

    const enumFileKey = Object.keys(outputs).find((k) =>
      k.includes("Status"),
    );
    expect(enumFileKey).toBeDefined();
    const enumFile = outputs[enumFileKey!];

    expect(enumFile).toContain("The operation is currently active.");
    expect(enumFile).toContain("The operation has been paused.");
  });
});
