import { describe, expect, it } from "vitest";
import { HttpTester } from "./test-host.js";

/**
 * Tests for the FixedEnumFile component.
 *
 * These tests verify that the emitter correctly generates C# enum declarations
 * for non-extensible (fixed) TypeSpec enums. Fixed enums map to standard C#
 * `enum` types with XML doc comments on each member.
 *
 * Why these tests matter:
 * - Enum generation is the first concrete code-generation component in the emitter.
 * - Validates the full pipeline: TypeSpec → TCGC → FixedEnumFile → C# output.
 * - Ensures doc comment fallback logic matches the legacy generator behavior.
 * - Verifies file path, namespace, and formatting conventions.
 */
describe("FixedEnumFile", () => {
  /**
   * Validates that a basic string-backed TypeSpec enum compiles and generates
   * a C# source file at the expected path. This is the simplest smoke test
   * for the full enum generation pipeline.
   */
  it("generates a file for a string-backed fixed enum", async () => {
    const [{ outputs }, diagnostics] = await HttpTester.compileAndDiagnose(`
      using TypeSpec.Http;

      @service
      namespace TestNamespace;

      enum DaysOfWeek {
        Monday,
        Tuesday,
        Wednesday,
      }

      @route("/test")
      op test(@query day: DaysOfWeek): void;
    `);

    expect(diagnostics).toHaveLength(0);

    // The enum file should be generated at the Models subdirectory
    const enumFileKey = Object.keys(outputs).find((k) =>
      k.includes("DaysOfWeek"),
    );
    expect(enumFileKey).toBeDefined();
    const enumFile = outputs[enumFileKey!];
    expect(enumFile).toBeDefined();

    // Verify the enum declaration structure
    expect(enumFile).toContain("public enum DaysOfWeek");
    expect(enumFile).toContain("Monday");
    expect(enumFile).toContain("Tuesday");
    expect(enumFile).toContain("Wednesday");
  });

  /**
   * Validates that the auto-generated file header is present, including the
   * `// <auto-generated/>` marker and `#nullable disable` directive.
   * This matches the legacy emitter's golden file format.
   */
  it("includes the standard auto-generated header", async () => {
    const [{ outputs }, diagnostics] = await HttpTester.compileAndDiagnose(`
      using TypeSpec.Http;

      @service
      namespace TestNamespace;

      enum Color {
        Red,
        Green,
        Blue,
      }

      @route("/test")
      op test(@query color: Color): void;
    `);

    expect(diagnostics).toHaveLength(0);

    const enumFileKey = Object.keys(outputs).find((k) => k.includes("Color"));
    expect(enumFileKey).toBeDefined();
    const enumFile = outputs[enumFileKey!];

    expect(enumFile).toContain("// <auto-generated/>");
    expect(enumFile).toContain("#nullable disable");
  });

  /**
   * Validates that XML doc comments are generated for each enum member.
   * When no explicit @doc decorator is used, the member name followed by
   * a period is used as the summary — matching legacy DocHelpers behavior.
   */
  it("generates XML doc comments for members", async () => {
    const [{ outputs }, diagnostics] = await HttpTester.compileAndDiagnose(`
      using TypeSpec.Http;

      @service
      namespace TestNamespace;

      enum Season {
        Spring,
        Summer,
        Autumn,
        Winter,
      }

      @route("/test")
      op test(@query season: Season): void;
    `);

    expect(diagnostics).toHaveLength(0);

    const enumFileKey = Object.keys(outputs).find((k) => k.includes("Season"));
    expect(enumFileKey).toBeDefined();
    const enumFile = outputs[enumFileKey!];

    // Each member should have a summary doc comment with fallback to name
    expect(enumFile).toContain("/// <summary> Spring. </summary>");
    expect(enumFile).toContain("/// <summary> Summer. </summary>");
    expect(enumFile).toContain("/// <summary> Autumn. </summary>");
    expect(enumFile).toContain("/// <summary> Winter. </summary>");
  });

  /**
   * Validates that the generated file is placed in the correct namespace.
   * The namespace comes from the TCGC SdkEnumType.namespace property.
   */
  it("wraps the enum in the correct namespace", async () => {
    const [{ outputs }, diagnostics] = await HttpTester.compileAndDiagnose(`
      using TypeSpec.Http;

      @service
      namespace MyService;

      enum Priority {
        Low,
        Medium,
        High,
      }

      @route("/test")
      op test(@query priority: Priority): void;
    `);

    expect(diagnostics).toHaveLength(0);

    const enumFileKey = Object.keys(outputs).find((k) =>
      k.includes("Priority"),
    );
    expect(enumFileKey).toBeDefined();
    const enumFile = outputs[enumFileKey!];

    expect(enumFile).toContain("namespace MyService");
  });

  /**
   * Validates that string-backed enums have no explicit initialization values.
   * In C#, string-backed fixed enums use serialization extension methods
   * rather than explicit values (which C# enums don't support for strings).
   */
  it("does not emit initialization values for string-backed enums", async () => {
    const [{ outputs }, diagnostics] = await HttpTester.compileAndDiagnose(`
      using TypeSpec.Http;

      @service
      namespace TestNamespace;

      enum Fruit {
        Apple,
        Banana,
        Cherry,
      }

      @route("/test")
      op test(@query fruit: Fruit): void;
    `);

    expect(diagnostics).toHaveLength(0);

    const enumFileKey = Object.keys(outputs).find((k) => k.includes("Fruit"));
    expect(enumFileKey).toBeDefined();
    const enumFile = outputs[enumFileKey!];

    // String-backed enums should not have "=" assignments
    expect(enumFile).not.toMatch(/Apple\s*=/);
    expect(enumFile).not.toMatch(/Banana\s*=/);
    expect(enumFile).not.toMatch(/Cherry\s*=/);
  });

  /**
   * Validates that no enum files are generated when the TypeSpec input has
   * no enum definitions. This ensures the emitter doesn't produce empty
   * or spurious output files. Infrastructure files (Internal/) are excluded
   * from this check since they are always generated as standard scaffolding.
   */
  it("produces no enum files when no enums exist", async () => {
    const [{ outputs }, diagnostics] = await HttpTester.compileAndDiagnose(`
      op test(): void;
    `);

    expect(diagnostics).toHaveLength(0);
    const csFiles = Object.keys(outputs).filter(
      (k) => k.endsWith(".cs") && !k.includes("/Internal/"),
    );
    expect(csFiles).toHaveLength(0);
  });

  /**
   * Validates that int-backed fixed enums include explicit initialization values
   * on each member (e.g., `One = 1, Two = 2`). This is critical because C# enums
   * natively support integer values, and the generated code must preserve the
   * specific integer mappings defined in the TypeSpec source. The legacy emitter
   * only embeds values for int-backed enums (not string or float).
   */
  it("emits initialization values for int-backed fixed enums", async () => {
    const [{ outputs }, diagnostics] = await HttpTester.compileAndDiagnose(`
      using TypeSpec.Http;

      @service
      namespace TestNamespace;

      enum Priority {
        Low: 0,
        Medium: 1,
        High: 2,
        Critical: 10,
      }

      @route("/test")
      op test(@query priority: Priority): void;
    `);

    expect(diagnostics).toHaveLength(0);

    const enumFileKey = Object.keys(outputs).find((k) =>
      k.includes("Priority"),
    );
    expect(enumFileKey).toBeDefined();
    const enumFile = outputs[enumFileKey!];

    // Int-backed enums must have "= value" assignments
    expect(enumFile).toContain("Low = 0");
    expect(enumFile).toContain("Medium = 1");
    expect(enumFile).toContain("High = 2");
    expect(enumFile).toContain("Critical = 10");
  });

  /**
   * Validates that float-backed fixed enums do NOT include initialization values.
   * C# enums cannot hold float constants, so float values are handled by
   * serialization extension methods (similar to string-backed enums).
   * This matches the legacy emitter's behavior where only int-backed enums
   * get explicit values.
   */
  it("does not emit initialization values for float-backed fixed enums", async () => {
    const [{ outputs }, diagnostics] = await HttpTester.compileAndDiagnose(`
      using TypeSpec.Http;

      @service
      namespace TestNamespace;

      enum Temperature {
        Cold: 32.5,
        Warm: 72.0,
        Hot: 100.5,
      }

      @route("/test")
      op test(@query temp: Temperature): void;
    `);

    expect(diagnostics).toHaveLength(0);

    const enumFileKey = Object.keys(outputs).find((k) =>
      k.includes("Temperature"),
    );
    expect(enumFileKey).toBeDefined();
    const enumFile = outputs[enumFileKey!];

    // Float-backed enums should NOT have "=" assignments
    expect(enumFile).not.toMatch(/Cold\s*=/);
    expect(enumFile).not.toMatch(/Warm\s*=/);
    expect(enumFile).not.toMatch(/Hot\s*=/);

    // But members should still exist
    expect(enumFile).toContain("Cold");
    expect(enumFile).toContain("Warm");
    expect(enumFile).toContain("Hot");
  });

  /**
   * Validates that int-backed enums with non-sequential values preserve the
   * exact integer values. This covers flag-style enums where values are
   * powers of 2 or otherwise non-contiguous.
   */
  it("preserves non-sequential int values", async () => {
    const [{ outputs }, diagnostics] = await HttpTester.compileAndDiagnose(`
      using TypeSpec.Http;

      @service
      namespace TestNamespace;

      enum Permissions {
        Read: 1,
        Write: 2,
        Execute: 4,
        Admin: 8,
      }

      @route("/test")
      op test(@query perm: Permissions): void;
    `);

    expect(diagnostics).toHaveLength(0);

    const enumFileKey = Object.keys(outputs).find((k) =>
      k.includes("Permissions"),
    );
    expect(enumFileKey).toBeDefined();
    const enumFile = outputs[enumFileKey!];

    expect(enumFile).toContain("Read = 1");
    expect(enumFile).toContain("Write = 2");
    expect(enumFile).toContain("Execute = 4");
    expect(enumFile).toContain("Admin = 8");
  });

  /**
   * Validates that @doc decorators on enum members are used for XML doc
   * comments instead of the fallback member name. This ensures explicit
   * documentation takes precedence.
   */
  it("uses @doc decorator content for member doc comments", async () => {
    const [{ outputs }, diagnostics] = await HttpTester.compileAndDiagnose(`
      using TypeSpec.Http;

      @service
      namespace TestNamespace;

      enum Status {
        @doc("The operation is currently active.")
        Active,
        @doc("The operation has been paused.")
        Paused,
      }

      @route("/test")
      op test(@query status: Status): void;
    `);

    expect(diagnostics).toHaveLength(0);

    const enumFileKey = Object.keys(outputs).find((k) => k.includes("Status"));
    expect(enumFileKey).toBeDefined();
    const enumFile = outputs[enumFileKey!];

    expect(enumFile).toContain("The operation is currently active.");
    expect(enumFile).toContain("The operation has been paused.");
  });

  /**
   * Validates that enum members whose names start with a digit (e.g., float
   * literal union values like "1.25", "2.375") are emitted as valid C# identifiers.
   *
   * TCGC preserves float literal union values verbatim as enum member names
   * (e.g., "1.25"). In C#, identifiers cannot start with a digit, so the legacy
   * emitter prefixes them with "_" and removes the decimal point:
   *   "1.25" → "_125", "2.375" → "_2375"
   *
   * This test ensures our emitter matches that behavior and produces compilable code.
   * Without this fix, the emitter generated "1_25" (invalid C# identifier).
   */
  it("generates valid C# identifiers for numeric-starting enum member names", async () => {
    const [{ outputs }, diagnostics] = await HttpTester.compileAndDiagnose(`
      using TypeSpec.Http;

      @service
      namespace TestNamespace;

      model Widget {
        floatProp?: 1.25 | 2.375;
        intProp?: 1 | 2;
      }

      @route("/test")
      op test(): Widget;
    `);

    expect(diagnostics).toHaveLength(0);

    // Float literal union → enum with "_125", "_2375" (not "1_25", "2_375")
    // The enum file name is derived from the model+property names by TCGC
    const floatEnumKey = Object.keys(outputs).find(
      (k) =>
        k.includes("Models") &&
        k.endsWith(".cs") &&
        !k.includes("Serialization"),
    );
    const allModelFiles = Object.entries(outputs)
      .filter(
        ([k]) =>
          k.includes("Models") &&
          k.endsWith(".cs") &&
          !k.includes("Serialization"),
      )
      .map(([, v]) => v)
      .join("\n");

    // Must contain valid C# identifiers: _125 and _2375
    expect(allModelFiles).toContain("_125");
    expect(allModelFiles).toContain("_2375");
    // Must NOT contain invalid identifiers starting with digits
    expect(allModelFiles).not.toContain("\n    1_25,");
    expect(allModelFiles).not.toContain("\n    2_375");

    // Int literal union → enum with "_1 = 1", "_2 = 2" (not bare "1 = 1", "2 = 2")
    expect(allModelFiles).toContain("_1 = 1");
    expect(allModelFiles).toContain("_2 = 2");
  });
});
