import { describe, it, expect } from "vitest";
import { getLicenseHeader } from "../src/utils/header.js";
import type { ResolvedCSharpEmitterOptions } from "../src/options.js";
import { defaultOptions } from "../src/options.js";

/**
 * Tests for the license header utility in src/utils/header.ts.
 *
 * These tests validate that getLicenseHeader() produces the correct C# file
 * header for all configuration combinations. Every generated C# file starts
 * with this header, so incorrect output would affect all downstream files.
 *
 * The header format must match the legacy emitter's output exactly:
 *   // Copyright (c) {company}. All rights reserved.
 *   // Licensed under the {name}.
 *   (blank line)
 *   // <auto-generated/>
 *   (blank line)
 *   #nullable disable
 *
 * Getting this wrong would cause diffs against golden files and break
 * downstream consumers that parse the auto-generated marker.
 */

/** Helper to create resolved options with specific license config. */
function makeOptions(
  license?: ResolvedCSharpEmitterOptions["license"],
): ResolvedCSharpEmitterOptions {
  return { ...defaultOptions, license };
}

describe("getLicenseHeader", () => {
  /**
   * The standard case: both company and license name are provided.
   * This matches the golden file format seen in the legacy emitter's
   * test projects (e.g., "Microsoft" company, "MIT License" name).
   * The output must include the copyright line, license line, auto-generated
   * marker, and nullable disable — separated by blank lines in the right places.
   */
  it("generates header with company and license name", () => {
    const header = getLicenseHeader(
      makeOptions({ name: "MIT License", company: "Microsoft" }),
    );

    expect(header).toBe(
      [
        "// Copyright (c) Microsoft. All rights reserved.",
        "// Licensed under the MIT License.",
        "",
        "// <auto-generated/>",
        "",
        "#nullable disable",
      ].join("\n"),
    );
  });

  /**
   * When only the license name is provided (no company), the copyright line
   * should be omitted. This handles open-source projects that may not have
   * a specific company attribution.
   */
  it("generates header with only license name (no company)", () => {
    const header = getLicenseHeader(makeOptions({ name: "Apache-2.0" }));

    expect(header).toBe(
      [
        "// Licensed under the Apache-2.0.",
        "",
        "// <auto-generated/>",
        "",
        "#nullable disable",
      ].join("\n"),
    );
  });

  /**
   * When a raw header string is provided via the `header` field, it should
   * be used instead of constructing from company/name. Each line of the raw
   * header gets a "// " prefix, matching the legacy CodeWriter behavior
   * that splits on newlines and prepends comment markers.
   */
  it("uses raw header string when provided", () => {
    const header = getLicenseHeader(
      makeOptions({
        name: "MIT",
        header:
          "Copyright (c) Contoso Ltd. All rights reserved.\nLicensed under the MIT License.",
      }),
    );

    expect(header).toBe(
      [
        "// Copyright (c) Contoso Ltd. All rights reserved.",
        "// Licensed under the MIT License.",
        "",
        "// <auto-generated/>",
        "",
        "#nullable disable",
      ].join("\n"),
    );
  });

  /**
   * When no license options are provided at all, the header should contain
   * only the auto-generated marker and nullable directive. This is the
   * minimal header that every generated file must have regardless of
   * license configuration.
   */
  it("generates minimal header when no license is configured", () => {
    const header = getLicenseHeader(makeOptions());

    expect(header).toBe(
      ["// <auto-generated/>", "", "#nullable disable"].join("\n"),
    );
  });

  /**
   * When license options exist but no company is set, only the license
   * line should appear. This ensures we don't emit an empty or malformed
   * copyright line.
   */
  it("omits copyright line when company is undefined", () => {
    const header = getLicenseHeader(makeOptions({ name: "BSD-3-Clause" }));

    expect(header).not.toContain("Copyright");
    expect(header).toContain("// Licensed under the BSD-3-Clause.");
  });

  /**
   * The auto-generated marker must always be present in every header.
   * Tools and IDEs rely on this marker to identify generated files and
   * skip them during analysis (e.g., code review, linting).
   */
  it("always includes auto-generated marker", () => {
    const withLicense = getLicenseHeader(
      makeOptions({ name: "MIT", company: "Test" }),
    );
    const withoutLicense = getLicenseHeader(makeOptions());

    expect(withLicense).toContain("// <auto-generated/>");
    expect(withoutLicense).toContain("// <auto-generated/>");
  });

  /**
   * The #nullable disable directive must always be present.
   * Generated C# code uses nullable reference types selectively, and
   * this directive prevents the compiler from emitting nullable warnings
   * for generated code.
   */
  it("always includes #nullable disable", () => {
    const withLicense = getLicenseHeader(
      makeOptions({ name: "MIT", company: "Test" }),
    );
    const withoutLicense = getLicenseHeader(makeOptions());

    expect(withLicense).toContain("#nullable disable");
    expect(withoutLicense).toContain("#nullable disable");
  });

  /**
   * Raw header strings may contain Windows-style line endings (\r\n).
   * The function must handle these correctly, splitting on both \n and \r\n
   * to avoid leftover \r characters in the output.
   */
  it("handles Windows-style line endings in raw header", () => {
    const header = getLicenseHeader(
      makeOptions({
        name: "MIT",
        header: "Line one\r\nLine two",
      }),
    );

    expect(header).toContain("// Line one\n// Line two");
    expect(header).not.toContain("\r");
  });

  /**
   * Validates the exact golden-file format used by the legacy emitter.
   * This is the definitive format test — if this passes, the header will
   * match what the legacy emitter produces for the standard Microsoft/MIT
   * configuration used across all Azure SDK test projects.
   */
  it("matches the legacy emitter golden file format exactly", () => {
    const header = getLicenseHeader(
      makeOptions({ name: "MIT License", company: "Microsoft" }),
    );

    // This is the exact header from any golden file in
    // submodules/typespec/packages/http-client-csharp/generator/TestProjects/
    const expected =
      "// Copyright (c) Microsoft. All rights reserved.\n" +
      "// Licensed under the MIT License.\n" +
      "\n" +
      "// <auto-generated/>\n" +
      "\n" +
      "#nullable disable";

    expect(header).toBe(expected);
  });
});
