import { describe, expect, it } from "vitest";
import { HttpTester } from "./test-host.js";

/**
 * Tests for the ModelSerializationFile component.
 *
 * These tests verify that the emitter generates `.Serialization.cs` partial class
 * files for models that implement `IJsonModel<T>`. The ModelSerializationFile component
 * is responsible for the serialization file skeleton: header, namespace, partial class
 * declaration with the `IJsonModel<T>` interface, and correct access modifiers.
 *
 * Why these tests matter:
 * - Serialization files are the foundation for all model serialization/deserialization
 *   code (JSON write, JSON read, cast operators, etc.).
 * - Validates that the correct file path (`{Name}.Serialization.cs`) is used.
 * - Ensures the `IJsonModel<T>` interface is properly declared, which is required
 *   for the System.ClientModel serialization framework.
 * - Verifies that derived models re-declare their base type in the serialization file.
 * - Ensures abstract models get the `abstract` modifier in the serialization file.
 */
describe("ModelSerializationFile", () => {
  /**
   * Validates that a `.Serialization.cs` file is generated at the expected path
   * alongside the regular model file. Both files must exist for a complete model.
   */
  it("generates a serialization file at the correct path", async () => {
    const [{ outputs }, diagnostics] = await HttpTester.compileAndDiagnose(`
      using TypeSpec.Http;

      @service
      namespace TestNamespace;

      model Widget {
        name: string;
      }

      @route("/test")
      op test(): Widget;
    `);

    expect(diagnostics).toHaveLength(0);

    const serializationFileKey = Object.keys(outputs).find((k) =>
      k.includes("Widget.Serialization.cs"),
    );
    expect(serializationFileKey).toBeDefined();
    expect(serializationFileKey).toContain(
      "src/Generated/Models/Widget.Serialization.cs",
    );
  });

  /**
   * Validates that the serialization file includes the standard auto-generated
   * header (`// <auto-generated/>` and `#nullable disable`). This must match
   * the legacy emitter's golden file format.
   */
  it("includes the standard auto-generated header", async () => {
    const [{ outputs }, diagnostics] = await HttpTester.compileAndDiagnose(`
      using TypeSpec.Http;

      @service
      namespace TestNamespace;

      model Widget {
        name: string;
      }

      @route("/test")
      op test(): Widget;
    `);

    expect(diagnostics).toHaveLength(0);

    const fileKey = Object.keys(outputs).find((k) =>
      k.includes("Widget.Serialization.cs"),
    );
    const content = outputs[fileKey!];

    expect(content).toContain("// <auto-generated/>");
    expect(content).toContain("#nullable disable");
  });

  /**
   * Validates that the serialization class declares `IJsonModel<T>` as an interface.
   * This is the core requirement — the `IJsonModel<T>` interface (which inherits from
   * `IPersistableModel<T>`) is how the System.ClientModel framework discovers
   * serializable models.
   */
  it("declares IJsonModel<T> interface on the partial class", async () => {
    const [{ outputs }, diagnostics] = await HttpTester.compileAndDiagnose(`
      using TypeSpec.Http;

      @service
      namespace TestNamespace;

      model Widget {
        name: string;
      }

      @route("/test")
      op test(): Widget;
    `);

    expect(diagnostics).toHaveLength(0);

    const fileKey = Object.keys(outputs).find((k) =>
      k.includes("Widget.Serialization.cs"),
    );
    const content = outputs[fileKey!];

    // Must be a partial class implementing IJsonModel<Widget>
    expect(content).toMatch(
      /public\s+partial\s+class\s+Widget\s*:\s*IJsonModel<Widget>/,
    );
  });

  /**
   * Validates that the `using System.ClientModel.Primitives;` directive is
   * auto-generated because IJsonModel<T> is referenced from that namespace.
   * This using statement is critical for the serialization code to compile.
   */
  it("includes using directive for System.ClientModel.Primitives", async () => {
    const [{ outputs }, diagnostics] = await HttpTester.compileAndDiagnose(`
      using TypeSpec.Http;

      @service
      namespace TestNamespace;

      model Widget {
        name: string;
      }

      @route("/test")
      op test(): Widget;
    `);

    expect(diagnostics).toHaveLength(0);

    const fileKey = Object.keys(outputs).find((k) =>
      k.includes("Widget.Serialization.cs"),
    );
    const content = outputs[fileKey!];

    expect(content).toContain("using System.ClientModel.Primitives;");
  });

  /**
   * Validates that the serialization class is in the correct namespace,
   * matching the model's namespace from the TCGC SDK type.
   */
  it("wraps the class in the correct namespace", async () => {
    const [{ outputs }, diagnostics] = await HttpTester.compileAndDiagnose(`
      using TypeSpec.Http;

      @service
      namespace TestNamespace;

      model Widget {
        name: string;
      }

      @route("/test")
      op test(): Widget;
    `);

    expect(diagnostics).toHaveLength(0);

    const fileKey = Object.keys(outputs).find((k) =>
      k.includes("Widget.Serialization.cs"),
    );
    const content = outputs[fileKey!];

    expect(content).toMatch(/namespace\s+TestNamespace/);
  });

  /**
   * Validates that derived models re-declare the base type in the serialization
   * file's class declaration. C# requires all partial declarations to agree on
   * the base class. For example: `public partial class Dog : Pet, IJsonModel<Dog>`.
   */
  it("re-declares base type for derived models", async () => {
    const [{ outputs }, diagnostics] = await HttpTester.compileAndDiagnose(`
      using TypeSpec.Http;

      @service
      namespace TestNamespace;

      @discriminator("kind")
      model Pet {
        kind: string;
        name: string;
      }

      model Dog extends Pet {
        kind: "dog";
        breed: string;
      }

      @route("/test")
      op test(): Pet;
    `);

    expect(diagnostics).toHaveLength(0);

    const dogFileKey = Object.keys(outputs).find((k) =>
      k.includes("Dog.Serialization.cs"),
    );
    expect(dogFileKey).toBeDefined();
    const dogContent = outputs[dogFileKey!];

    // Derived model must re-declare base type and implement IJsonModel<Dog>
    expect(dogContent).toMatch(
      /public\s+partial\s+class\s+Dog\s*:\s*Pet,\s*IJsonModel<Dog>/,
    );
  });

  /**
   * Validates that abstract base models with discriminators get the `abstract`
   * modifier in the serialization file, matching the main model file's declaration.
   * Abstract models cannot be instantiated directly — only derived types can.
   */
  it("applies abstract modifier for discriminated base models", async () => {
    const [{ outputs }, diagnostics] = await HttpTester.compileAndDiagnose(`
      using TypeSpec.Http;

      @service
      namespace TestNamespace;

      @discriminator("kind")
      model Pet {
        kind: string;
        name: string;
      }

      model Dog extends Pet {
        kind: "dog";
        breed: string;
      }

      @route("/test")
      op test(): Pet;
    `);

    expect(diagnostics).toHaveLength(0);

    const petFileKey = Object.keys(outputs).find((k) =>
      k.includes("Pet.Serialization.cs"),
    );
    expect(petFileKey).toBeDefined();
    const petContent = outputs[petFileKey!];

    // Base model must be abstract in the serialization file
    expect(petContent).toMatch(
      /public\s+abstract\s+partial\s+class\s+Pet\s*:\s*IJsonModel<Pet>/,
    );
  });

  /**
   * Validates that each model in the SDK package gets its own serialization file,
   * including both base and derived models in a discriminator hierarchy.
   */
  it("generates serialization files for all models in hierarchy", async () => {
    const [{ outputs }, diagnostics] = await HttpTester.compileAndDiagnose(`
      using TypeSpec.Http;

      @service
      namespace TestNamespace;

      @discriminator("kind")
      model Pet {
        kind: string;
        name: string;
      }

      model Dog extends Pet {
        kind: "dog";
        breed: string;
      }

      model Cat extends Pet {
        kind: "cat";
        indoor: boolean;
      }

      @route("/test")
      op test(): Pet;
    `);

    expect(diagnostics).toHaveLength(0);

    const serializationFiles = Object.keys(outputs).filter((k) =>
      k.includes(".Serialization.cs"),
    );

    // All three models should have serialization files
    expect(
      serializationFiles.some((k) => k.includes("Pet.Serialization.cs")),
    ).toBe(true);
    expect(
      serializationFiles.some((k) => k.includes("Dog.Serialization.cs")),
    ).toBe(true);
    expect(
      serializationFiles.some((k) => k.includes("Cat.Serialization.cs")),
    ).toBe(true);
  });
});

/**
 * Tests for the DeserializationConstructor component.
 *
 * These tests verify that the emitter generates a parameterless `internal`
 * constructor in the `.Serialization.cs` partial class for models that need it.
 * The MRW (Model Reader/Writer) framework requires this constructor to create
 * empty model instances during deserialization.
 *
 * Why these tests matter:
 * - Without this constructor, the MRW framework cannot instantiate models for
 *   deserialization, causing runtime failures.
 * - The constructor must only be generated when the model's public init ctor
 *   has parameters — otherwise, a duplicate parameterless constructor would
 *   cause a C# compilation error.
 * - The XML doc comment format must match the legacy emitter's golden files.
 */
describe("DeserializationConstructor", () => {
  /**
   * Validates that a model with required properties gets a parameterless
   * internal constructor in its serialization file. Since the public init
   * ctor has parameters (name, value), no parameterless ctor exists, so
   * the deserialization constructor must be generated.
   */
  it("generates internal parameterless constructor for models with required properties", async () => {
    const [{ outputs }, diagnostics] = await HttpTester.compileAndDiagnose(`
      using TypeSpec.Http;

      @service
      namespace TestNamespace;

      model Widget {
        name: string;
        value: int32;
      }

      @route("/test")
      op test(): Widget;
    `);

    expect(diagnostics).toHaveLength(0);

    const fileKey = Object.keys(outputs).find((k) =>
      k.includes("Widget.Serialization.cs"),
    );
    const content = outputs[fileKey!];

    expect(content).toMatch(/internal\s+Widget\s*\(\s*\)/);
  });

  /**
   * Validates that the XML doc comment on the deserialization constructor
   * matches the legacy emitter's format: `/// <summary> Initializes a new
   * instance of <see cref="ModelName"/> for deserialization. </summary>`.
   * This ensures consistency with golden files.
   */
  it("includes XML doc comment for deserialization", async () => {
    const [{ outputs }, diagnostics] = await HttpTester.compileAndDiagnose(`
      using TypeSpec.Http;

      @service
      namespace TestNamespace;

      model Widget {
        name: string;
      }

      @route("/test")
      op test(): Widget;
    `);

    expect(diagnostics).toHaveLength(0);

    const fileKey = Object.keys(outputs).find((k) =>
      k.includes("Widget.Serialization.cs"),
    );
    const content = outputs[fileKey!];

    expect(content).toContain(
      '/// <summary> Initializes a new instance of <see cref="Widget"/> for deserialization. </summary>',
    );
  });

  /**
   * Validates that models with only optional properties do NOT get the
   * deserialization constructor. When all properties are optional, the
   * public init ctor has zero parameters, so it already serves as the
   * parameterless constructor — generating another would cause a C#
   * duplicate constructor error.
   */
  it("skips constructor for models with only optional properties", async () => {
    const [{ outputs }, diagnostics] = await HttpTester.compileAndDiagnose(`
      using TypeSpec.Http;

      @service
      namespace TestNamespace;

      model Widget {
        name?: string;
        value?: int32;
      }

      @route("/test")
      op test(): Widget;
    `);

    expect(diagnostics).toHaveLength(0);

    const fileKey = Object.keys(outputs).find((k) =>
      k.includes("Widget.Serialization.cs"),
    );
    const content = outputs[fileKey!];

    // Should NOT contain a parameterless internal constructor since
    // the public ctor already has zero parameters
    expect(content).not.toMatch(/internal\s+Widget\s*\(\s*\)/);
  });

  /**
   * Validates that derived models in a discriminator hierarchy get the
   * deserialization constructor when they have required base properties
   * (excluding the discriminator). For example, if Pet has `name: string`,
   * Dog extends Pet with `kind: "dog"` — Dog's public ctor takes `name`,
   * so Dog needs a parameterless deserialization ctor.
   */
  it("generates constructor for derived models with required base properties", async () => {
    const [{ outputs }, diagnostics] = await HttpTester.compileAndDiagnose(`
      using TypeSpec.Http;

      @service
      namespace TestNamespace;

      @discriminator("kind")
      model Pet {
        kind: string;
        name: string;
      }

      model Dog extends Pet {
        kind: "dog";
        breed: string;
      }

      @route("/test")
      op test(): Pet;
    `);

    expect(diagnostics).toHaveLength(0);

    const dogFileKey = Object.keys(outputs).find((k) =>
      k.includes("Dog.Serialization.cs"),
    );
    const dogContent = outputs[dogFileKey!];

    // Dog has required base params (name) + own params (breed),
    // so it needs a parameterless deserialization ctor
    expect(dogContent).toMatch(/internal\s+Dog\s*\(\s*\)/);
    expect(dogContent).toContain(
      '/// <summary> Initializes a new instance of <see cref="Dog"/> for deserialization. </summary>',
    );
  });

  /**
   * Validates that derived models WITHOUT required base properties (other
   * than the discriminator) do NOT get the deserialization constructor.
   * When Pet only has `kind: string` (the discriminator), Dog's public ctor
   * has zero parameters, so a deserialization ctor would duplicate it.
   */
  it("skips constructor for derived models with no required non-discriminator base properties", async () => {
    const [{ outputs }, diagnostics] = await HttpTester.compileAndDiagnose(`
      using TypeSpec.Http;

      @service
      namespace TestNamespace;

      @discriminator("kind")
      model Pet {
        kind: string;
      }

      model Dog extends Pet {
        kind: "dog";
      }

      @route("/test")
      op test(): Pet;
    `);

    expect(diagnostics).toHaveLength(0);

    const dogFileKey = Object.keys(outputs).find((k) =>
      k.includes("Dog.Serialization.cs"),
    );
    const dogContent = outputs[dogFileKey!];

    // Dog has no required params (kind is the discriminator, filtered out),
    // so its public ctor is parameterless — no deserialization ctor needed
    expect(dogContent).not.toMatch(/internal\s+Dog\s*\(\s*\)/);
  });

  /**
   * Validates that abstract base models in a discriminator hierarchy also
   * get the deserialization constructor when they have required properties.
   * Even though abstract models can't be directly instantiated, their
   * deserialization constructors are called by derived model constructors
   * via constructor chaining.
   */
  it("generates constructor for abstract base models with required properties", async () => {
    const [{ outputs }, diagnostics] = await HttpTester.compileAndDiagnose(`
      using TypeSpec.Http;

      @service
      namespace TestNamespace;

      @discriminator("kind")
      model Pet {
        kind: string;
        name: string;
      }

      model Dog extends Pet {
        kind: "dog";
      }

      @route("/test")
      op test(): Pet;
    `);

    expect(diagnostics).toHaveLength(0);

    const petFileKey = Object.keys(outputs).find((k) =>
      k.includes("Pet.Serialization.cs"),
    );
    const petContent = outputs[petFileKey!];

    // Pet has required properties (kind + name), so it needs the ctor
    expect(petContent).toMatch(/internal\s+Pet\s*\(\s*\)/);
    expect(petContent).toContain(
      '/// <summary> Initializes a new instance of <see cref="Pet"/> for deserialization. </summary>',
    );
  });
});

/**
 * Tests for the JsonModelWriteCore component.
 *
 * These tests verify that the emitter generates the `JsonModelWriteCore` method
 * in the `.Serialization.cs` partial class. This method is the core JSON
 * serialization entry point called by `IJsonModel<T>.Write`. It validates the
 * wire format, optionally calls the base class implementation for derived models,
 * and provides a children slot for property-level serialization.
 *
 * Why these tests matter:
 * - JsonModelWriteCore is the foundation for all JSON property serialization
 *   (tasks 2.2.2–2.2.14). Without this method shell, property writes have no home.
 * - Format validation prevents models from being serialized in unsupported formats
 *   (e.g., attempting XML on a JSON-only model), which would produce corrupt output.
 * - Virtual/override modifiers are critical for polymorphic serialization — derived
 *   models must override the base to add their own properties after the base call.
 * - The base.JsonModelWriteCore call ensures inherited properties are serialized
 *   before derived properties, matching the wire format contract.
 * - Auto-generated `using` directives for System, System.Text.Json, and
 *   System.ClientModel.Primitives are required for the code to compile.
 */
describe("JsonModelWriteCore", () => {
  /**
   * Validates that a root model (no base class) generates JsonModelWriteCore
   * with `protected virtual` modifier. Virtual allows derived models to override
   * the method while providing a default implementation for direct serialization.
   */
  it("generates protected virtual method for root model", async () => {
    const [{ outputs }, diagnostics] = await HttpTester.compileAndDiagnose(`
      using TypeSpec.Http;

      @service
      namespace TestNamespace;

      model Widget {
        name: string;
      }

      @route("/test")
      op test(): Widget;
    `);

    expect(diagnostics).toHaveLength(0);

    const fileKey = Object.keys(outputs).find((k) =>
      k.includes("Widget.Serialization.cs"),
    );
    const content = outputs[fileKey!];

    expect(content).toMatch(
      /protected\s+virtual\s+void\s+JsonModelWriteCore\s*\(/,
    );
  });

  /**
   * Validates that the method signature includes Utf8JsonWriter and
   * ModelReaderWriterOptions parameters, matching the IJsonModel<T>
   * serialization contract. These are the only parameters — the model
   * instance is `this`.
   */
  it("includes Utf8JsonWriter and ModelReaderWriterOptions parameters", async () => {
    const [{ outputs }, diagnostics] = await HttpTester.compileAndDiagnose(`
      using TypeSpec.Http;

      @service
      namespace TestNamespace;

      model Widget {
        name: string;
      }

      @route("/test")
      op test(): Widget;
    `);

    expect(diagnostics).toHaveLength(0);

    const fileKey = Object.keys(outputs).find((k) =>
      k.includes("Widget.Serialization.cs"),
    );
    const content = outputs[fileKey!];

    expect(content).toMatch(
      /JsonModelWriteCore\s*\(\s*Utf8JsonWriter\s+writer\s*,\s*ModelReaderWriterOptions\s+options\s*\)/,
    );
  });

  /**
   * Validates that the method starts with format validation that checks
   * whether the wire format is "J" (JSON). The format string is resolved
   * via IPersistableModel<T>.GetFormatFromOptions when options.Format is "W"
   * (wire format). This is critical — without it, a non-JSON format request
   * would silently produce malformed output.
   */
  it("includes format validation at the start of method body", async () => {
    const [{ outputs }, diagnostics] = await HttpTester.compileAndDiagnose(`
      using TypeSpec.Http;

      @service
      namespace TestNamespace;

      model Widget {
        name: string;
      }

      @route("/test")
      op test(): Widget;
    `);

    expect(diagnostics).toHaveLength(0);

    const fileKey = Object.keys(outputs).find((k) =>
      k.includes("Widget.Serialization.cs"),
    );
    const content = outputs[fileKey!];

    // Format resolution via IPersistableModel<T>.GetFormatFromOptions
    expect(content).toContain(
      "((IPersistableModel<Widget>)this).GetFormatFromOptions(options)",
    );

    // Format check and FormatException
    expect(content).toContain('if (format != "J")');
    expect(content).toContain("throw new FormatException(");
    expect(content).toContain("nameof(Widget)");
  });

  /**
   * Validates that derived models in a discriminator hierarchy use
   * `protected override` instead of `protected virtual`. Override is
   * required so the runtime dispatches to the derived model's serialization
   * when the base type's Write method is called polymorphically.
   */
  it("generates protected override method for derived model", async () => {
    const [{ outputs }, diagnostics] = await HttpTester.compileAndDiagnose(`
      using TypeSpec.Http;

      @service
      namespace TestNamespace;

      @discriminator("kind")
      model Pet {
        kind: string;
        name: string;
      }

      model Dog extends Pet {
        kind: "dog";
        breed: string;
      }

      @route("/test")
      op test(): Pet;
    `);

    expect(diagnostics).toHaveLength(0);

    const dogFileKey = Object.keys(outputs).find((k) =>
      k.includes("Dog.Serialization.cs"),
    );
    const dogContent = outputs[dogFileKey!];

    expect(dogContent).toMatch(
      /protected\s+override\s+void\s+JsonModelWriteCore\s*\(/,
    );
  });

  /**
   * Validates that derived models call `base.JsonModelWriteCore(writer, options)`
   * to serialize inherited properties before their own. Without this call,
   * base model properties would be silently dropped from the JSON output,
   * breaking the wire format contract.
   */
  it("calls base.JsonModelWriteCore for derived models", async () => {
    const [{ outputs }, diagnostics] = await HttpTester.compileAndDiagnose(`
      using TypeSpec.Http;

      @service
      namespace TestNamespace;

      @discriminator("kind")
      model Pet {
        kind: string;
        name: string;
      }

      model Dog extends Pet {
        kind: "dog";
        breed: string;
      }

      @route("/test")
      op test(): Pet;
    `);

    expect(diagnostics).toHaveLength(0);

    const dogFileKey = Object.keys(outputs).find((k) =>
      k.includes("Dog.Serialization.cs"),
    );
    const dogContent = outputs[dogFileKey!];

    expect(dogContent).toContain("base.JsonModelWriteCore(writer, options);");
  });

  /**
   * Validates that root models do NOT call base.JsonModelWriteCore.
   * Root models have no base serialization to delegate to, and calling
   * a non-existent base method would cause a C# compilation error.
   */
  it("does not call base.JsonModelWriteCore for root models", async () => {
    const [{ outputs }, diagnostics] = await HttpTester.compileAndDiagnose(`
      using TypeSpec.Http;

      @service
      namespace TestNamespace;

      model Widget {
        name: string;
      }

      @route("/test")
      op test(): Widget;
    `);

    expect(diagnostics).toHaveLength(0);

    const fileKey = Object.keys(outputs).find((k) =>
      k.includes("Widget.Serialization.cs"),
    );
    const content = outputs[fileKey!];

    expect(content).not.toContain("base.JsonModelWriteCore");
  });

  /**
   * Validates that the `using System.Text.Json;` directive is auto-generated
   * because Utf8JsonWriter is referenced from that namespace in the method
   * parameters. This using statement is critical for the code to compile.
   */
  it("includes using directive for System.Text.Json", async () => {
    const [{ outputs }, diagnostics] = await HttpTester.compileAndDiagnose(`
      using TypeSpec.Http;

      @service
      namespace TestNamespace;

      model Widget {
        name: string;
      }

      @route("/test")
      op test(): Widget;
    `);

    expect(diagnostics).toHaveLength(0);

    const fileKey = Object.keys(outputs).find((k) =>
      k.includes("Widget.Serialization.cs"),
    );
    const content = outputs[fileKey!];

    expect(content).toContain("using System.Text.Json;");
  });

  /**
   * Validates that the `using System;` directive is auto-generated
   * because FormatException is referenced from the System namespace
   * in the format validation block. Without this, the code won't compile.
   */
  it("includes using directive for System", async () => {
    const [{ outputs }, diagnostics] = await HttpTester.compileAndDiagnose(`
      using TypeSpec.Http;

      @service
      namespace TestNamespace;

      model Widget {
        name: string;
      }

      @route("/test")
      op test(): Widget;
    `);

    expect(diagnostics).toHaveLength(0);

    const fileKey = Object.keys(outputs).find((k) =>
      k.includes("Widget.Serialization.cs"),
    );
    const content = outputs[fileKey!];

    expect(content).toContain("using System;");
  });

  /**
   * Validates that the format validation references the correct model name
   * in both the IPersistableModel cast and the FormatException message.
   * Each model must reference its own type, not a generic placeholder.
   */
  it("uses correct model name in format validation for each model", async () => {
    const [{ outputs }, diagnostics] = await HttpTester.compileAndDiagnose(`
      using TypeSpec.Http;

      @service
      namespace TestNamespace;

      @discriminator("kind")
      model Pet {
        kind: string;
        name: string;
      }

      model Dog extends Pet {
        kind: "dog";
        breed: string;
      }

      @route("/test")
      op test(): Pet;
    `);

    expect(diagnostics).toHaveLength(0);

    // Pet should reference IPersistableModel<Pet>
    const petFileKey = Object.keys(outputs).find((k) =>
      k.includes("Pet.Serialization.cs"),
    );
    const petContent = outputs[petFileKey!];
    expect(petContent).toContain("(IPersistableModel<Pet>)this");
    expect(petContent).toContain("nameof(Pet)");

    // Dog should reference IPersistableModel<Dog>
    const dogFileKey = Object.keys(outputs).find((k) =>
      k.includes("Dog.Serialization.cs"),
    );
    const dogContent = outputs[dogFileKey!];
    expect(dogContent).toContain("(IPersistableModel<Dog>)this");
    expect(dogContent).toContain("nameof(Dog)");
  });

  /**
   * Validates that abstract base models (discriminated union roots) also
   * get the JsonModelWriteCore method with `protected virtual` modifier.
   * Even though abstract models can't be directly instantiated, their
   * JsonModelWriteCore is called by derived models via base.JsonModelWriteCore.
   */
  it("generates virtual method for abstract base models", async () => {
    const [{ outputs }, diagnostics] = await HttpTester.compileAndDiagnose(`
      using TypeSpec.Http;

      @service
      namespace TestNamespace;

      @discriminator("kind")
      model Pet {
        kind: string;
        name: string;
      }

      model Dog extends Pet {
        kind: "dog";
      }

      @route("/test")
      op test(): Pet;
    `);

    expect(diagnostics).toHaveLength(0);

    const petFileKey = Object.keys(outputs).find((k) =>
      k.includes("Pet.Serialization.cs"),
    );
    const petContent = outputs[petFileKey!];

    // Abstract base model should have protected virtual (not override)
    expect(petContent).toMatch(
      /protected\s+virtual\s+void\s+JsonModelWriteCore/,
    );
    expect(petContent).not.toContain("base.JsonModelWriteCore");
  });

  /**
   * Validates multi-level inheritance: grandchild models also use override
   * and call base. For a hierarchy Animal → Pet → Dog, Dog must override
   * JsonModelWriteCore and call base to chain through Pet → Animal.
   */
  it("handles multi-level inheritance correctly", async () => {
    const [{ outputs }, diagnostics] = await HttpTester.compileAndDiagnose(`
      using TypeSpec.Http;

      @service
      namespace TestNamespace;

      @discriminator("kind")
      model Animal {
        kind: string;
        name: string;
      }

      model Pet extends Animal {
        kind: "pet";
        trained: boolean;
      }

      @route("/test")
      op test(): Animal;
    `);

    expect(diagnostics).toHaveLength(0);

    // Animal (root) should be virtual
    const animalKey = Object.keys(outputs).find((k) =>
      k.includes("Animal.Serialization.cs"),
    );
    const animalContent = outputs[animalKey!];
    expect(animalContent).toMatch(
      /protected\s+virtual\s+void\s+JsonModelWriteCore/,
    );

    // Pet (derived) should be override with base call
    const petKey = Object.keys(outputs).find((k) =>
      k.includes("Pet.Serialization.cs"),
    );
    const petContent = outputs[petKey!];
    expect(petContent).toMatch(
      /protected\s+override\s+void\s+JsonModelWriteCore/,
    );
    expect(petContent).toContain("base.JsonModelWriteCore(writer, options);");
  });
});

/**
 * Tests for primitive property serialization in JsonModelWriteCore.
 *
 * These tests verify that the emitter generates `writer.WritePropertyName("serializedName"u8)`
 * and `writer.WriteXxxValue(PropertyName)` statements for each primitive property type
 * inside the `JsonModelWriteCore` method body.
 *
 * Why these tests matter:
 * - Property serialization is the core output of the JSON write path — without it,
 *   models produce empty JSON objects, breaking all API communication.
 * - UTF-8 byte literals (`"name"u8`) are a performance-critical pattern that the
 *   System.ClientModel framework expects for efficient JSON writing.
 * - The correct writer method must be selected for each type (WriteStringValue,
 *   WriteNumberValue, WriteBooleanValue) or the output will be malformed JSON.
 * - Derived models must NOT serialize base discriminator overrides — those are
 *   handled by the base class via `base.JsonModelWriteCore`.
 */
describe("PropertySerialization", () => {
  /**
   * Validates that a string property generates `writer.WritePropertyName("name"u8)`
   * followed by `writer.WriteStringValue(Name)`. This is the most common
   * serialization pattern — the UTF-8 byte literal is required for performance.
   */
  it("serializes string property with WriteStringValue", async () => {
    const [{ outputs }, diagnostics] = await HttpTester.compileAndDiagnose(`
      using TypeSpec.Http;

      @service
      namespace TestNamespace;

      model Widget {
        name: string;
      }

      @route("/test")
      op test(): Widget;
    `);

    expect(diagnostics).toHaveLength(0);

    const fileKey = Object.keys(outputs).find((k) =>
      k.includes("Widget.Serialization.cs"),
    );
    const content = outputs[fileKey!];

    expect(content).toContain('writer.WritePropertyName("name"u8);');
    expect(content).toContain("writer.WriteStringValue(Name);");
  });

  /**
   * Validates that an int32 property generates `writer.WriteNumberValue(Count)`.
   * All integer and floating-point types map to WriteNumberValue in the
   * Utf8JsonWriter API.
   */
  it("serializes int32 property with WriteNumberValue", async () => {
    const [{ outputs }, diagnostics] = await HttpTester.compileAndDiagnose(`
      using TypeSpec.Http;

      @service
      namespace TestNamespace;

      model Widget {
        count: int32;
      }

      @route("/test")
      op test(): Widget;
    `);

    expect(diagnostics).toHaveLength(0);

    const fileKey = Object.keys(outputs).find((k) =>
      k.includes("Widget.Serialization.cs"),
    );
    const content = outputs[fileKey!];

    expect(content).toContain('writer.WritePropertyName("count"u8);');
    expect(content).toContain("writer.WriteNumberValue(Count);");
  });

  /**
   * Validates that a boolean property generates `writer.WriteBooleanValue(IsActive)`.
   * Boolean is the third primitive type alongside string and number.
   */
  it("serializes boolean property with WriteBooleanValue", async () => {
    const [{ outputs }, diagnostics] = await HttpTester.compileAndDiagnose(`
      using TypeSpec.Http;

      @service
      namespace TestNamespace;

      model Widget {
        isActive: boolean;
      }

      @route("/test")
      op test(): Widget;
    `);

    expect(diagnostics).toHaveLength(0);

    const fileKey = Object.keys(outputs).find((k) =>
      k.includes("Widget.Serialization.cs"),
    );
    const content = outputs[fileKey!];

    expect(content).toContain('writer.WritePropertyName("isActive"u8);');
    expect(content).toContain("writer.WriteBooleanValue(IsActive);");
  });

  /**
   * Validates that a float64 property generates `writer.WriteNumberValue(Score)`.
   * Floating-point types also use WriteNumberValue, same as integers.
   */
  it("serializes float64 property with WriteNumberValue", async () => {
    const [{ outputs }, diagnostics] = await HttpTester.compileAndDiagnose(`
      using TypeSpec.Http;

      @service
      namespace TestNamespace;

      model Widget {
        score: float64;
      }

      @route("/test")
      op test(): Widget;
    `);

    expect(diagnostics).toHaveLength(0);

    const fileKey = Object.keys(outputs).find((k) =>
      k.includes("Widget.Serialization.cs"),
    );
    const content = outputs[fileKey!];

    expect(content).toContain('writer.WritePropertyName("score"u8);');
    expect(content).toContain("writer.WriteNumberValue(Score);");
  });

  /**
   * Validates that multiple properties are serialized in order. Each property
   * gets its own WritePropertyName + WriteXxxValue pair. The output should
   * contain all property serialization statements.
   */
  it("serializes multiple primitive properties in order", async () => {
    const [{ outputs }, diagnostics] = await HttpTester.compileAndDiagnose(`
      using TypeSpec.Http;

      @service
      namespace TestNamespace;

      model Widget {
        name: string;
        count: int32;
        isActive: boolean;
      }

      @route("/test")
      op test(): Widget;
    `);

    expect(diagnostics).toHaveLength(0);

    const fileKey = Object.keys(outputs).find((k) =>
      k.includes("Widget.Serialization.cs"),
    );
    const content = outputs[fileKey!];

    // All three properties should be serialized
    expect(content).toContain('writer.WritePropertyName("name"u8);');
    expect(content).toContain("writer.WriteStringValue(Name);");
    expect(content).toContain('writer.WritePropertyName("count"u8);');
    expect(content).toContain("writer.WriteNumberValue(Count);");
    expect(content).toContain('writer.WritePropertyName("isActive"u8);');
    expect(content).toContain("writer.WriteBooleanValue(IsActive);");

    // Verify ordering: name before count before isActive
    const nameIdx = content.indexOf('WritePropertyName("name"u8)');
    const countIdx = content.indexOf('WritePropertyName("count"u8)');
    const activeIdx = content.indexOf('WritePropertyName("isActive"u8)');
    expect(nameIdx).toBeLessThan(countIdx);
    expect(countIdx).toBeLessThan(activeIdx);
  });

  /**
   * Validates that property names use UTF-8 byte literals (`"name"u8`).
   * The u8 suffix creates a `ReadOnlySpan<byte>` which avoids UTF-16 to
   * UTF-8 transcoding at runtime — a critical performance optimization
   * required by the System.ClientModel framework.
   */
  it("uses u8 suffix for UTF-8 byte literal property names", async () => {
    const [{ outputs }, diagnostics] = await HttpTester.compileAndDiagnose(`
      using TypeSpec.Http;

      @service
      namespace TestNamespace;

      model Widget {
        myProperty: string;
      }

      @route("/test")
      op test(): Widget;
    `);

    expect(diagnostics).toHaveLength(0);

    const fileKey = Object.keys(outputs).find((k) =>
      k.includes("Widget.Serialization.cs"),
    );
    const content = outputs[fileKey!];

    // Must use u8 suffix for the property name
    expect(content).toMatch(/WritePropertyName\("myProperty"u8\)/);
  });

  /**
   * Validates that the serialized name (JSON wire name) is used for
   * WritePropertyName, not the C# property name. TypeSpec property names
   * use camelCase which becomes the serialized name, while C# properties
   * are PascalCase.
   */
  it("uses serializedName for WritePropertyName and PascalCase for value", async () => {
    const [{ outputs }, diagnostics] = await HttpTester.compileAndDiagnose(`
      using TypeSpec.Http;

      @service
      namespace TestNamespace;

      model Widget {
        firstName: string;
      }

      @route("/test")
      op test(): Widget;
    `);

    expect(diagnostics).toHaveLength(0);

    const fileKey = Object.keys(outputs).find((k) =>
      k.includes("Widget.Serialization.cs"),
    );
    const content = outputs[fileKey!];

    // serializedName (camelCase) for the wire name
    expect(content).toContain('writer.WritePropertyName("firstName"u8);');
    // PascalCase for the C# property accessor
    expect(content).toContain("writer.WriteStringValue(FirstName);");
  });

  /**
   * Validates that derived models only serialize their own properties, not
   * inherited ones. The base class properties are serialized via the
   * `base.JsonModelWriteCore(writer, options)` call.
   */
  it("derived model serializes only own properties", async () => {
    const [{ outputs }, diagnostics] = await HttpTester.compileAndDiagnose(`
      using TypeSpec.Http;

      @service
      namespace TestNamespace;

      @discriminator("kind")
      model Pet {
        kind: string;
        name: string;
      }

      model Dog extends Pet {
        kind: "dog";
        breed: string;
      }

      @route("/test")
      op test(): Pet;
    `);

    expect(diagnostics).toHaveLength(0);

    // Dog should serialize its own property (breed) but NOT the base discriminator override (kind: "dog")
    const dogFileKey = Object.keys(outputs).find((k) =>
      k.includes("Dog.Serialization.cs"),
    );
    const dogContent = outputs[dogFileKey!];

    expect(dogContent).toContain('writer.WritePropertyName("breed"u8);');
    expect(dogContent).toContain("writer.WriteStringValue(Breed);");
    // Should NOT contain kind property write — it's handled by base.JsonModelWriteCore
    expect(dogContent).not.toContain('WritePropertyName("kind"u8)');

    // Pet (base) should serialize both kind and name
    const petFileKey = Object.keys(outputs).find((k) =>
      k.includes("Pet.Serialization.cs"),
    );
    const petContent = outputs[petFileKey!];

    expect(petContent).toContain('writer.WritePropertyName("kind"u8);');
    expect(petContent).toContain("writer.WriteStringValue(Kind);");
    expect(petContent).toContain('writer.WritePropertyName("name"u8);');
    expect(petContent).toContain("writer.WriteStringValue(Name);");
  });

  /**
   * Validates that int64 properties use WriteNumberValue. This ensures
   * all integer variants (not just int32) are correctly handled.
   */
  it("serializes int64 property with WriteNumberValue", async () => {
    const [{ outputs }, diagnostics] = await HttpTester.compileAndDiagnose(`
      using TypeSpec.Http;

      @service
      namespace TestNamespace;

      model Widget {
        bigId: int64;
      }

      @route("/test")
      op test(): Widget;
    `);

    expect(diagnostics).toHaveLength(0);

    const fileKey = Object.keys(outputs).find((k) =>
      k.includes("Widget.Serialization.cs"),
    );
    const content = outputs[fileKey!];

    expect(content).toContain('writer.WritePropertyName("bigId"u8);');
    expect(content).toContain("writer.WriteNumberValue(BigId);");
  });

  /**
   * Validates that the property serialization is placed inside the
   * JsonModelWriteCore method body (after format validation and optional
   * base call), not outside it.
   */
  it("property writes are inside JsonModelWriteCore method body", async () => {
    const [{ outputs }, diagnostics] = await HttpTester.compileAndDiagnose(`
      using TypeSpec.Http;

      @service
      namespace TestNamespace;

      model Widget {
        name: string;
      }

      @route("/test")
      op test(): Widget;
    `);

    expect(diagnostics).toHaveLength(0);

    const fileKey = Object.keys(outputs).find((k) =>
      k.includes("Widget.Serialization.cs"),
    );
    const content = outputs[fileKey!];

    // The format check should come BEFORE the property write
    const formatCheckIdx = content.indexOf('if (format != "J")');
    const propertyWriteIdx = content.indexOf('WritePropertyName("name"u8)');
    expect(formatCheckIdx).toBeLessThan(propertyWriteIdx);
  });

  /**
   * Validates that a utcDateTime property with default encoding (RFC3339)
   * generates `writer.WriteStringValue(CreatedAt, "O")`. The "O" format specifier
   * produces ISO 8601 round-trip format, which is the standard JSON date encoding.
   * The format argument is passed to the `ModelSerializationExtensions.WriteStringValue`
   * extension method, not the native `Utf8JsonWriter.WriteStringValue`.
   */
  it("serializes utcDateTime property with RFC3339 encoding", async () => {
    const [{ outputs }, diagnostics] = await HttpTester.compileAndDiagnose(`
      using TypeSpec.Http;

      @service
      namespace TestNamespace;

      model Widget {
        createdAt: utcDateTime;
      }

      @route("/test")
      op test(): Widget;
    `);

    expect(diagnostics).toHaveLength(0);

    const fileKey = Object.keys(outputs).find((k) =>
      k.includes("Widget.Serialization.cs"),
    );
    const content = outputs[fileKey!];

    expect(content).toContain('writer.WritePropertyName("createdAt"u8);');
    expect(content).toContain('writer.WriteStringValue(CreatedAt, "O");');
  });

  /**
   * Validates that a utcDateTime property with RFC7231 encoding generates
   * `writer.WriteStringValue(LastModified, "R")`. The "R" format specifier
   * produces RFC 1123 format (e.g., "Wed, 12 Oct 2022 07:20:50 GMT"), which
   * is used for HTTP header dates. Without the correct format, API servers
   * would reject the date value.
   */
  it("serializes utcDateTime property with RFC7231 encoding", async () => {
    const [{ outputs }, diagnostics] = await HttpTester.compileAndDiagnose(`
      using TypeSpec.Http;

      @service
      namespace TestNamespace;

      model Widget {
        @encode(DateTimeKnownEncoding.rfc7231)
        lastModified: utcDateTime;
      }

      @route("/test")
      op test(): Widget;
    `);

    expect(diagnostics).toHaveLength(0);

    const fileKey = Object.keys(outputs).find((k) =>
      k.includes("Widget.Serialization.cs"),
    );
    const content = outputs[fileKey!];

    expect(content).toContain('writer.WritePropertyName("lastModified"u8);');
    expect(content).toContain('writer.WriteStringValue(LastModified, "R");');
  });

  /**
   * Validates that a utcDateTime property with Unix timestamp encoding generates
   * `writer.WriteNumberValue(Timestamp, "U")`. Unlike RFC3339/RFC7231, Unix
   * timestamps are numbers (seconds since epoch), so they use WriteNumberValue
   * instead of WriteStringValue. The "U" format is handled by the
   * `ModelSerializationExtensions.WriteNumberValue` extension method which calls
   * `DateTimeOffset.ToUnixTimeSeconds()`.
   */
  it("serializes utcDateTime property with unixTimestamp encoding", async () => {
    const [{ outputs }, diagnostics] = await HttpTester.compileAndDiagnose(`
      using TypeSpec.Http;

      @service
      namespace TestNamespace;

      model Widget {
        @encode(DateTimeKnownEncoding.unixTimestamp, int64)
        timestamp: utcDateTime;
      }

      @route("/test")
      op test(): Widget;
    `);

    expect(diagnostics).toHaveLength(0);

    const fileKey = Object.keys(outputs).find((k) =>
      k.includes("Widget.Serialization.cs"),
    );
    const content = outputs[fileKey!];

    expect(content).toContain('writer.WritePropertyName("timestamp"u8);');
    expect(content).toContain('writer.WriteNumberValue(Timestamp, "U");');
  });

  /**
   * Validates that a plainDate property generates `writer.WriteStringValue(BirthDate, "D")`.
   * The "D" format specifier produces ISO 8601 date-only format (e.g., "2022-10-12").
   * plainDate maps to DateTimeOffset in C# but needs explicit formatting to exclude
   * the time portion.
   */
  it("serializes plainDate property with D format", async () => {
    const [{ outputs }, diagnostics] = await HttpTester.compileAndDiagnose(`
      using TypeSpec.Http;

      @service
      namespace TestNamespace;

      model Widget {
        birthDate: plainDate;
      }

      @route("/test")
      op test(): Widget;
    `);

    expect(diagnostics).toHaveLength(0);

    const fileKey = Object.keys(outputs).find((k) =>
      k.includes("Widget.Serialization.cs"),
    );
    const content = outputs[fileKey!];

    expect(content).toContain('writer.WritePropertyName("birthDate"u8);');
    expect(content).toContain('writer.WriteStringValue(BirthDate, "D");');
  });

  /**
   * Validates that a plainTime property generates `writer.WriteStringValue(StartTime, "T")`.
   * The "T" format specifier produces ISO 8601 time-only format (e.g., "13:45:30").
   * plainTime maps to TimeSpan in C# and requires the "T" format to avoid writing
   * a duration-like string.
   */
  it("serializes plainTime property with T format", async () => {
    const [{ outputs }, diagnostics] = await HttpTester.compileAndDiagnose(`
      using TypeSpec.Http;

      @service
      namespace TestNamespace;

      model Widget {
        startTime: plainTime;
      }

      @route("/test")
      op test(): Widget;
    `);

    expect(diagnostics).toHaveLength(0);

    const fileKey = Object.keys(outputs).find((k) =>
      k.includes("Widget.Serialization.cs"),
    );
    const content = outputs[fileKey!];

    expect(content).toContain('writer.WritePropertyName("startTime"u8);');
    expect(content).toContain('writer.WriteStringValue(StartTime, "T");');
  });

  /**
   * Validates that a duration property with default encoding (ISO8601) generates
   * `writer.WriteStringValue(Timeout, "P")`. The "P" format specifier triggers
   * `TypeFormatters.ToString(value, "P")` which uses `XmlConvert.ToString()` to
   * produce ISO 8601 duration strings like "P1DT2H3M4S". Without the "P" format,
   * TimeSpan.ToString() would produce a different format (e.g., "1.02:03:04").
   */
  it("serializes duration property with ISO8601 encoding (default)", async () => {
    const [{ outputs }, diagnostics] = await HttpTester.compileAndDiagnose(`
      using TypeSpec.Http;

      @service
      namespace TestNamespace;

      model Widget {
        timeout: duration;
      }

      @route("/test")
      op test(): Widget;
    `);

    expect(diagnostics).toHaveLength(0);

    const fileKey = Object.keys(outputs).find((k) =>
      k.includes("Widget.Serialization.cs"),
    );
    const content = outputs[fileKey!];

    expect(content).toContain('writer.WritePropertyName("timeout"u8);');
    expect(content).toContain('writer.WriteStringValue(Timeout, "P");');
  });

  /**
   * Validates that a duration property encoded as seconds with a float wire type
   * generates `writer.WriteNumberValue(Delay.TotalSeconds)`. Float/double wire
   * types pass the raw TotalSeconds value without truncation, preserving fractional
   * seconds. This is the standard numeric duration encoding for REST APIs.
   */
  it("serializes duration property with seconds encoding (float)", async () => {
    const [{ outputs }, diagnostics] = await HttpTester.compileAndDiagnose(`
      using TypeSpec.Http;

      @service
      namespace TestNamespace;

      model Widget {
        @encode(DurationKnownEncoding.seconds, float64)
        delay: duration;
      }

      @route("/test")
      op test(): Widget;
    `);

    expect(diagnostics).toHaveLength(0);

    const fileKey = Object.keys(outputs).find((k) =>
      k.includes("Widget.Serialization.cs"),
    );
    const content = outputs[fileKey!];

    expect(content).toContain('writer.WritePropertyName("delay"u8);');
    expect(content).toContain("writer.WriteNumberValue(Delay.TotalSeconds);");
  });

  /**
   * Validates that a duration property encoded as seconds with an integer wire type
   * generates `writer.WriteNumberValue(Convert.ToInt32(Ttl.TotalSeconds))`. Integer
   * wire types require Convert.ToInt32() to truncate fractional seconds — without it,
   * the JSON output could contain unexpected decimal values for a field that should
   * be an integer.
   */
  it("serializes duration property with seconds encoding (integer)", async () => {
    const [{ outputs }, diagnostics] = await HttpTester.compileAndDiagnose(`
      using TypeSpec.Http;

      @service
      namespace TestNamespace;

      model Widget {
        @encode(DurationKnownEncoding.seconds, int32)
        ttl: duration;
      }

      @route("/test")
      op test(): Widget;
    `);

    expect(diagnostics).toHaveLength(0);

    const fileKey = Object.keys(outputs).find((k) =>
      k.includes("Widget.Serialization.cs"),
    );
    const content = outputs[fileKey!];

    expect(content).toContain('writer.WritePropertyName("ttl"u8);');
    expect(content).toContain(
      "writer.WriteNumberValue(Convert.ToInt32(Ttl.TotalSeconds));",
    );
  });

  /**
   * Validates that a duration property encoded as milliseconds with a float wire type
   * generates `writer.WriteNumberValue(Latency.TotalMilliseconds)`. This encoding is
   * used by APIs that measure durations in milliseconds with fractional precision
   * (e.g., performance metrics).
   */
  it("serializes duration property with milliseconds encoding (float)", async () => {
    const [{ outputs }, diagnostics] = await HttpTester.compileAndDiagnose(`
      using TypeSpec.Http;

      @service
      namespace TestNamespace;

      model Widget {
        @encode(DurationKnownEncoding.milliseconds, float64)
        latency: duration;
      }

      @route("/test")
      op test(): Widget;
    `);

    expect(diagnostics).toHaveLength(0);

    const fileKey = Object.keys(outputs).find((k) =>
      k.includes("Widget.Serialization.cs"),
    );
    const content = outputs[fileKey!];

    expect(content).toContain('writer.WritePropertyName("latency"u8);');
    expect(content).toContain(
      "writer.WriteNumberValue(Latency.TotalMilliseconds);",
    );
  });

  /**
   * Validates that a duration property encoded as milliseconds with an integer wire type
   * generates `writer.WriteNumberValue(Convert.ToInt32(PollInterval.TotalMilliseconds))`.
   * Integer millisecond encoding is used when APIs require whole-number millisecond values
   * (e.g., retry-after headers, polling intervals).
   */
  it("serializes duration property with milliseconds encoding (integer)", async () => {
    const [{ outputs }, diagnostics] = await HttpTester.compileAndDiagnose(`
      using TypeSpec.Http;

      @service
      namespace TestNamespace;

      model Widget {
        @encode(DurationKnownEncoding.milliseconds, int32)
        pollInterval: duration;
      }

      @route("/test")
      op test(): Widget;
    `);

    expect(diagnostics).toHaveLength(0);

    const fileKey = Object.keys(outputs).find((k) =>
      k.includes("Widget.Serialization.cs"),
    );
    const content = outputs[fileKey!];

    expect(content).toContain('writer.WritePropertyName("pollInterval"u8);');
    expect(content).toContain(
      "writer.WriteNumberValue(Convert.ToInt32(PollInterval.TotalMilliseconds));",
    );
  });
});

/**
 * Tests for optional property serialization guards.
 *
 * When a property is optional, it may not have been set by the user. The
 * generated serialization code wraps the property write in an `Optional.IsDefined`
 * (for scalar types) or `Optional.IsCollectionDefined` (for collection types) guard.
 * This prevents serializing unset values and matches the legacy emitter's behavior
 * from `CreateConditionalSerializationStatement` in MrwSerializationTypeDefinition.cs.
 *
 * Required non-nullable properties serialize directly without guards.
 */
describe("OptionalPropertyGuards", () => {
  /**
   * Validates that an optional string property is wrapped in `Optional.IsDefined`.
   * This is the most common guard pattern — string is a reference type and when
   * optional, the user may not have set it.
   */
  it("wraps optional string property in Optional.IsDefined guard", async () => {
    const [{ outputs }, diagnostics] = await HttpTester.compileAndDiagnose(`
      using TypeSpec.Http;

      @service
      namespace TestNamespace;

      model Widget {
        name: string;
        description?: string;
      }

      @route("/test")
      op test(): Widget;
    `);

    expect(diagnostics).toHaveLength(0);

    const fileKey = Object.keys(outputs).find((k) =>
      k.includes("Widget.Serialization.cs"),
    );
    const content = outputs[fileKey!];

    // Required property 'name' serializes directly without guard
    expect(content).toContain('writer.WritePropertyName("name"u8);');
    expect(content).toContain("writer.WriteStringValue(Name);");
    expect(content).not.toContain("Optional.IsDefined(Name)");

    // Optional property 'description' wrapped in IsDefined guard
    expect(content).toContain("if (Optional.IsDefined(Description))");
    expect(content).toContain('writer.WritePropertyName("description"u8);');
    expect(content).toContain("writer.WriteStringValue(Description);");
  });

  /**
   * Validates that an optional int32 property is wrapped in `Optional.IsDefined`.
   * Even though int is a value type, when optional it becomes `int?` (Nullable<int>)
   * and needs a guard to detect whether the user set it.
   */
  it("wraps optional int32 property in Optional.IsDefined guard", async () => {
    const [{ outputs }, diagnostics] = await HttpTester.compileAndDiagnose(`
      using TypeSpec.Http;

      @service
      namespace TestNamespace;

      model Widget {
        count?: int32;
      }

      @route("/test")
      op test(): Widget;
    `);

    expect(diagnostics).toHaveLength(0);

    const fileKey = Object.keys(outputs).find((k) =>
      k.includes("Widget.Serialization.cs"),
    );
    const content = outputs[fileKey!];

    expect(content).toContain("if (Optional.IsDefined(Count))");
    expect(content).toContain('writer.WritePropertyName("count"u8);');
    expect(content).toContain("writer.WriteNumberValue(Count);");
  });

  /**
   * Validates that a required non-nullable property serializes directly
   * without any `Optional.IsDefined` guard. Required properties are always
   * present and don't need conditional serialization.
   */
  it("does not wrap required non-nullable property in guard", async () => {
    const [{ outputs }, diagnostics] = await HttpTester.compileAndDiagnose(`
      using TypeSpec.Http;

      @service
      namespace TestNamespace;

      model Widget {
        name: string;
        count: int32;
      }

      @route("/test")
      op test(): Widget;
    `);

    expect(diagnostics).toHaveLength(0);

    const fileKey = Object.keys(outputs).find((k) =>
      k.includes("Widget.Serialization.cs"),
    );
    const content = outputs[fileKey!];

    // Neither required property should have a guard
    expect(content).not.toContain("Optional.IsDefined");
    expect(content).not.toContain("Optional.IsCollectionDefined");

    // Both should serialize directly
    expect(content).toContain('writer.WritePropertyName("name"u8);');
    expect(content).toContain("writer.WriteStringValue(Name);");
    expect(content).toContain('writer.WritePropertyName("count"u8);');
    expect(content).toContain("writer.WriteNumberValue(Count);");
  });

  /**
   * Validates that the write statements inside an Optional guard are
   * properly indented (8 spaces inside the if block vs 4 spaces for
   * direct writes). The guard block should follow the C# brace style:
   * ```csharp
   *     if (Optional.IsDefined(Prop))
   *     {
   *         writer.WritePropertyName("prop"u8);
   *         writer.WriteStringValue(Prop);
   *     }
   * ```
   */
  it("indents write statements inside Optional guard block", async () => {
    const [{ outputs }, diagnostics] = await HttpTester.compileAndDiagnose(`
      using TypeSpec.Http;

      @service
      namespace TestNamespace;

      model Widget {
        description?: string;
      }

      @route("/test")
      op test(): Widget;
    `);

    expect(diagnostics).toHaveLength(0);

    const fileKey = Object.keys(outputs).find((k) =>
      k.includes("Widget.Serialization.cs"),
    );
    const content = outputs[fileKey!];

    // Check the full guarded block structure with correct indentation
    expect(content).toContain("    if (Optional.IsDefined(Description))");
    expect(content).toContain("    {");
    expect(content).toContain(
      '        writer.WritePropertyName("description"u8);',
    );
    expect(content).toContain("        writer.WriteStringValue(Description);");
    expect(content).toContain("    }");
  });

  /**
   * Validates that an optional boolean property gets the IsDefined guard.
   * Covers the boolean primitive type to ensure all primitive types
   * consistently get guards when optional.
   */
  it("wraps optional boolean property in Optional.IsDefined guard", async () => {
    const [{ outputs }, diagnostics] = await HttpTester.compileAndDiagnose(`
      using TypeSpec.Http;

      @service
      namespace TestNamespace;

      model Widget {
        isActive?: boolean;
      }

      @route("/test")
      op test(): Widget;
    `);

    expect(diagnostics).toHaveLength(0);

    const fileKey = Object.keys(outputs).find((k) =>
      k.includes("Widget.Serialization.cs"),
    );
    const content = outputs[fileKey!];

    expect(content).toContain("if (Optional.IsDefined(IsActive))");
    expect(content).toContain('writer.WritePropertyName("isActive"u8);');
    expect(content).toContain("writer.WriteBooleanValue(IsActive);");
  });

  /**
   * Validates that models with a mix of required and optional properties
   * correctly apply guards only to optional ones. Required properties
   * should serialize directly while optional properties get guards.
   */
  it("applies guards only to optional properties in mixed model", async () => {
    const [{ outputs }, diagnostics] = await HttpTester.compileAndDiagnose(`
      using TypeSpec.Http;

      @service
      namespace TestNamespace;

      model Widget {
        name: string;
        description?: string;
        count: int32;
        weight?: float64;
      }

      @route("/test")
      op test(): Widget;
    `);

    expect(diagnostics).toHaveLength(0);

    const fileKey = Object.keys(outputs).find((k) =>
      k.includes("Widget.Serialization.cs"),
    );
    const content = outputs[fileKey!];

    // Required properties: no guard
    expect(content).not.toContain("Optional.IsDefined(Name)");
    expect(content).not.toContain("Optional.IsDefined(Count)");

    // Optional properties: have guard
    expect(content).toContain("Optional.IsDefined(Description)");
    expect(content).toContain("Optional.IsDefined(Weight)");
  });

  /**
   * Validates that an optional utcDateTime property with RFC3339 encoding
   * gets both the IsDefined guard and the correct format specifier inside.
   * Ensures guards compose correctly with encoding-aware serialization.
   */
  it("wraps optional utcDateTime property in guard with format specifier", async () => {
    const [{ outputs }, diagnostics] = await HttpTester.compileAndDiagnose(`
      using TypeSpec.Http;

      @service
      namespace TestNamespace;

      model Widget {
        createdAt?: utcDateTime;
      }

      @route("/test")
      op test(): Widget;
    `);

    expect(diagnostics).toHaveLength(0);

    const fileKey = Object.keys(outputs).find((k) =>
      k.includes("Widget.Serialization.cs"),
    );
    const content = outputs[fileKey!];

    expect(content).toContain("if (Optional.IsDefined(CreatedAt))");
    expect(content).toContain('writer.WritePropertyName("createdAt"u8);');
    expect(content).toContain('writer.WriteStringValue(CreatedAt, "O");');
  });
});

/**
 * Tests for the required-nullable write pattern (task 2.2.12).
 *
 * When a property is required AND explicitly nullable (e.g., `prop: string | null`),
 * the serialization code generates an if/else pattern:
 * - If the value is defined: write the property name and value
 * - Else: write null via `writer.WriteNull("name"u8)`
 *
 * This differs from:
 * - Required non-nullable: no guard at all (always writes value)
 * - Optional: only an if block (skips serialization when unset, no else)
 *
 * For nullable value types (int?, bool?, DateTimeOffset?), the value accessor
 * uses `.Value` inside the if block to unwrap the Nullable<T> struct.
 * Reference types (string?) don't need `.Value`.
 */
describe("RequiredNullableWritePattern", () => {
  /**
   * Validates that a required nullable string property gets the if/else pattern
   * with WriteNull in the else branch. String is a reference type so no `.Value`
   * is needed — the property accessor is used directly.
   */
  it("generates if/else with WriteNull for required nullable string", async () => {
    const [{ outputs }, diagnostics] = await HttpTester.compileAndDiagnose(`
      using TypeSpec.Http;

      @service
      namespace TestNamespace;

      model Widget {
        name: string | null;
      }

      @route("/test")
      op test(): Widget;
    `);

    expect(diagnostics).toHaveLength(0);

    const fileKey = Object.keys(outputs).find((k) =>
      k.includes("Widget.Serialization.cs"),
    );
    const content = outputs[fileKey!];

    // Required nullable string gets if/else guard with IsDefined
    expect(content).toContain("if (Optional.IsDefined(Name))");
    expect(content).toContain('writer.WritePropertyName("name"u8);');
    // String is a reference type — no .Value needed
    expect(content).toContain("writer.WriteStringValue(Name);");
    // Else branch writes null
    expect(content).toContain('writer.WriteNull("name"u8);');
  });

  /**
   * Validates that a required nullable int32 property gets the if/else pattern
   * with `.Value` to unwrap the Nullable<int>. Int is a C# value type, so
   * `int?` is actually `Nullable<int>` and requires `.Value` to access the
   * underlying value when we know it's defined.
   */
  it("generates if/else with .Value for required nullable int32", async () => {
    const [{ outputs }, diagnostics] = await HttpTester.compileAndDiagnose(`
      using TypeSpec.Http;

      @service
      namespace TestNamespace;

      model Widget {
        count: int32 | null;
      }

      @route("/test")
      op test(): Widget;
    `);

    expect(diagnostics).toHaveLength(0);

    const fileKey = Object.keys(outputs).find((k) =>
      k.includes("Widget.Serialization.cs"),
    );
    const content = outputs[fileKey!];

    // Required nullable int32 gets if/else guard
    expect(content).toContain("if (Optional.IsDefined(Count))");
    expect(content).toContain('writer.WritePropertyName("count"u8);');
    // Int is a value type — .Value needed to unwrap Nullable<int>
    expect(content).toContain("writer.WriteNumberValue(Count.Value);");
    // Else branch writes null
    expect(content).toContain('writer.WriteNull("count"u8);');
  });

  /**
   * Validates the required nullable boolean pattern. Boolean is a value type,
   * so `bool?` is `Nullable<bool>` and needs `.Value`.
   */
  it("generates if/else with .Value for required nullable boolean", async () => {
    const [{ outputs }, diagnostics] = await HttpTester.compileAndDiagnose(`
      using TypeSpec.Http;

      @service
      namespace TestNamespace;

      model Widget {
        isActive: boolean | null;
      }

      @route("/test")
      op test(): Widget;
    `);

    expect(diagnostics).toHaveLength(0);

    const fileKey = Object.keys(outputs).find((k) =>
      k.includes("Widget.Serialization.cs"),
    );
    const content = outputs[fileKey!];

    expect(content).toContain("if (Optional.IsDefined(IsActive))");
    expect(content).toContain('writer.WritePropertyName("isActive"u8);');
    expect(content).toContain("writer.WriteBooleanValue(IsActive.Value);");
    expect(content).toContain('writer.WriteNull("isActive"u8);');
  });

  /**
   * Validates the required nullable utcDateTime pattern. DateTimeOffset is a
   * value type, so `DateTimeOffset?` needs `.Value`. The format specifier "O"
   * (RFC3339) should appear after the `.Value` accessor.
   */
  it("generates if/else with .Value and format for required nullable utcDateTime", async () => {
    const [{ outputs }, diagnostics] = await HttpTester.compileAndDiagnose(`
      using TypeSpec.Http;

      @service
      namespace TestNamespace;

      model Widget {
        createdAt: utcDateTime | null;
      }

      @route("/test")
      op test(): Widget;
    `);

    expect(diagnostics).toHaveLength(0);

    const fileKey = Object.keys(outputs).find((k) =>
      k.includes("Widget.Serialization.cs"),
    );
    const content = outputs[fileKey!];

    expect(content).toContain("if (Optional.IsDefined(CreatedAt))");
    expect(content).toContain('writer.WritePropertyName("createdAt"u8);');
    // DateTimeOffset is a value type — .Value + format specifier
    expect(content).toContain('writer.WriteStringValue(CreatedAt.Value, "O");');
    expect(content).toContain('writer.WriteNull("createdAt"u8);');
  });

  /**
   * Validates correct indentation of the full if/else block structure.
   * The else branch should follow the same indentation as the if block.
   * ```csharp
   *     if (Optional.IsDefined(Count))
   *     {
   *         writer.WritePropertyName("count"u8);
   *         writer.WriteNumberValue(Count.Value);
   *     }
   *     else
   *     {
   *         writer.WriteNull("count"u8);
   *     }
   * ```
   */
  it("indents if/else block correctly for required nullable property", async () => {
    const [{ outputs }, diagnostics] = await HttpTester.compileAndDiagnose(`
      using TypeSpec.Http;

      @service
      namespace TestNamespace;

      model Widget {
        count: int32 | null;
      }

      @route("/test")
      op test(): Widget;
    `);

    expect(diagnostics).toHaveLength(0);

    const fileKey = Object.keys(outputs).find((k) =>
      k.includes("Widget.Serialization.cs"),
    );
    const content = outputs[fileKey!];

    // Verify full indented block structure
    expect(content).toContain("    if (Optional.IsDefined(Count))");
    expect(content).toContain("    {");
    expect(content).toContain('        writer.WritePropertyName("count"u8);');
    expect(content).toContain("        writer.WriteNumberValue(Count.Value);");
    expect(content).toContain("    else");
    expect(content).toContain('        writer.WriteNull("count"u8);');
  });

  /**
   * Validates that a model with mixed required, optional, and required-nullable
   * properties applies the correct pattern to each:
   * - Required non-nullable: direct write (no guard)
   * - Optional: if guard only (no else)
   * - Required nullable: if/else guard with WriteNull
   */
  it("handles mixed required, optional, and required-nullable properties", async () => {
    const [{ outputs }, diagnostics] = await HttpTester.compileAndDiagnose(`
      using TypeSpec.Http;

      @service
      namespace TestNamespace;

      model Widget {
        name: string;
        description?: string;
        count: int32 | null;
      }

      @route("/test")
      op test(): Widget;
    `);

    expect(diagnostics).toHaveLength(0);

    const fileKey = Object.keys(outputs).find((k) =>
      k.includes("Widget.Serialization.cs"),
    );
    const content = outputs[fileKey!];

    // Required non-nullable 'name': no guard
    expect(content).not.toContain("Optional.IsDefined(Name)");
    expect(content).toContain('writer.WritePropertyName("name"u8);');
    expect(content).toContain("writer.WriteStringValue(Name);");

    // Optional 'description': if guard only (no else/WriteNull)
    expect(content).toContain("if (Optional.IsDefined(Description))");
    expect(content).not.toContain('writer.WriteNull("description"u8);');

    // Required nullable 'count': if/else guard with WriteNull
    expect(content).toContain("if (Optional.IsDefined(Count))");
    expect(content).toContain("writer.WriteNumberValue(Count.Value);");
    expect(content).toContain('writer.WriteNull("count"u8);');
  });

  /**
   * Validates that a required nullable URL property (reference type) does not
   * get `.Value`. URL maps to System.Uri which is a class (reference type),
   * not a struct.
   */
  it("does not add .Value for required nullable URL (reference type)", async () => {
    const [{ outputs }, diagnostics] = await HttpTester.compileAndDiagnose(`
      using TypeSpec.Http;

      @service
      namespace TestNamespace;

      model Widget {
        endpoint: url | null;
      }

      @route("/test")
      op test(): Widget;
    `);

    expect(diagnostics).toHaveLength(0);

    const fileKey = Object.keys(outputs).find((k) =>
      k.includes("Widget.Serialization.cs"),
    );
    const content = outputs[fileKey!];

    expect(content).toContain("if (Optional.IsDefined(Endpoint))");
    // URL is a reference type — no .Value
    expect(content).toContain("writer.WriteStringValue(Endpoint);");
    expect(content).not.toContain("Endpoint.Value");
    expect(content).toContain('writer.WriteNull("endpoint"u8);');
  });
});

/**
 * Tests for the JsonDeserialize component.
 *
 * These tests verify that the emitter generates the `DeserializeXxx` static
 * deserialization method inside model `.Serialization.cs` files. The
 * JsonDeserialize component produces the core deserialization method skeleton:
 * method signature with correct parameters, null check, and children slot.
 *
 * Why these tests matter:
 * - The deserialization method is the entry point for JSON→model conversion,
 *   required by the `IJsonModel<T>.Create` explicit interface implementation.
 * - Validates the method signature pattern (`internal static {Model} Deserialize{Model}`).
 * - Ensures the null check handles `JsonValueKind.Null` consistently.
 * - Verifies using directives for `System.Text.Json` and `System.ClientModel.Primitives`
 *   are generated via builtin refkeys.
 * - Confirms the method is placed inside the serialization partial class.
 */
describe("JsonDeserialize", () => {
  /**
   * Validates the deserialization method signature follows the legacy emitter's
   * convention: `internal static {Model} Deserialize{Model}(JsonElement, ModelReaderWriterOptions)`.
   * The `internal static` modifier is critical — the method is called by the
   * IJsonModel<T>.Create implementation but should not be part of the public API.
   */
  it("generates deserialization method with correct signature", async () => {
    const [{ outputs }, diagnostics] = await HttpTester.compileAndDiagnose(`
      using TypeSpec.Http;

      @service
      namespace TestNamespace;

      model Widget {
        name: string;
      }

      @route("/test")
      op test(): Widget;
    `);

    expect(diagnostics).toHaveLength(0);

    const fileKey = Object.keys(outputs).find((k) =>
      k.includes("Widget.Serialization.cs"),
    );
    expect(fileKey).toBeDefined();
    const content = outputs[fileKey!];

    expect(content).toContain(
      "internal static Widget DeserializeWidget(JsonElement element, ModelReaderWriterOptions options)",
    );
  });

  /**
   * Validates that the deserialization method includes a null check at the top.
   * When a JSON element is null, the method should return null immediately rather
   * than attempting to deserialize properties. This is essential for handling
   * nullable model references in JSON payloads.
   */
  it("generates null check that returns null for null JSON element", async () => {
    const [{ outputs }, diagnostics] = await HttpTester.compileAndDiagnose(`
      using TypeSpec.Http;

      @service
      namespace TestNamespace;

      model Widget {
        name: string;
      }

      @route("/test")
      op test(): Widget;
    `);

    expect(diagnostics).toHaveLength(0);

    const fileKey = Object.keys(outputs).find((k) =>
      k.includes("Widget.Serialization.cs"),
    );
    const content = outputs[fileKey!];

    expect(content).toContain("if (element.ValueKind == JsonValueKind.Null)");
    expect(content).toContain("return null;");
  });

  /**
   * Validates that using directives for System.Text.Json are generated.
   * The method signature references `JsonElement` and the body references
   * `JsonValueKind` — both require `using System.Text.Json;` to compile.
   * The using is auto-generated via Alloy's builtin refkey system when
   * `SystemTextJson.JsonElement` is referenced in the code template.
   */
  it("generates using directive for System.Text.Json", async () => {
    const [{ outputs }, diagnostics] = await HttpTester.compileAndDiagnose(`
      using TypeSpec.Http;

      @service
      namespace TestNamespace;

      model Widget {
        name: string;
      }

      @route("/test")
      op test(): Widget;
    `);

    expect(diagnostics).toHaveLength(0);

    const fileKey = Object.keys(outputs).find((k) =>
      k.includes("Widget.Serialization.cs"),
    );
    const content = outputs[fileKey!];

    expect(content).toContain("using System.Text.Json;");
  });

  /**
   * Validates that the deserialization method is generated for derived models.
   * Each model in a discriminated hierarchy gets its own deserialization method,
   * not just the base model. The return type and method name must match the
   * specific derived model type.
   */
  it("generates deserialization method for derived models", async () => {
    const [{ outputs }, diagnostics] = await HttpTester.compileAndDiagnose(`
      using TypeSpec.Http;

      @service
      namespace TestNamespace;

      @discriminator("kind")
      model Pet {
        kind: string;
        name: string;
      }

      model Dog extends Pet {
        kind: "dog";
        breed: string;
      }

      @route("/test")
      op test(): Pet;
    `);

    expect(diagnostics).toHaveLength(0);

    // Check base model
    const petFile = Object.keys(outputs).find((k) =>
      k.includes("Pet.Serialization.cs"),
    );
    expect(petFile).toBeDefined();
    const petContent = outputs[petFile!];
    expect(petContent).toContain(
      "internal static Pet DeserializePet(JsonElement element, ModelReaderWriterOptions options)",
    );

    // Check derived model
    const dogFile = Object.keys(outputs).find((k) =>
      k.includes("Dog.Serialization.cs"),
    );
    expect(dogFile).toBeDefined();
    const dogContent = outputs[dogFile!];
    expect(dogContent).toContain(
      "internal static Dog DeserializeDog(JsonElement element, ModelReaderWriterOptions options)",
    );
  });

  /**
   * Validates that the deserialization method is placed inside the serialization
   * partial class, after the write core method and deserialization constructor.
   * The method must be within the class body for correct C# partial class semantics.
   */
  it("is placed inside the serialization partial class", async () => {
    const [{ outputs }, diagnostics] = await HttpTester.compileAndDiagnose(`
      using TypeSpec.Http;

      @service
      namespace TestNamespace;

      model Widget {
        name: string;
      }

      @route("/test")
      op test(): Widget;
    `);

    expect(diagnostics).toHaveLength(0);

    const fileKey = Object.keys(outputs).find((k) =>
      k.includes("Widget.Serialization.cs"),
    );
    const content = outputs[fileKey!];

    // The deserialization method should appear after the write core method
    const writeIndex = content.indexOf("JsonModelWriteCore");
    const deserializeIndex = content.indexOf("DeserializeWidget");
    expect(writeIndex).toBeGreaterThan(-1);
    expect(deserializeIndex).toBeGreaterThan(-1);
    expect(deserializeIndex).toBeGreaterThan(writeIndex);
  });

  /**
   * Validates the complete structure of the deserialization method body.
   * The null check should be properly indented inside the method body with
   * Allman-style braces matching the legacy emitter's golden file format.
   */
  it("generates correctly indented method body", async () => {
    const [{ outputs }, diagnostics] = await HttpTester.compileAndDiagnose(`
      using TypeSpec.Http;

      @service
      namespace TestNamespace;

      model Widget {
        name: string;
      }

      @route("/test")
      op test(): Widget;
    `);

    expect(diagnostics).toHaveLength(0);

    const fileKey = Object.keys(outputs).find((k) =>
      k.includes("Widget.Serialization.cs"),
    );
    const content = outputs[fileKey!];

    // Check the overall method structure with indentation
    expect(content).toContain("internal static Widget DeserializeWidget(JsonElement element, ModelReaderWriterOptions options)");
    expect(content).toMatch(/DeserializeWidget\(JsonElement element, ModelReaderWriterOptions options\)\n\s*\{/);
    expect(content).toContain("    if (element.ValueKind == JsonValueKind.Null)");
    expect(content).toContain("        return null;");
  });
});
