import { describe, expect, it } from "vitest";
import { HttpTester } from "./test-host.js";

/**
 * Tests for the ModelSerializationFile component.
 *
 * These tests verify that the emitter generates `.Serialization.cs` partial class
 * files for models that implement `IJsonModel<T>`. The ModelSerializationFile component
 * is responsible for the serialization file skeleton: header, namespace, partial class
 * declaration with the `IJsonModel<T>` interface, and correct access modifiers.
 *
 * Why these tests matter:
 * - Serialization files are the foundation for all model serialization/deserialization
 *   code (JSON write, JSON read, cast operators, etc.).
 * - Validates that the correct file path (`{Name}.Serialization.cs`) is used.
 * - Ensures the `IJsonModel<T>` interface is properly declared, which is required
 *   for the System.ClientModel serialization framework.
 * - Verifies that derived models re-declare their base type in the serialization file.
 * - Ensures abstract models get the `abstract` modifier in the serialization file.
 */
describe("ModelSerializationFile", () => {
  /**
   * Validates that a `.Serialization.cs` file is generated at the expected path
   * alongside the regular model file. Both files must exist for a complete model.
   */
  it("generates a serialization file at the correct path", async () => {
    const [{ outputs }, diagnostics] = await HttpTester.compileAndDiagnose(`
      using TypeSpec.Http;

      @service
      namespace TestNamespace;

      model Widget {
        name: string;
      }

      @route("/test")
      op test(): Widget;
    `);

    expect(diagnostics).toHaveLength(0);

    const serializationFileKey = Object.keys(outputs).find((k) =>
      k.includes("Widget.Serialization.cs"),
    );
    expect(serializationFileKey).toBeDefined();
    expect(serializationFileKey).toContain(
      "src/Generated/Models/Widget.Serialization.cs",
    );
  });

  /**
   * Validates that the serialization file includes the standard auto-generated
   * header (`// <auto-generated/>` and `#nullable disable`). This must match
   * the legacy emitter's golden file format.
   */
  it("includes the standard auto-generated header", async () => {
    const [{ outputs }, diagnostics] = await HttpTester.compileAndDiagnose(`
      using TypeSpec.Http;

      @service
      namespace TestNamespace;

      model Widget {
        name: string;
      }

      @route("/test")
      op test(): Widget;
    `);

    expect(diagnostics).toHaveLength(0);

    const fileKey = Object.keys(outputs).find((k) =>
      k.includes("Widget.Serialization.cs"),
    );
    const content = outputs[fileKey!];

    expect(content).toContain("// <auto-generated/>");
    expect(content).toContain("#nullable disable");
  });

  /**
   * Validates that the serialization class declares `IJsonModel<T>` as an interface.
   * This is the core requirement — the `IJsonModel<T>` interface (which inherits from
   * `IPersistableModel<T>`) is how the System.ClientModel framework discovers
   * serializable models.
   */
  it("declares IJsonModel<T> interface on the partial class", async () => {
    const [{ outputs }, diagnostics] = await HttpTester.compileAndDiagnose(`
      using TypeSpec.Http;

      @service
      namespace TestNamespace;

      model Widget {
        name: string;
      }

      @route("/test")
      op test(): Widget;
    `);

    expect(diagnostics).toHaveLength(0);

    const fileKey = Object.keys(outputs).find((k) =>
      k.includes("Widget.Serialization.cs"),
    );
    const content = outputs[fileKey!];

    // Must be a partial class implementing IJsonModel<Widget>
    expect(content).toMatch(
      /public\s+partial\s+class\s+Widget\s*:\s*IJsonModel<Widget>/,
    );
  });

  /**
   * Validates that the `using System.ClientModel.Primitives;` directive is
   * auto-generated because IJsonModel<T> is referenced from that namespace.
   * This using statement is critical for the serialization code to compile.
   */
  it("includes using directive for System.ClientModel.Primitives", async () => {
    const [{ outputs }, diagnostics] = await HttpTester.compileAndDiagnose(`
      using TypeSpec.Http;

      @service
      namespace TestNamespace;

      model Widget {
        name: string;
      }

      @route("/test")
      op test(): Widget;
    `);

    expect(diagnostics).toHaveLength(0);

    const fileKey = Object.keys(outputs).find((k) =>
      k.includes("Widget.Serialization.cs"),
    );
    const content = outputs[fileKey!];

    expect(content).toContain("using System.ClientModel.Primitives;");
  });

  /**
   * Validates that the serialization class is in the correct namespace,
   * matching the model's namespace from the TCGC SDK type.
   */
  it("wraps the class in the correct namespace", async () => {
    const [{ outputs }, diagnostics] = await HttpTester.compileAndDiagnose(`
      using TypeSpec.Http;

      @service
      namespace TestNamespace;

      model Widget {
        name: string;
      }

      @route("/test")
      op test(): Widget;
    `);

    expect(diagnostics).toHaveLength(0);

    const fileKey = Object.keys(outputs).find((k) =>
      k.includes("Widget.Serialization.cs"),
    );
    const content = outputs[fileKey!];

    expect(content).toMatch(/namespace\s+TestNamespace/);
  });

  /**
   * Validates that derived models re-declare the base type in the serialization
   * file's class declaration. C# requires all partial declarations to agree on
   * the base class. For example: `public partial class Dog : Pet, IJsonModel<Dog>`.
   */
  it("re-declares base type for derived models", async () => {
    const [{ outputs }, diagnostics] = await HttpTester.compileAndDiagnose(`
      using TypeSpec.Http;

      @service
      namespace TestNamespace;

      @discriminator("kind")
      model Pet {
        kind: string;
        name: string;
      }

      model Dog extends Pet {
        kind: "dog";
        breed: string;
      }

      @route("/test")
      op test(): Pet;
    `);

    expect(diagnostics).toHaveLength(0);

    const dogFileKey = Object.keys(outputs).find((k) =>
      k.includes("Dog.Serialization.cs"),
    );
    expect(dogFileKey).toBeDefined();
    const dogContent = outputs[dogFileKey!];

    // Derived model must re-declare base type and implement IJsonModel<Dog>
    expect(dogContent).toMatch(
      /public\s+partial\s+class\s+Dog\s*:\s*Pet,\s*IJsonModel<Dog>/,
    );
  });

  /**
   * Validates that abstract base models with discriminators get the `abstract`
   * modifier in the serialization file, matching the main model file's declaration.
   * Abstract models cannot be instantiated directly — only derived types can.
   */
  it("applies abstract modifier for discriminated base models", async () => {
    const [{ outputs }, diagnostics] = await HttpTester.compileAndDiagnose(`
      using TypeSpec.Http;

      @service
      namespace TestNamespace;

      @discriminator("kind")
      model Pet {
        kind: string;
        name: string;
      }

      model Dog extends Pet {
        kind: "dog";
        breed: string;
      }

      @route("/test")
      op test(): Pet;
    `);

    expect(diagnostics).toHaveLength(0);

    const petFileKey = Object.keys(outputs).find((k) =>
      k.includes("Pet.Serialization.cs"),
    );
    expect(petFileKey).toBeDefined();
    const petContent = outputs[petFileKey!];

    // Base model must be abstract in the serialization file
    expect(petContent).toMatch(
      /public\s+abstract\s+partial\s+class\s+Pet\s*:\s*IJsonModel<Pet>/,
    );
  });

  /**
   * Validates that each model in the SDK package gets its own serialization file,
   * including both base and derived models in a discriminator hierarchy.
   */
  it("generates serialization files for all models in hierarchy", async () => {
    const [{ outputs }, diagnostics] = await HttpTester.compileAndDiagnose(`
      using TypeSpec.Http;

      @service
      namespace TestNamespace;

      @discriminator("kind")
      model Pet {
        kind: string;
        name: string;
      }

      model Dog extends Pet {
        kind: "dog";
        breed: string;
      }

      model Cat extends Pet {
        kind: "cat";
        indoor: boolean;
      }

      @route("/test")
      op test(): Pet;
    `);

    expect(diagnostics).toHaveLength(0);

    const serializationFiles = Object.keys(outputs).filter((k) =>
      k.includes(".Serialization.cs"),
    );

    // All three models should have serialization files
    expect(serializationFiles.some((k) => k.includes("Pet.Serialization.cs"))).toBe(true);
    expect(serializationFiles.some((k) => k.includes("Dog.Serialization.cs"))).toBe(true);
    expect(serializationFiles.some((k) => k.includes("Cat.Serialization.cs"))).toBe(true);
  });
});

/**
 * Tests for the DeserializationConstructor component.
 *
 * These tests verify that the emitter generates a parameterless `internal`
 * constructor in the `.Serialization.cs` partial class for models that need it.
 * The MRW (Model Reader/Writer) framework requires this constructor to create
 * empty model instances during deserialization.
 *
 * Why these tests matter:
 * - Without this constructor, the MRW framework cannot instantiate models for
 *   deserialization, causing runtime failures.
 * - The constructor must only be generated when the model's public init ctor
 *   has parameters — otherwise, a duplicate parameterless constructor would
 *   cause a C# compilation error.
 * - The XML doc comment format must match the legacy emitter's golden files.
 */
describe("DeserializationConstructor", () => {
  /**
   * Validates that a model with required properties gets a parameterless
   * internal constructor in its serialization file. Since the public init
   * ctor has parameters (name, value), no parameterless ctor exists, so
   * the deserialization constructor must be generated.
   */
  it("generates internal parameterless constructor for models with required properties", async () => {
    const [{ outputs }, diagnostics] = await HttpTester.compileAndDiagnose(`
      using TypeSpec.Http;

      @service
      namespace TestNamespace;

      model Widget {
        name: string;
        value: int32;
      }

      @route("/test")
      op test(): Widget;
    `);

    expect(diagnostics).toHaveLength(0);

    const fileKey = Object.keys(outputs).find((k) =>
      k.includes("Widget.Serialization.cs"),
    );
    const content = outputs[fileKey!];

    expect(content).toMatch(/internal\s+Widget\s*\(\s*\)/);
  });

  /**
   * Validates that the XML doc comment on the deserialization constructor
   * matches the legacy emitter's format: `/// <summary> Initializes a new
   * instance of <see cref="ModelName"/> for deserialization. </summary>`.
   * This ensures consistency with golden files.
   */
  it("includes XML doc comment for deserialization", async () => {
    const [{ outputs }, diagnostics] = await HttpTester.compileAndDiagnose(`
      using TypeSpec.Http;

      @service
      namespace TestNamespace;

      model Widget {
        name: string;
      }

      @route("/test")
      op test(): Widget;
    `);

    expect(diagnostics).toHaveLength(0);

    const fileKey = Object.keys(outputs).find((k) =>
      k.includes("Widget.Serialization.cs"),
    );
    const content = outputs[fileKey!];

    expect(content).toContain(
      '/// <summary> Initializes a new instance of <see cref="Widget"/> for deserialization. </summary>',
    );
  });

  /**
   * Validates that models with only optional properties do NOT get the
   * deserialization constructor. When all properties are optional, the
   * public init ctor has zero parameters, so it already serves as the
   * parameterless constructor — generating another would cause a C#
   * duplicate constructor error.
   */
  it("skips constructor for models with only optional properties", async () => {
    const [{ outputs }, diagnostics] = await HttpTester.compileAndDiagnose(`
      using TypeSpec.Http;

      @service
      namespace TestNamespace;

      model Widget {
        name?: string;
        value?: int32;
      }

      @route("/test")
      op test(): Widget;
    `);

    expect(diagnostics).toHaveLength(0);

    const fileKey = Object.keys(outputs).find((k) =>
      k.includes("Widget.Serialization.cs"),
    );
    const content = outputs[fileKey!];

    // Should NOT contain a parameterless internal constructor since
    // the public ctor already has zero parameters
    expect(content).not.toMatch(/internal\s+Widget\s*\(\s*\)/);
  });

  /**
   * Validates that derived models in a discriminator hierarchy get the
   * deserialization constructor when they have required base properties
   * (excluding the discriminator). For example, if Pet has `name: string`,
   * Dog extends Pet with `kind: "dog"` — Dog's public ctor takes `name`,
   * so Dog needs a parameterless deserialization ctor.
   */
  it("generates constructor for derived models with required base properties", async () => {
    const [{ outputs }, diagnostics] = await HttpTester.compileAndDiagnose(`
      using TypeSpec.Http;

      @service
      namespace TestNamespace;

      @discriminator("kind")
      model Pet {
        kind: string;
        name: string;
      }

      model Dog extends Pet {
        kind: "dog";
        breed: string;
      }

      @route("/test")
      op test(): Pet;
    `);

    expect(diagnostics).toHaveLength(0);

    const dogFileKey = Object.keys(outputs).find((k) =>
      k.includes("Dog.Serialization.cs"),
    );
    const dogContent = outputs[dogFileKey!];

    // Dog has required base params (name) + own params (breed),
    // so it needs a parameterless deserialization ctor
    expect(dogContent).toMatch(/internal\s+Dog\s*\(\s*\)/);
    expect(dogContent).toContain(
      '/// <summary> Initializes a new instance of <see cref="Dog"/> for deserialization. </summary>',
    );
  });

  /**
   * Validates that derived models WITHOUT required base properties (other
   * than the discriminator) do NOT get the deserialization constructor.
   * When Pet only has `kind: string` (the discriminator), Dog's public ctor
   * has zero parameters, so a deserialization ctor would duplicate it.
   */
  it("skips constructor for derived models with no required non-discriminator base properties", async () => {
    const [{ outputs }, diagnostics] = await HttpTester.compileAndDiagnose(`
      using TypeSpec.Http;

      @service
      namespace TestNamespace;

      @discriminator("kind")
      model Pet {
        kind: string;
      }

      model Dog extends Pet {
        kind: "dog";
      }

      @route("/test")
      op test(): Pet;
    `);

    expect(diagnostics).toHaveLength(0);

    const dogFileKey = Object.keys(outputs).find((k) =>
      k.includes("Dog.Serialization.cs"),
    );
    const dogContent = outputs[dogFileKey!];

    // Dog has no required params (kind is the discriminator, filtered out),
    // so its public ctor is parameterless — no deserialization ctor needed
    expect(dogContent).not.toMatch(/internal\s+Dog\s*\(\s*\)/);
  });

  /**
   * Validates that abstract base models in a discriminator hierarchy also
   * get the deserialization constructor when they have required properties.
   * Even though abstract models can't be directly instantiated, their
   * deserialization constructors are called by derived model constructors
   * via constructor chaining.
   */
  it("generates constructor for abstract base models with required properties", async () => {
    const [{ outputs }, diagnostics] = await HttpTester.compileAndDiagnose(`
      using TypeSpec.Http;

      @service
      namespace TestNamespace;

      @discriminator("kind")
      model Pet {
        kind: string;
        name: string;
      }

      model Dog extends Pet {
        kind: "dog";
      }

      @route("/test")
      op test(): Pet;
    `);

    expect(diagnostics).toHaveLength(0);

    const petFileKey = Object.keys(outputs).find((k) =>
      k.includes("Pet.Serialization.cs"),
    );
    const petContent = outputs[petFileKey!];

    // Pet has required properties (kind + name), so it needs the ctor
    expect(petContent).toMatch(/internal\s+Pet\s*\(\s*\)/);
    expect(petContent).toContain(
      '/// <summary> Initializes a new instance of <see cref="Pet"/> for deserialization. </summary>',
    );
  });
});
