import { describe, expect, it } from "vitest";
import { HttpTester } from "./test-host.js";

/**
 * Tests for the ModelSerializationFile component.
 *
 * These tests verify that the emitter generates `.Serialization.cs` partial class
 * files for models that implement `IJsonModel<T>`. The ModelSerializationFile component
 * is responsible for the serialization file skeleton: header, namespace, partial class
 * declaration with the `IJsonModel<T>` interface, and correct access modifiers.
 *
 * Why these tests matter:
 * - Serialization files are the foundation for all model serialization/deserialization
 *   code (JSON write, JSON read, cast operators, etc.).
 * - Validates that the correct file path (`{Name}.Serialization.cs`) is used.
 * - Ensures the `IJsonModel<T>` interface is properly declared, which is required
 *   for the System.ClientModel serialization framework.
 * - Verifies that derived models re-declare their base type in the serialization file.
 * - Ensures abstract models get the `abstract` modifier in the serialization file.
 */
describe("ModelSerializationFile", () => {
  /**
   * Validates that a `.Serialization.cs` file is generated at the expected path
   * alongside the regular model file. Both files must exist for a complete model.
   */
  it("generates a serialization file at the correct path", async () => {
    const [{ outputs }, diagnostics] = await HttpTester.compileAndDiagnose(`
      using TypeSpec.Http;

      @service
      namespace TestNamespace;

      model Widget {
        name: string;
      }

      @route("/test")
      op test(): Widget;
    `);

    expect(diagnostics).toHaveLength(0);

    const serializationFileKey = Object.keys(outputs).find((k) =>
      k.includes("Widget.Serialization.cs"),
    );
    expect(serializationFileKey).toBeDefined();
    expect(serializationFileKey).toContain(
      "src/Generated/Models/Widget.Serialization.cs",
    );
  });

  /**
   * Validates that the serialization file includes the standard auto-generated
   * header (`// <auto-generated/>` and `#nullable disable`). This must match
   * the legacy emitter's golden file format.
   */
  it("includes the standard auto-generated header", async () => {
    const [{ outputs }, diagnostics] = await HttpTester.compileAndDiagnose(`
      using TypeSpec.Http;

      @service
      namespace TestNamespace;

      model Widget {
        name: string;
      }

      @route("/test")
      op test(): Widget;
    `);

    expect(diagnostics).toHaveLength(0);

    const fileKey = Object.keys(outputs).find((k) =>
      k.includes("Widget.Serialization.cs"),
    );
    const content = outputs[fileKey!];

    expect(content).toContain("// <auto-generated/>");
    expect(content).toContain("#nullable disable");
  });

  /**
   * Validates that the serialization class declares `IJsonModel<T>` as an interface.
   * This is the core requirement — the `IJsonModel<T>` interface (which inherits from
   * `IPersistableModel<T>`) is how the System.ClientModel framework discovers
   * serializable models.
   */
  it("declares IJsonModel<T> interface on the partial class", async () => {
    const [{ outputs }, diagnostics] = await HttpTester.compileAndDiagnose(`
      using TypeSpec.Http;

      @service
      namespace TestNamespace;

      model Widget {
        name: string;
      }

      @route("/test")
      op test(): Widget;
    `);

    expect(diagnostics).toHaveLength(0);

    const fileKey = Object.keys(outputs).find((k) =>
      k.includes("Widget.Serialization.cs"),
    );
    const content = outputs[fileKey!];

    // Must be a partial class implementing IJsonModel<Widget>
    expect(content).toMatch(
      /public\s+partial\s+class\s+Widget\s*:\s*IJsonModel<Widget>/,
    );
  });

  /**
   * Validates that the `using System.ClientModel.Primitives;` directive is
   * auto-generated because IJsonModel<T> is referenced from that namespace.
   * This using statement is critical for the serialization code to compile.
   */
  it("includes using directive for System.ClientModel.Primitives", async () => {
    const [{ outputs }, diagnostics] = await HttpTester.compileAndDiagnose(`
      using TypeSpec.Http;

      @service
      namespace TestNamespace;

      model Widget {
        name: string;
      }

      @route("/test")
      op test(): Widget;
    `);

    expect(diagnostics).toHaveLength(0);

    const fileKey = Object.keys(outputs).find((k) =>
      k.includes("Widget.Serialization.cs"),
    );
    const content = outputs[fileKey!];

    expect(content).toContain("using System.ClientModel.Primitives;");
  });

  /**
   * Validates that the serialization class is in the correct namespace,
   * matching the model's namespace from the TCGC SDK type.
   */
  it("wraps the class in the correct namespace", async () => {
    const [{ outputs }, diagnostics] = await HttpTester.compileAndDiagnose(`
      using TypeSpec.Http;

      @service
      namespace TestNamespace;

      model Widget {
        name: string;
      }

      @route("/test")
      op test(): Widget;
    `);

    expect(diagnostics).toHaveLength(0);

    const fileKey = Object.keys(outputs).find((k) =>
      k.includes("Widget.Serialization.cs"),
    );
    const content = outputs[fileKey!];

    expect(content).toMatch(/namespace\s+TestNamespace/);
  });

  /**
   * Validates that derived models re-declare the base type in the serialization
   * file's class declaration. C# requires all partial declarations to agree on
   * the base class. For example: `public partial class Dog : Pet, IJsonModel<Dog>`.
   */
  it("re-declares base type for derived models", async () => {
    const [{ outputs }, diagnostics] = await HttpTester.compileAndDiagnose(`
      using TypeSpec.Http;

      @service
      namespace TestNamespace;

      @discriminator("kind")
      model Pet {
        kind: string;
        name: string;
      }

      model Dog extends Pet {
        kind: "dog";
        breed: string;
      }

      @route("/test")
      op test(): Pet;
    `);

    expect(diagnostics).toHaveLength(0);

    const dogFileKey = Object.keys(outputs).find((k) =>
      k.includes("Dog.Serialization.cs"),
    );
    expect(dogFileKey).toBeDefined();
    const dogContent = outputs[dogFileKey!];

    // Derived model must re-declare base type and implement IJsonModel<Dog>
    expect(dogContent).toMatch(
      /public\s+partial\s+class\s+Dog\s*:\s*Pet,\s*IJsonModel<Dog>/,
    );
  });

  /**
   * Validates that abstract base models with discriminators get the `abstract`
   * modifier in the serialization file, matching the main model file's declaration.
   * Abstract models cannot be instantiated directly — only derived types can.
   */
  it("applies abstract modifier for discriminated base models", async () => {
    const [{ outputs }, diagnostics] = await HttpTester.compileAndDiagnose(`
      using TypeSpec.Http;

      @service
      namespace TestNamespace;

      @discriminator("kind")
      model Pet {
        kind: string;
        name: string;
      }

      model Dog extends Pet {
        kind: "dog";
        breed: string;
      }

      @route("/test")
      op test(): Pet;
    `);

    expect(diagnostics).toHaveLength(0);

    const petFileKey = Object.keys(outputs).find((k) =>
      k.includes("Pet.Serialization.cs"),
    );
    expect(petFileKey).toBeDefined();
    const petContent = outputs[petFileKey!];

    // Base model must be abstract in the serialization file
    expect(petContent).toMatch(
      /public\s+abstract\s+partial\s+class\s+Pet\s*:\s*IJsonModel<Pet>/,
    );
  });

  /**
   * Validates that each model in the SDK package gets its own serialization file,
   * including both base and derived models in a discriminator hierarchy.
   */
  it("generates serialization files for all models in hierarchy", async () => {
    const [{ outputs }, diagnostics] = await HttpTester.compileAndDiagnose(`
      using TypeSpec.Http;

      @service
      namespace TestNamespace;

      @discriminator("kind")
      model Pet {
        kind: string;
        name: string;
      }

      model Dog extends Pet {
        kind: "dog";
        breed: string;
      }

      model Cat extends Pet {
        kind: "cat";
        indoor: boolean;
      }

      @route("/test")
      op test(): Pet;
    `);

    expect(diagnostics).toHaveLength(0);

    const serializationFiles = Object.keys(outputs).filter((k) =>
      k.includes(".Serialization.cs"),
    );

    // All three models should have serialization files
    expect(serializationFiles.some((k) => k.includes("Pet.Serialization.cs"))).toBe(true);
    expect(serializationFiles.some((k) => k.includes("Dog.Serialization.cs"))).toBe(true);
    expect(serializationFiles.some((k) => k.includes("Cat.Serialization.cs"))).toBe(true);
  });
});
