import { describe, it, expect } from "vitest";
import { fixNamespaceBraceStyle } from "../src/utils/namespace-brace-style.js";

/**
 * Tests for the namespace brace style post-processing utility.
 *
 * The Alloy C# Namespace component renders K&R-style braces (opening brace
 * on the same line). The legacy emitter golden files use Allman style (brace
 * on the next line). These tests verify that the post-processing correctly
 * converts between the two styles.
 *
 * This is critical because every generated C# file contains a namespace
 * declaration, so any regression here affects the entire output surface.
 */
describe("fixNamespaceBraceStyle", () => {
  /**
   * The most common case: a simple namespace declaration at column 0
   * with content inside. Verifies K&R → Allman conversion.
   */
  it("converts K&R brace to Allman style for a simple namespace", () => {
    const input = `namespace TestNamespace {
    public partial class Widget
    {
    }
}
`;
    const expected = `namespace TestNamespace
{
    public partial class Widget
    {
    }
}
`;
    expect(fixNamespaceBraceStyle(input)).toBe(expected);
  });

  /**
   * Dotted namespaces (e.g., SampleTypeSpec.Models) are common in the
   * generated output. The regex must handle dots in namespace names.
   */
  it("handles dotted namespace names", () => {
    const input = `namespace My.Service.Models {
    public class Foo { }
}
`;
    const expected = `namespace My.Service.Models
{
    public class Foo { }
}
`;
    expect(fixNamespaceBraceStyle(input)).toBe(expected);
  });

  /**
   * If a file is already in Allman style (e.g., manually written or
   * previously processed), the function should leave it unchanged.
   * The regex only matches `namespace <name> {` on the same line.
   */
  it("leaves Allman-style namespaces unchanged", () => {
    const input = `namespace TestNamespace
{
    public class Widget { }
}
`;
    expect(fixNamespaceBraceStyle(input)).toBe(input);
  });

  /**
   * Files without namespace declarations (unlikely but possible)
   * should pass through unchanged.
   */
  it("returns unchanged content when no namespace is present", () => {
    const input = `// Some comment
public class GlobalClass { }
`;
    expect(fixNamespaceBraceStyle(input)).toBe(input);
  });

  /**
   * A full file with header, usings, and namespace — the typical
   * output format after header reordering. Verifies the fix works
   * in context with surrounding content.
   */
  it("works with full file content including header and usings", () => {
    const input = `// <auto-generated/>

#nullable disable

using System;
using System.Collections.Generic;

namespace TestNamespace {
    public partial class Widget
    {
        public string Name { get; }
    }
}
`;
    const expected = `// <auto-generated/>

#nullable disable

using System;
using System.Collections.Generic;

namespace TestNamespace
{
    public partial class Widget
    {
        public string Name { get; }
    }
}
`;
    expect(fixNamespaceBraceStyle(input)).toBe(expected);
  });

  /**
   * Namespaces with underscored segments (from C# keyword escaping,
   * e.g., `Type` → `_Type`) must also be handled.
   */
  it("handles namespace names with underscores", () => {
    const input = `namespace My._Type.Models {
    public class Foo { }
}
`;
    const expected = `namespace My._Type.Models
{
    public class Foo { }
}
`;
    expect(fixNamespaceBraceStyle(input)).toBe(expected);
  });

  /**
   * The word "namespace" might appear in comments or strings.
   * The regex is anchored to lines that start with optional whitespace
   * followed by `namespace`, so it should not match comments.
   */
  it("does not modify namespace mentions in comments", () => {
    const input = `// The namespace Foo.Bar { is defined here
namespace TestNamespace {
    public class Widget { }
}
`;
    const expected = `// The namespace Foo.Bar { is defined here
namespace TestNamespace
{
    public class Widget { }
}
`;
    expect(fixNamespaceBraceStyle(input)).toBe(expected);
  });

  /**
   * Ensures class-level K&R braces (e.g., `class Foo {`) are NOT
   * affected by this transformation. Only namespace declarations
   * should be converted.
   */
  it("does not modify class-level braces", () => {
    const input = `namespace TestNamespace {
    public class Widget {
        public string Name { get; }
    }
}
`;
    const expected = `namespace TestNamespace
{
    public class Widget {
        public string Name { get; }
    }
}
`;
    expect(fixNamespaceBraceStyle(input)).toBe(expected);
  });
});
