import { describe, it, expect } from "vitest";
import {
  fixNamespaceBraceStyle,
  fixEmptyClassBody,
} from "../src/utils/namespace-brace-style.js";

/**
 * Tests for the namespace brace style post-processing utility.
 *
 * The Alloy C# Namespace component renders K&R-style braces (opening brace
 * on the same line). The legacy emitter golden files use Allman style (brace
 * on the next line). These tests verify that the post-processing correctly
 * converts between the two styles.
 *
 * This is critical because every generated C# file contains a namespace
 * declaration, so any regression here affects the entire output surface.
 */
describe("fixNamespaceBraceStyle", () => {
  /**
   * The most common case: a simple namespace declaration at column 0
   * with content inside. Verifies K&R → Allman conversion.
   */
  it("converts K&R brace to Allman style for a simple namespace", () => {
    const input = `namespace TestNamespace {
    public partial class Widget
    {
    }
}
`;
    const expected = `namespace TestNamespace
{
    public partial class Widget
    {
    }
}
`;
    expect(fixNamespaceBraceStyle(input)).toBe(expected);
  });

  /**
   * Dotted namespaces (e.g., SampleTypeSpec.Models) are common in the
   * generated output. The regex must handle dots in namespace names.
   */
  it("handles dotted namespace names", () => {
    const input = `namespace My.Service.Models {
    public class Foo { }
}
`;
    const expected = `namespace My.Service.Models
{
    public class Foo { }
}
`;
    expect(fixNamespaceBraceStyle(input)).toBe(expected);
  });

  /**
   * If a file is already in Allman style (e.g., manually written or
   * previously processed), the function should leave it unchanged.
   * The regex only matches `namespace <name> {` on the same line.
   */
  it("leaves Allman-style namespaces unchanged", () => {
    const input = `namespace TestNamespace
{
    public class Widget { }
}
`;
    expect(fixNamespaceBraceStyle(input)).toBe(input);
  });

  /**
   * Files without namespace declarations (unlikely but possible)
   * should pass through unchanged.
   */
  it("returns unchanged content when no namespace is present", () => {
    const input = `// Some comment
public class GlobalClass { }
`;
    expect(fixNamespaceBraceStyle(input)).toBe(input);
  });

  /**
   * A full file with header, usings, and namespace — the typical
   * output format after header reordering. Verifies the fix works
   * in context with surrounding content.
   */
  it("works with full file content including header and usings", () => {
    const input = `// <auto-generated/>

#nullable disable

using System;
using System.Collections.Generic;

namespace TestNamespace {
    public partial class Widget
    {
        public string Name { get; }
    }
}
`;
    const expected = `// <auto-generated/>

#nullable disable

using System;
using System.Collections.Generic;

namespace TestNamespace
{
    public partial class Widget
    {
        public string Name { get; }
    }
}
`;
    expect(fixNamespaceBraceStyle(input)).toBe(expected);
  });

  /**
   * Namespaces with underscored segments (from C# keyword escaping,
   * e.g., `Type` → `_Type`) must also be handled.
   */
  it("handles namespace names with underscores", () => {
    const input = `namespace My._Type.Models {
    public class Foo { }
}
`;
    const expected = `namespace My._Type.Models
{
    public class Foo { }
}
`;
    expect(fixNamespaceBraceStyle(input)).toBe(expected);
  });

  /**
   * The word "namespace" might appear in comments or strings.
   * The regex is anchored to lines that start with optional whitespace
   * followed by `namespace`, so it should not match comments.
   */
  it("does not modify namespace mentions in comments", () => {
    const input = `// The namespace Foo.Bar { is defined here
namespace TestNamespace {
    public class Widget { }
}
`;
    const expected = `// The namespace Foo.Bar { is defined here
namespace TestNamespace
{
    public class Widget { }
}
`;
    expect(fixNamespaceBraceStyle(input)).toBe(expected);
  });

  /**
   * Ensures class-level K&R braces (e.g., `class Foo {`) are NOT
   * affected by this transformation. Only namespace declarations
   * should be converted.
   */
  it("does not modify class-level braces", () => {
    const input = `namespace TestNamespace {
    public class Widget {
        public string Name { get; }
    }
}
`;
    const expected = `namespace TestNamespace
{
    public class Widget {
        public string Name { get; }
    }
}
`;
    expect(fixNamespaceBraceStyle(input)).toBe(expected);
  });
});

/**
 * Tests for the empty class body post-processing utility.
 *
 * The Alloy C# ClassDeclaration component renders empty classes (no children)
 * with a file-scoped declaration ending in `;` (e.g., `class Foo;`).
 * The legacy emitter golden files use block-body style with empty braces on
 * separate lines. These tests verify the post-processing correctly converts
 * file-scoped empty class declarations to block-body style.
 *
 * This is important because the ModelReaderWriterContext class is always empty
 * (it only has attributes), and matching the golden file format is required
 * for output consistency.
 */
describe("fixEmptyClassBody", () => {
  /**
   * The most common case: a public partial class with a base type ending in `;`.
   * This is the pattern used by ModelReaderWriterContext.
   */
  it("converts file-scoped class to block-body style", () => {
    const input = `    public partial class FooContext : ModelReaderWriterContext;`;
    const expected = `    public partial class FooContext : ModelReaderWriterContext
    {
    }`;
    expect(fixEmptyClassBody(input)).toBe(expected);
  });

  /**
   * Internal classes should also be converted, not just public ones.
   */
  it("handles internal class declarations", () => {
    const input = `    internal partial class InternalContext : BaseClass;`;
    const expected = `    internal partial class InternalContext : BaseClass
    {
    }`;
    expect(fixEmptyClassBody(input)).toBe(expected);
  });

  /**
   * Classes without base types should also be handled.
   */
  it("handles class without base type", () => {
    const input = `    public class EmptyClass;`;
    const expected = `    public class EmptyClass
    {
    }`;
    expect(fixEmptyClassBody(input)).toBe(expected);
  });

  /**
   * Ensures regular class declarations with braces are NOT affected.
   * Only classes ending with `;` should be converted.
   */
  it("does not modify classes with block bodies", () => {
    const input = `    public class Widget
    {
        public string Name { get; }
    }`;
    expect(fixEmptyClassBody(input)).toBe(input);
  });

  /**
   * Works in context of a full file with namespace, attributes, etc.
   * This simulates the actual ModelReaderWriterContext output.
   */
  it("works in full file context with attributes", () => {
    const input = `// <auto-generated/>

#nullable disable

using System.ClientModel.Primitives;

namespace TestNamespace
{
    [ModelReaderWriterBuildable(typeof(Widget))]
    public partial class TestNamespaceContext : ModelReaderWriterContext;
}
`;
    const expected = `// <auto-generated/>

#nullable disable

using System.ClientModel.Primitives;

namespace TestNamespace
{
    [ModelReaderWriterBuildable(typeof(Widget))]
    public partial class TestNamespaceContext : ModelReaderWriterContext
    {
    }
}
`;
    expect(fixEmptyClassBody(input)).toBe(expected);
  });

  /**
   * Ensures non-class statements ending with `;` are not affected.
   * Property declarations, method signatures, etc. should remain unchanged.
   */
  it("does not modify non-class semicolons", () => {
    const input = `    public string Name { get; set; }
    public void DoSomething();
    using System;`;
    expect(fixEmptyClassBody(input)).toBe(input);
  });
});
