import { describe, expect, it } from "vitest";
import { reorderFileHeader } from "../src/utils/reorder-header.js";
import { HttpTester } from "./test-host.js";

/**
 * Tests for the file header reordering utility and its integration with the
 * emitter pipeline.
 *
 * The Alloy C# SourceFile component renders auto-detected `using` directives
 * before children content. Since the license/auto-generated header is injected
 * as children, it ends up after the usings. The reorderFileHeader function
 * post-processes the rendered output to place the header before usings,
 * matching the golden file format from the legacy emitter.
 *
 * Getting the header ordering wrong would cause diffs against every golden
 * file in the legacy test projects and break downstream tooling that parses
 * the auto-generated marker at the top of files.
 */
describe("reorderFileHeader", () => {
  /**
   * The core reordering case: when using directives appear before the
   * auto-generated header, the function should swap them so the header
   * comes first. This is the primary fix for the SourceFile rendering order.
   */
  it("moves header before usings when usings come first", () => {
    const input = [
      "using System;",
      "using System.Collections.Generic;",
      "",
      "// <auto-generated/>",
      "",
      "#nullable disable",
      "",
      "namespace TestNamespace {",
      "}",
    ].join("\n");

    const result = reorderFileHeader(input);

    const lines = result.split("\n");
    expect(lines[0]).toBe("// <auto-generated/>");
    expect(lines[1]).toBe("");
    expect(lines[2]).toBe("#nullable disable");
    expect(lines[3]).toBe("");
    expect(lines[4]).toBe("using System;");
    expect(lines[5]).toBe("using System.Collections.Generic;");
    expect(lines[6]).toBe("");
    expect(lines[7]).toBe("namespace TestNamespace {");
  });

  /**
   * When a license header is present, it should also be moved before usings.
   * The full header block includes copyright, license, auto-generated, and
   * nullable disable lines.
   */
  it("moves full license header before usings", () => {
    const input = [
      "using System;",
      "",
      "// Copyright (c) Microsoft. All rights reserved.",
      "// Licensed under the MIT License.",
      "",
      "// <auto-generated/>",
      "",
      "#nullable disable",
      "",
      "namespace TestNamespace {",
      "}",
    ].join("\n");

    const result = reorderFileHeader(input);

    const lines = result.split("\n");
    expect(lines[0]).toBe("// Copyright (c) Microsoft. All rights reserved.");
    expect(lines[1]).toBe("// Licensed under the MIT License.");
    expect(lines[2]).toBe("");
    expect(lines[3]).toBe("// <auto-generated/>");
    expect(lines[4]).toBe("");
    expect(lines[5]).toBe("#nullable disable");
    expect(lines[6]).toBe("");
    expect(lines[7]).toBe("using System;");
  });

  /**
   * When the header is already before usings (e.g., files with explicit string
   * usings from ExtensibleEnumFile), the function should not modify the content.
   * This ensures we don't break files that already have the correct ordering.
   */
  it("does not modify content when header is already first", () => {
    const input = [
      "// <auto-generated/>",
      "",
      "#nullable disable",
      "",
      "using System;",
      "using System.ComponentModel;",
      "",
      "namespace Type.Enum.Extensible {",
      "}",
    ].join("\n");

    const result = reorderFileHeader(input);
    expect(result).toBe(input);
  });

  /**
   * Files without usings (e.g., infrastructure files that don't reference
   * types via refkeys) should be left unchanged.
   */
  it("does not modify content when there are no usings", () => {
    const input = [
      "// <auto-generated/>",
      "",
      "#nullable disable",
      "",
      "namespace TestNamespace {",
      "}",
    ].join("\n");

    const result = reorderFileHeader(input);
    expect(result).toBe(input);
  });

  /**
   * Non-C# files or files without headers should be left unchanged.
   */
  it("does not modify content without a header block", () => {
    const input = [
      "using System;",
      "",
      "namespace TestNamespace {",
      "}",
    ].join("\n");

    const result = reorderFileHeader(input);
    expect(result).toBe(input);
  });
});

describe("emitter header ordering", () => {
  /**
   * Integration test: verifies that the full emitter pipeline produces files
   * with the header before usings. This tests the entire chain:
   * TypeSpec → TCGC → JSX rendering → reorderFileHeader → output.
   *
   * Without this fix, auto-detected usings from Alloy's SourceFile scope
   * would appear before the auto-generated header in files like ModelFile
   * that use refkeys (which trigger auto-using detection).
   */
  it("places header before usings in model files", async () => {
    const [{ outputs }] = await HttpTester.compileAndDiagnose(`
      using TypeSpec.Http;
      @service
      namespace TestNamespace;
      model Widget { name: string; id: int32; }
      @route("/test")
      op test(): Widget;
    `);

    const modelKey = Object.keys(outputs).find(
      (k) => k.includes("Widget.cs") && !k.includes("Serialization"),
    );
    expect(modelKey).toBeDefined();

    const content = outputs[modelKey!];
    const lines = content.split("\n");

    // Header must be the very first line
    expect(lines[0]).toBe("// <auto-generated/>");

    // #nullable disable must come after auto-generated
    const nullableIdx = lines.indexOf("#nullable disable");
    expect(nullableIdx).toBeGreaterThan(0);

    // First using must come after #nullable disable
    const firstUsingIdx = lines.findIndex((l) => l.startsWith("using "));
    expect(firstUsingIdx).toBeGreaterThan(nullableIdx);

    // namespace must come after usings
    const nsIdx = lines.findIndex((l) => l.startsWith("namespace "));
    expect(nsIdx).toBeGreaterThan(firstUsingIdx);
  });

  /**
   * Verifies header ordering in serialization files, which are generated
   * by ModelSerializationFile and also use auto-detected usings.
   */
  it("places header before usings in serialization files", async () => {
    const [{ outputs }] = await HttpTester.compileAndDiagnose(`
      using TypeSpec.Http;
      @service
      namespace TestNamespace;
      model Widget { name: string; id: int32; }
      @route("/test")
      op test(): Widget;
    `);

    const serKey = Object.keys(outputs).find((k) =>
      k.includes("Widget.Serialization.cs"),
    );
    expect(serKey).toBeDefined();

    const content = outputs[serKey!];
    const headerIdx = content.indexOf("// <auto-generated/>");
    const usingIdx = content.indexOf("using ");
    expect(headerIdx).toBeLessThan(usingIdx);
  });

  /**
   * Verifies header ordering in client files, which reference many types
   * and generate numerous auto-detected usings.
   */
  it("places header before usings in client files", async () => {
    const [{ outputs }] = await HttpTester.compileAndDiagnose(`
      using TypeSpec.Http;
      @service
      namespace TestNamespace;
      model Widget { name: string; id: int32; }
      @route("/test")
      op test(): Widget;
    `);

    const clientKey = Object.keys(outputs).find(
      (k) => k.includes("TestNamespaceClient.cs") && !k.includes("RestClient"),
    );
    expect(clientKey).toBeDefined();

    const content = outputs[clientKey!];
    const headerIdx = content.indexOf("// <auto-generated/>");
    const usingIdx = content.indexOf("using ");

    // Only check ordering if both header and usings exist
    if (headerIdx >= 0 && usingIdx >= 0) {
      expect(headerIdx).toBeLessThan(usingIdx);
    }
  });
});
