/**
 * Prints Spector scenario coverage from the e2e coverage file.
 *
 * Usage: npx tsx eng/scripts/check-coverage.ts [--verbose]
 *
 * The coverage file is generated by `pnpm test:e2e`.
 */
import { readFileSync } from "node:fs";
import { resolve } from "node:path";

const COVERAGE_FILE = resolve(
  import.meta.dirname,
  "../../temp/spector-coverage.json",
);

const verbose = process.argv.includes("--verbose");

interface CoverageEntry {
  scenariosMetadata: { packageName: string; version: string; commit: string };
  results: Record<string, string>;
}

let data: CoverageEntry[];
try {
  data = JSON.parse(readFileSync(COVERAGE_FILE, "utf-8"));
} catch {
  console.error(
    `Coverage file not found: ${COVERAGE_FILE}\nRun 'pnpm test:e2e' first to generate it.`,
  );
  process.exit(1);
}

let grandTotal = 0;
let grandPassed = 0;

for (const entry of data) {
  const pkg = entry.scenariosMetadata.packageName;
  const results = entry.results;
  const total = Object.keys(results).length;
  const passed = Object.values(results).filter((v) => v === "pass").length;
  const failed = Object.values(results).filter((v) => v === "fail").length;
  const notImpl = total - passed - failed;
  const pct = total > 0 ? ((passed / total) * 100).toFixed(1) : "0.0";

  grandTotal += total;
  grandPassed += passed;

  console.log(`\n📦 ${pkg}`);
  console.log(`   ✅ Passed:          ${passed}/${total} (${pct}%)`);
  if (failed > 0) console.log(`   ❌ Failed:          ${failed}`);
  console.log(`   ⬜ Not implemented: ${notImpl}`);

  if (verbose) {
    const sorted = Object.entries(results).sort(([a], [b]) =>
      a.localeCompare(b),
    );
    for (const [name, status] of sorted) {
      const icon = status === "pass" ? "✅" : status === "fail" ? "❌" : "  ";
      if (status !== "not-implemented" || verbose) {
        console.log(`      ${icon} ${name}`);
      }
    }
  }
}

const grandPct =
  grandTotal > 0 ? ((grandPassed / grandTotal) * 100).toFixed(1) : "0.0";
console.log(`\n══════════════════════════════════════════════`);
console.log(
  `📊 Overall: ${grandPassed}/${grandTotal} scenarios covered (${grandPct}%)`,
);
console.log(`══════════════════════════════════════════════\n`);
