import {
  ClassDeclaration,
  Namespace,
  SourceFile,
  useCSharpNamePolicy,
} from "@alloy-js/csharp";
import { type Children, code, namekey } from "@alloy-js/core";
import type { SdkModelType } from "@azure-tools/typespec-client-generator-core";
import { SystemClientModelPrimitives } from "../../builtins/system-client-model.js";
import type { ResolvedCSharpEmitterOptions } from "../../options.js";
import { getLicenseHeader } from "../../utils/header.js";
import { efCsharpRefkey } from "../../utils/refkey.js";
import { isModelAbstract } from "../models/ModelConstructors.js";

/**
 * Props for the {@link ModelSerializationFile} component.
 */
export interface ModelSerializationFileProps {
  /** The TCGC SDK model type representing a TypeSpec model. */
  type: SdkModelType;
  /** Resolved emitter options used for generating the file header. */
  options: ResolvedCSharpEmitterOptions;
  /** Optional children rendered inside the class body (e.g., serialization methods). */
  children?: Children;
}

/**
 * Generates a C# `.Serialization.cs` partial class file that implements `IJsonModel<T>`.
 *
 * This component produces the serialization file skeleton for a model: the license
 * header, namespace, and a `partial class` declaration that implements the
 * `IJsonModel<T>` interface from System.ClientModel.Primitives. Since `IJsonModel<T>`
 * inherits from `IPersistableModel<T>`, the model implicitly implements both interfaces.
 *
 * The file is generated at `src/Generated/Models/{ModelName}.Serialization.cs`,
 * matching the legacy emitter's golden file format.
 *
 * For derived models, the class re-declares the base type to match C# partial class
 * requirements (e.g., `public partial class Dog : Pet, IJsonModel<Dog>`).
 *
 * Child components can render serialization methods (JsonModelWriteCore,
 * PersistableModelWriteCore, Deserialize, etc.) inside the class body — those
 * are handled by subsequent tasks (2.1.3–2.3.14).
 *
 * @example Generated output for a simple model:
 * ```csharp
 * // <auto-generated/>
 *
 * #nullable disable
 *
 * using System.ClientModel.Primitives;
 *
 * namespace TestNamespace.Models
 * {
 *     public partial class Widget : IJsonModel<Widget>
 *     {
 *     }
 * }
 * ```
 */
export function ModelSerializationFile(props: ModelSerializationFileProps) {
  const header = getLicenseHeader(props.options);
  const namePolicy = useCSharpNamePolicy();
  const modelName = namePolicy.getName(props.type.name, "class");
  const isPublic = props.type.access === "public";
  const isAbstract = isModelAbstract(props.type);

  // Use namekey with ignoreNameConflict to prevent Alloy's symbol deduplication.
  // The main model file (ModelFile.tsx) already declares a ClassDeclaration with
  // the same name in the same namespace — without this flag, Alloy would rename
  // the second declaration with a "_2" suffix.
  const partialName = namekey(modelName, { ignoreNameConflict: true });

  return (
    <SourceFile path={`src/Generated/Models/${modelName}.Serialization.cs`}>
      {header}
      {"\n\n"}
      <Namespace name={props.type.namespace}>
        <ClassDeclaration
          public={isPublic}
          internal={!isPublic}
          abstract={isAbstract}
          partial
          name={partialName as unknown as string}
          baseType={
            props.type.baseModel
              ? efCsharpRefkey(props.type.baseModel.__raw!)
              : undefined
          }
          interfaceTypes={[
            code`${SystemClientModelPrimitives.IJsonModel}<${modelName}>`,
          ]}
        >
          {props.children}
        </ClassDeclaration>
      </Namespace>
    </SourceFile>
  );
}
