import {
  Attribute,
  ClassDeclaration,
  Namespace,
  SourceFile,
  useCSharpNamePolicy,
} from "@alloy-js/csharp";
import { type Children, code, namekey } from "@alloy-js/core";
import {
  type SdkModelType,
  UsageFlags,
} from "@azure-tools/typespec-client-generator-core";
import { SystemClientModelPrimitives } from "../../builtins/system-client-model.js";
import {
  getCustomNamespace,
  useCustomCode,
} from "../../contexts/custom-code-context.js";
import type { ResolvedCSharpEmitterOptions } from "../../options.js";
import { getLicenseHeader } from "../../utils/header.js";
import { efCsharpRefkey, unknownModelRefkey } from "../../utils/refkey.js";
import { isModelAbstract } from "../models/ModelConstructors.js";
import { isDynamicModel } from "../models/DynamicModel.js";

/**
 * Props for the {@link ModelSerializationFile} component.
 */
export interface ModelSerializationFileProps {
  /** The TCGC SDK model type representing a TypeSpec model. */
  type: SdkModelType;
  /** Resolved emitter options used for generating the file header. */
  options: ResolvedCSharpEmitterOptions;
  /** Optional children rendered inside the class body (e.g., serialization methods). */
  children?: Children;
}

/**
 * Determines which serialization interfaces a model should implement based on
 * its TCGC usage flags.
 *
 * The logic mirrors the legacy emitter's `MrwSerializationTypeDefinition.BuildImplements()`:
 * - Models with JSON usage implement `IJsonModel<T>` (which inherits `IPersistableModel<T>`,
 *   so both interfaces are satisfied).
 * - Models with only XML usage implement `IPersistableModel<T>` directly (JSON methods
 *   are not needed).
 *
 * @param type - The TCGC SDK model type.
 * @param modelName - The C# class name (used as the generic type argument `T`).
 * @returns An array of Alloy `code` expressions for the `interfaceTypes` prop.
 */
export function getSerializationInterfaces(
  type: SdkModelType,
  modelName: string,
): Children[] {
  const supportsJson = (type.usage & UsageFlags.Json) !== 0;
  const supportsXml = (type.usage & UsageFlags.Xml) !== 0;

  if (supportsJson) {
    return [code`${SystemClientModelPrimitives.IJsonModel}<${modelName}>`];
  } else if (supportsXml) {
    return [
      code`${SystemClientModelPrimitives.IPersistableModel}<${modelName}>`,
    ];
  }

  // Fallback: models with no serialization format still default to IJsonModel<T>
  // to match the legacy emitter behavior where all emitted models are serializable.
  return [code`${SystemClientModelPrimitives.IJsonModel}<${modelName}>`];
}

/**
 * Generates a C# `.Serialization.cs` partial class file that implements the
 * appropriate serialization interface (`IJsonModel<T>` or `IPersistableModel<T>`).
 *
 * This component produces the serialization file skeleton for a model: the license
 * header, namespace, and a `partial class` declaration with the correct serialization
 * interface. Interface selection is based on the model's TCGC usage flags:
 * - JSON models implement `IJsonModel<T>` (which inherits `IPersistableModel<T>`).
 * - XML-only models implement `IPersistableModel<T>` directly.
 *
 * The file is generated at `src/Generated/Models/{ModelName}.Serialization.cs`,
 * matching the legacy emitter's golden file format.
 *
 * For derived models, the class re-declares the base type to match C# partial class
 * requirements (e.g., `public partial class Dog : Pet, IJsonModel<Dog>`).
 *
 * Child components can render serialization methods (JsonModelWriteCore,
 * PersistableModelWriteCore, Deserialize, etc.) inside the class body — those
 * are handled by subsequent tasks (2.1.3–2.3.14).
 *
 * @example Generated output for a JSON model:
 * ```csharp
 * // <auto-generated/>
 *
 * #nullable disable
 *
 * using System.ClientModel.Primitives;
 *
 * namespace TestNamespace.Models
 * {
 *     public partial class Widget : IJsonModel<Widget>
 *     {
 *     }
 * }
 * ```
 *
 * @example Generated output for an XML-only model:
 * ```csharp
 * // <auto-generated/>
 *
 * #nullable disable
 *
 * using System.ClientModel.Primitives;
 *
 * namespace TestNamespace.Models
 * {
 *     public partial class Widget : IPersistableModel<Widget>
 *     {
 *     }
 * }
 * ```
 */
export function ModelSerializationFile(props: ModelSerializationFileProps) {
  const header = getLicenseHeader(props.options);
  const namePolicy = useCSharpNamePolicy();
  const modelName = namePolicy.getName(props.type.name, "class");
  const isPublic = props.type.access === "public";
  const isAbstract = isModelAbstract(props.type);

  // Use namekey with ignoreNameConflict to prevent Alloy's symbol deduplication.
  // The main model file (ModelFile.tsx) already declares a ClassDeclaration with
  // the same name in the same namespace — without this flag, Alloy would rename
  // the second declaration with a "_2" suffix.
  const partialName = namekey(modelName, { ignoreNameConflict: true });

  // When custom code declares a partial class in a different namespace
  // (e.g., [CodeGenType("Friend")] in SampleTypeSpec.Models.Custom),
  // the serialization file must match the model file's namespace.
  const customCode = useCustomCode();
  const effectiveNamespace =
    getCustomNamespace(customCode, modelName) ?? props.type.namespace;

  // Dynamic models (JSON Merge Patch) need System.Text for Encoding.UTF8.GetBytes()
  // used in per-key dictionary patch checks.
  const additionalUsings = isDynamicModel(props.type)
    ? ["System.Text"]
    : undefined;

  // Abstract base models with discriminated subtypes need the PersistableModelProxy
  // attribute to tell the framework which concrete type to instantiate when the
  // discriminator value is unrecognized during deserialization.
  const attributes = isAbstract
    ? [
        <Attribute
          name={SystemClientModelPrimitives.PersistableModelProxyAttribute}
          args={[code`typeof(${unknownModelRefkey(props.type.__raw!)})`]}
        />,
      ]
    : undefined;

  return (
    <SourceFile
      path={`src/Generated/Models/${modelName}.Serialization.cs`}
      using={additionalUsings}
    >
      {header}
      {"\n\n"}
      <Namespace name={effectiveNamespace}>
        <ClassDeclaration
          public={isPublic}
          internal={!isPublic}
          abstract={isAbstract}
          partial
          name={partialName as unknown as string}
          baseType={
            props.type.baseModel
              ? efCsharpRefkey(props.type.baseModel.__raw!)
              : undefined
          }
          interfaceTypes={getSerializationInterfaces(props.type, modelName)}
          attributes={attributes}
        >
          {props.children}
        </ClassDeclaration>
      </Namespace>
    </SourceFile>
  );
}
