/**
 * Unknown discriminator model serialization file generation component.
 *
 * For every abstract discriminated base model that has an `Unknown{BaseName}`
 * class (generated by {@link UnknownDiscriminatorModelFile}), this component
 * generates the corresponding `.Serialization.cs` partial class file.
 *
 * The serialization file implements `IJsonModel<BaseType>` on the Unknown
 * variant and provides:
 * - A parameterless deserialization constructor
 * - Override methods for PersistableModelCreateCore, PersistableModelWriteCore,
 *   JsonModelWriteCore, JsonModelCreateCore
 * - Explicit interface implementations for IPersistableModel<BaseType> and
 *   IJsonModel<BaseType>
 * - A static DeserializeUnknown{Base} method with full property deserialization
 *
 * Key differences from regular model serialization:
 * - All interface methods are parameterized by the BASE type (e.g., `IJsonModel<Pet>`),
 *   not the Unknown type itself
 * - PersistableModelCreateCore and JsonModelCreateCore call the BASE type's
 *   Deserialize method (e.g., `DeserializePet`), not the Unknown's
 * - JsonModelWriteCore delegates entirely to `base.JsonModelWriteCore` with no
 *   own property serialization
 * - The DeserializeUnknown{Base} method initializes discriminator variables to
 *   `"unknown"` instead of a specific discriminator value
 *
 * @example Generated output for UnknownPet (Pet extends Animal):
 * ```csharp
 * internal partial class UnknownPet : Pet, IJsonModel<Pet>
 * {
 *     internal UnknownPet() { }
 *
 *     protected override Animal PersistableModelCreateCore(BinaryData data, ModelReaderWriterOptions options) { ... }
 *     protected override BinaryData PersistableModelWriteCore(ModelReaderWriterOptions options) { ... }
 *     BinaryData IPersistableModel<Pet>.Write(ModelReaderWriterOptions options) => PersistableModelWriteCore(options);
 *     Pet IPersistableModel<Pet>.Create(BinaryData data, ModelReaderWriterOptions options) => (UnknownPet)PersistableModelCreateCore(data, options);
 *     string IPersistableModel<Pet>.GetFormatFromOptions(ModelReaderWriterOptions options) => "J";
 *     void IJsonModel<Pet>.Write(Utf8JsonWriter writer, ModelReaderWriterOptions options) { ... }
 *     protected override void JsonModelWriteCore(Utf8JsonWriter writer, ModelReaderWriterOptions options) { ... }
 *     Pet IJsonModel<Pet>.Create(ref Utf8JsonReader reader, ModelReaderWriterOptions options) => (UnknownPet)JsonModelCreateCore(ref reader, options);
 *     protected override Animal JsonModelCreateCore(ref Utf8JsonReader reader, ModelReaderWriterOptions options) { ... }
 *     internal static UnknownPet DeserializeUnknownPet(JsonElement element, ModelReaderWriterOptions options) { ... }
 * }
 * ```
 *
 * @module
 */

import {
  ClassDeclaration,
  Namespace,
  SourceFile,
  useCSharpNamePolicy,
} from "@alloy-js/csharp";
import { type Children, code, namekey } from "@alloy-js/core";
import {
  type SdkModelType,
  UsageFlags,
} from "@azure-tools/typespec-client-generator-core";
import { System } from "../../builtins/system.js";
import { SystemClientModelPrimitives } from "../../builtins/system-client-model.js";
import { SystemTextJson } from "../../builtins/system-text-json.js";
import type { ResolvedCSharpEmitterOptions } from "../../options.js";
import { getLicenseHeader } from "../../utils/header.js";
import {
  efCsharpRefkey,
  modelReaderWriterContextRefkey,
} from "../../utils/refkey.js";
import { ADDITIONAL_BINARY_DATA_PROPS_PARAM_NAME } from "../models/ModelConstructors.js";
import {
  ADDITIONAL_PROPERTIES_PARAM_NAME,
  renderAdditionalPropertiesValueType,
} from "../../utils/additional-properties.js";
import { getRootModelType } from "./PersistableModelCreateCore.js";
import { AdditionalBinaryDataRead } from "./AdditionalBinaryDataRead.js";
import { AdditionalPropertiesRead } from "./AdditionalPropertiesRead.js";
import {
  hasInheritedAdditionalProperties,
  getAdditionalPropertiesDefiningModel,
} from "../../utils/additional-properties.js";
import { PropertyMatchingLoop } from "./PropertyMatchingLoop.js";
import { computeVariableInfos } from "./DeserializeVariableDeclarations.js";
import { TypeExpression } from "@typespec/emitter-framework/csharp";
import { SystemCollectionsGeneric } from "../../builtins/system-collections-generic.js";
import {
  isPropertyNullable,
  unwrapNullableType,
} from "../../utils/nullable.js";
import { resolvePropertyName } from "../../utils/property.js";

/**
 * Props for the {@link UnknownDiscriminatorModelSerializationFile} component.
 */
export interface UnknownDiscriminatorModelSerializationFileProps {
  /** The abstract base model of the discriminated hierarchy. */
  type: SdkModelType;
  /** Resolved emitter options for the file header. */
  options: ResolvedCSharpEmitterOptions;
}

/**
 * Generates a C# `.Serialization.cs` partial class file for the Unknown
 * discriminator variant of an abstract base model.
 *
 * @param props - Component props containing the abstract base model type.
 */
export function UnknownDiscriminatorModelSerializationFile(
  props: UnknownDiscriminatorModelSerializationFileProps,
) {
  const header = getLicenseHeader(props.options);
  const namePolicy = useCSharpNamePolicy();
  const baseModel = props.type;
  const baseName = namePolicy.getName(baseModel.name, "class");
  const unknownName = `Unknown${baseName}`;
  const rootModel = getRootModelType(baseModel);
  const rootName = namePolicy.getName(rootModel.name, "class");

  // Determine if base model is the root of the hierarchy.
  // When the base IS the root, PersistableModelCreateCore/JsonModelCreateCore
  // return the base type directly. When the base is intermediate, they return
  // the root type, and explicit interface Create methods need a cast.
  const isRoot = baseModel.baseModel === undefined;
  const needsCast = !isRoot;

  const supportsJson = (baseModel.usage & UsageFlags.Json) !== 0;

  // Use namekey with ignoreNameConflict since the main Unknown model file
  // already declares a ClassDeclaration with the same name.
  const partialName = namekey(unknownName, { ignoreNameConflict: true });

  // Build interface types for the class declaration
  const interfaceTypes = supportsJson
    ? [code`${SystemClientModelPrimitives.IJsonModel}<${baseName}>`]
    : [code`${SystemClientModelPrimitives.IPersistableModel}<${baseName}>`];

  // Cast expression for explicit interface Create methods
  const persistableCreateExpr = needsCast
    ? `(${unknownName})PersistableModelCreateCore(data, options)`
    : "PersistableModelCreateCore(data, options)";

  const jsonCreateExpr = needsCast
    ? `(${unknownName})JsonModelCreateCore(ref reader, options)`
    : "JsonModelCreateCore(ref reader, options)";

  // XML-only models return "X" format; JSON models (including dual-format) return "J".
  const wireFormat = supportsJson ? "J" : "X";

  // Build all class body children imperatively to avoid Babel plugin crashes
  // with large numbers of conditional children in JSX.
  const classBody: Children[] = [];

  // 1. Deserialization constructor
  classBody.push(
    `/// <summary> Initializes a new instance of <see cref="${unknownName}"/> for deserialization. </summary>`,
    "\n",
    `internal ${unknownName}()`,
    "\n{\n}",
  );

  // 2. PersistableModelCreateCore
  classBody.push(
    "\n\n",
    `/// <param name="data"> The data to parse. </param>`,
    "\n",
    `/// <param name="options"> The client options for reading and writing models. </param>`,
    "\n",
    code`protected override ${rootName} PersistableModelCreateCore(${System.BinaryData} data, ${SystemClientModelPrimitives.ModelReaderWriterOptions} options)`,
    "\n{\n",
    code`    string format = options.Format == "W" ? ((${SystemClientModelPrimitives.IPersistableModel}<${baseName}>)this).GetFormatFromOptions(options) : options.Format;`,
    "\n    switch (format)",
    "\n    {",
  );
  if (supportsJson) {
    classBody.push(
      '\n        case "J":',
      "\n",
      code`            using (${SystemTextJson.JsonDocument} document = ${SystemTextJson.JsonDocument}.Parse(data))`,
      "\n            {",
      `\n                return Deserialize${baseName}(document.RootElement, options);`,
      "\n            }",
    );
  }
  classBody.push(
    "\n        default:",
    "\n",
    code`            throw new ${System.FormatException}($"The model {nameof(${baseName})} does not support reading '{options.Format}' format.");`,
    "\n    }",
    "\n}",
  );

  // 3. PersistableModelWriteCore
  classBody.push(
    "\n\n",
    `/// <param name="options"> The client options for reading and writing models. </param>`,
    "\n",
    code`protected override ${System.BinaryData} PersistableModelWriteCore(${SystemClientModelPrimitives.ModelReaderWriterOptions} options)`,
    "\n{\n",
    code`    string format = options.Format == "W" ? ((${SystemClientModelPrimitives.IPersistableModel}<${baseName}>)this).GetFormatFromOptions(options) : options.Format;`,
    "\n    switch (format)",
    "\n    {",
  );
  if (supportsJson) {
    classBody.push(
      '\n        case "J":',
      "\n",
      code`            return ${SystemClientModelPrimitives.ModelReaderWriter}.Write(this, options, ${modelReaderWriterContextRefkey()}.Default);`,
    );
  }
  classBody.push(
    "\n        default:",
    "\n",
    code`            throw new ${System.FormatException}($"The model {nameof(${baseName})} does not support writing '{options.Format}' format.");`,
    "\n    }",
    "\n}",
  );

  // 4. IPersistableModel<Base>.Write
  classBody.push(
    "\n\n",
    `/// <param name="options"> The client options for reading and writing models. </param>`,
    "\n",
    code`${System.BinaryData} ${SystemClientModelPrimitives.IPersistableModel}<${baseName}>.Write(${SystemClientModelPrimitives.ModelReaderWriterOptions} options) => PersistableModelWriteCore(options);`,
  );

  // 5. IPersistableModel<Base>.Create
  classBody.push(
    "\n\n",
    `/// <param name="data"> The data to parse. </param>`,
    "\n",
    `/// <param name="options"> The client options for reading and writing models. </param>`,
    "\n",
    code`${baseName} ${SystemClientModelPrimitives.IPersistableModel}<${baseName}>.Create(${System.BinaryData} data, ${SystemClientModelPrimitives.ModelReaderWriterOptions} options) => ${persistableCreateExpr};`,
  );

  // 6. IPersistableModel<Base>.GetFormatFromOptions
  classBody.push(
    "\n\n",
    `/// <param name="options"> The client options for reading and writing models. </param>`,
    "\n",
    code`string ${SystemClientModelPrimitives.IPersistableModel}<${baseName}>.GetFormatFromOptions(${SystemClientModelPrimitives.ModelReaderWriterOptions} options) => "${wireFormat}";`,
  );

  if (supportsJson) {
    // 7. IJsonModel<Base>.Write
    classBody.push(
      "\n\n",
      `/// <param name="writer"> The JSON writer. </param>`,
      "\n",
      `/// <param name="options"> The client options for reading and writing models. </param>`,
      "\n",
      code`void ${SystemClientModelPrimitives.IJsonModel}<${baseName}>.Write(${SystemTextJson.Utf8JsonWriter} writer, ${SystemClientModelPrimitives.ModelReaderWriterOptions} options)`,
      "\n{\n",
      "    writer.WriteStartObject();\n",
      "    JsonModelWriteCore(writer, options);\n",
      "}",
    );

    // 8. JsonModelWriteCore
    classBody.push(
      "\n\n",
      `/// <param name="writer"> The JSON writer. </param>`,
      "\n",
      `/// <param name="options"> The client options for reading and writing models. </param>`,
      "\n",
      code`protected override void JsonModelWriteCore(${SystemTextJson.Utf8JsonWriter} writer, ${SystemClientModelPrimitives.ModelReaderWriterOptions} options)`,
      "\n{\n",
      code`    string format = options.Format == "W" ? ((${SystemClientModelPrimitives.IPersistableModel}<${baseName}>)this).GetFormatFromOptions(options) : options.Format;`,
      '\n    if (format != "J")',
      "\n    {",
      "\n",
      code`        throw new ${System.FormatException}($"The model {nameof(${baseName})} does not support writing '{format}' format.");`,
      "\n    }",
      "\n    base.JsonModelWriteCore(writer, options);",
      "\n}",
    );

    // 9. IJsonModel<Base>.Create
    classBody.push(
      "\n\n",
      `/// <param name="reader"> The JSON reader. </param>`,
      "\n",
      `/// <param name="options"> The client options for reading and writing models. </param>`,
      "\n",
      code`${baseName} ${SystemClientModelPrimitives.IJsonModel}<${baseName}>.Create(ref ${SystemTextJson.Utf8JsonReader} reader, ${SystemClientModelPrimitives.ModelReaderWriterOptions} options) => ${jsonCreateExpr};`,
    );

    // 10. JsonModelCreateCore
    classBody.push(
      "\n\n",
      `/// <param name="reader"> The JSON reader. </param>`,
      "\n",
      `/// <param name="options"> The client options for reading and writing models. </param>`,
      "\n",
      code`protected override ${rootName} JsonModelCreateCore(ref ${SystemTextJson.Utf8JsonReader} reader, ${SystemClientModelPrimitives.ModelReaderWriterOptions} options)`,
      "\n{\n",
      code`    string format = options.Format == "W" ? ((${SystemClientModelPrimitives.IPersistableModel}<${baseName}>)this).GetFormatFromOptions(options) : options.Format;`,
      '\n    if (format != "J")',
      "\n    {",
      "\n",
      code`        throw new ${System.FormatException}($"The model {nameof(${baseName})} does not support reading '{format}' format.");`,
      "\n    }",
      "\n",
      code`    using ${SystemTextJson.JsonDocument} document = ${SystemTextJson.JsonDocument}.ParseValue(ref reader);`,
      `\n    return Deserialize${baseName}(document.RootElement, options);`,
      "\n}",
    );
  }

  // 11. DeserializeUnknownXxx — compute variable infos and return statement
  let deserializeReturnStmt: string | undefined;
  if (supportsJson) {
    const variableInfos = computeVariableInfos(baseModel);
    const returnArgs = variableInfos.map((info) => {
      if (info.kind === "additional-binary-data") {
        return ADDITIONAL_BINARY_DATA_PROPS_PARAM_NAME;
      }
      if (info.kind === "additional-properties") {
        return "additionalProperties";
      }
      if (info.kind === "patch") {
        return "patch";
      }
      return namePolicy.getName(
        resolvePropertyName(info.property.name, info.modelName),
        "parameter",
      );
    });
    deserializeReturnStmt = `\n    return new ${unknownName}(${returnArgs.join(", ")});`;
  }

  return (
    <SourceFile path={`src/Generated/Models/${unknownName}.Serialization.cs`}>
      {header}
      {"\n\n"}
      <Namespace name={baseModel.namespace}>
        <ClassDeclaration
          internal
          partial
          name={partialName as unknown as string}
          baseType={efCsharpRefkey(baseModel.__raw!)}
          interfaceTypes={interfaceTypes}
        >
          {classBody}
          {supportsJson && "\n\n"}
          {supportsJson &&
            `/// <param name="element"> The JSON element to deserialize. </param>`}
          {supportsJson && "\n"}
          {supportsJson &&
            `/// <param name="options"> The client options for reading and writing models. </param>`}
          {supportsJson && "\n"}
          {supportsJson &&
            code`internal static ${unknownName} Deserialize${unknownName}(${SystemTextJson.JsonElement} element, ${SystemClientModelPrimitives.ModelReaderWriterOptions} options)`}
          {supportsJson && "\n{"}
          {supportsJson && "\n    if (element.ValueKind == JsonValueKind.Null)"}
          {supportsJson && "\n    {"}
          {supportsJson && "\n        return null;"}
          {supportsJson && "\n    }"}
          {supportsJson && <UnknownDeserializeVariables type={baseModel} />}
          {supportsJson && (
            <PropertyMatchingLoop type={baseModel}>
              {hasInheritedAdditionalProperties(baseModel) ? (
                <AdditionalPropertiesRead
                  type={getAdditionalPropertiesDefiningModel(baseModel)!}
                />
              ) : (
                <AdditionalBinaryDataRead />
              )}
            </PropertyMatchingLoop>
          )}
          {supportsJson && deserializeReturnStmt}
          {supportsJson && "\n}"}
        </ClassDeclaration>
      </Namespace>
    </SourceFile>
  );
}

/**
 * Renders variable declarations for the Unknown model's DeserializeUnknownXxx
 * method. Discriminator properties are initialized to `"unknown"` instead of
 * a specific value.
 */
function UnknownDeserializeVariables(props: { type: SdkModelType }) {
  const namePolicy = useCSharpNamePolicy();
  const variableInfos = computeVariableInfos(props.type);

  // Filter out "patch" items first so the map never returns null
  // (which crashes the Babel JSX plugin)
  const filteredInfos = variableInfos.filter((info) => info.kind !== "patch");

  return (
    <>
      {filteredInfos.map((info) => {
        if (info.kind === "additional-binary-data") {
          return (
            <>
              {"\n    "}
              {code`${SystemCollectionsGeneric.IDictionary}<string, ${System.BinaryData}> ${ADDITIONAL_BINARY_DATA_PROPS_PARAM_NAME} = new ChangeTrackingDictionary<string, ${System.BinaryData}>();`}
            </>
          );
        }

        if (info.kind === "additional-properties") {
          const valueTypeExpr = renderAdditionalPropertiesValueType(
            info.model.additionalProperties!,
          );
          return (
            <>
              {"\n    "}
              {code`${SystemCollectionsGeneric.IDictionary}<string, ${valueTypeExpr}> ${ADDITIONAL_PROPERTIES_PARAM_NAME} = new ${SystemCollectionsGeneric.Dictionary}<string, ${valueTypeExpr}>();`}
            </>
          );
        }

        const p = info.property;
        const varName = namePolicy.getName(
          resolvePropertyName(p.name, info.modelName),
          "parameter",
        );
        const nullable = isPropertyNullable(p);
        const unwrapped = unwrapNullableType(p.type);
        const isDiscriminator = p.discriminator === true;
        const isStringDiscriminator =
          isDiscriminator && unwrapped.kind === "string";
        const initializer = isStringDiscriminator ? '"unknown"' : "default";

        return (
          <>
            {"\n    "}
            <TypeExpression type={unwrapped.__raw!} />
            {nullable ? "?" : ""}
            {` ${varName} = ${initializer};`}
          </>
        );
      })}
    </>
  );
}
