import {
  EnumDeclaration,
  EnumMember,
  Namespace,
  SourceFile,
  useCSharpNamePolicy,
} from "@alloy-js/csharp";
import { For, refkey } from "@alloy-js/core";
import {
  isSdkIntKind,
  type SdkEnumType,
  type SdkEnumValueType,
} from "@azure-tools/typespec-client-generator-core";
import type { ResolvedCSharpEmitterOptions } from "../../options.js";
import { getLicenseHeader } from "../../utils/header.js";

/**
 * Props for the {@link FixedEnumFile} component.
 */
export interface FixedEnumFileProps {
  /** The TCGC SDK enum type representing a non-extensible (fixed) enum. */
  type: SdkEnumType;
  /** Resolved emitter options used for generating the file header. */
  options: ResolvedCSharpEmitterOptions;
}

/**
 * Returns the XML doc description for an enum member.
 *
 * Uses the TCGC summary or doc string when available, falling back to
 * the member name followed by a period — matching the legacy C# generator's
 * `DocHelpers.GetFormattableDescription()` behavior.
 *
 * @param member - The TCGC enum value type to extract documentation from.
 * @returns A description string suitable for use in a `<summary>` XML doc tag.
 */
function getEnumMemberDescription(member: SdkEnumValueType): string {
  return member.summary ?? member.doc ?? `${member.name}.`;
}

/**
 * Determines whether a fixed enum is backed by an integer type.
 *
 * Only int-backed fixed enums include explicit initialization values in the
 * generated C# enum (e.g., `One = 1`). String-backed and float-backed enums
 * omit values because C# enums cannot hold string or float constants —
 * serialization is handled by separate extension methods instead.
 *
 * @param sdkEnum - The TCGC enum type to inspect.
 * @returns `true` if the enum's underlying value type is an integer kind.
 */
function isIntValueType(sdkEnum: SdkEnumType): boolean {
  return isSdkIntKind(sdkEnum.valueType.kind);
}

/**
 * Generates a C# source file containing a fixed (non-extensible) enum declaration.
 *
 * Fixed enums map to standard C# `enum` types. Int-backed enums include explicit
 * integer initialization values (e.g., `One = 1`). String-backed and float-backed
 * enums omit values — serialization is handled by extension methods in a separate
 * serialization file.
 *
 * The generated file includes the standard license header, namespace declaration,
 * and XML documentation comments for each enum member.
 *
 * @example Generated output for a string-backed enum:
 * ```csharp
 * // <auto-generated/>
 *
 * #nullable disable
 *
 * namespace MyNamespace
 * {
 *     public enum DaysOfWeek
 *     {
 *         /// <summary> Monday. </summary>
 *         Monday,
 *         /// <summary> Tuesday. </summary>
 *         Tuesday
 *     }
 * }
 * ```
 *
 * @example Generated output for an int-backed enum:
 * ```csharp
 * public enum Priority
 * {
 *     /// <summary> Low. </summary>
 *     Low = 0,
 *     /// <summary> High. </summary>
 *     High = 1
 * }
 * ```
 */
export function FixedEnumFile(props: FixedEnumFileProps) {
  const header = getLicenseHeader(props.options);
  const namePolicy = useCSharpNamePolicy();
  const enumName = namePolicy.getName(props.type.name, "enum");
  const hasIntValues = isIntValueType(props.type);

  return (
    <SourceFile path={`src/Generated/Models/${enumName}.cs`}>
      {header}
      {"\n\n"}
      <Namespace name={props.type.namespace}>
        <EnumDeclaration public name={enumName} refkey={refkey(props.type)}>
          <For each={props.type.values} joiner={",\n"}>
            {(member) => {
              const memberName = namePolicy.getName(member.name, "enum-member");
              const description = getEnumMemberDescription(member);
              return (
                <>
                  {`/// <summary> ${description} </summary>`}
                  {"\n"}
                  <EnumMember name={memberName} refkey={refkey(member)} />
                  {hasIntValues ? ` = ${member.value}` : ""}
                </>
              );
            }}
          </For>
        </EnumDeclaration>
      </Namespace>
    </SourceFile>
  );
}
