import {
  EnumDeclaration,
  Namespace,
  SourceFile,
  useCSharpNamePolicy,
} from "@alloy-js/csharp";
import { For, refkey } from "@alloy-js/core";
import {
  isSdkIntKind,
  type SdkEnumType,
  type SdkEnumValueType,
} from "@azure-tools/typespec-client-generator-core";
import type { ResolvedCSharpEmitterOptions } from "../../options.js";
import { ensureTrailingPeriod, formatDocLines } from "../../utils/doc.js";
import { getLicenseHeader } from "../../utils/header.js";
import { declarationRefkeys } from "../../utils/refkey.js";

/**
 * Props for the {@link FixedEnumFile} component.
 */
export interface FixedEnumFileProps {
  /** The TCGC SDK enum type representing a non-extensible (fixed) enum. */
  type: SdkEnumType;
  /** Resolved emitter options used for generating the file header. */
  options: ResolvedCSharpEmitterOptions;
}

/**
 * Converts a TCGC enum member name to a valid C# identifier.
 *
 * Matches the legacy emitter's `ToIdentifierName()` behavior from StringExtensions.cs:
 * - If the raw name starts with a digit, strip all non-alphanumeric characters
 *   (e.g., the decimal point in `"1.25"`) and prefix with `_`.
 *   Examples: `"1.25"` → `"_125"`, `"2.375"` → `"_2375"`, `"1"` → `"_1"`.
 * - Otherwise, delegate to the C# naming policy for normal PascalCase conversion.
 *
 * This is needed because TCGC preserves numeric literal union values verbatim
 * (e.g., `1.25`, `2.375`) as enum member names, which are invalid C# identifiers.
 * The `pascalCase` transform from `change-case` incorrectly produces `"1_25"`
 * instead of `"_125"` for these inputs.
 *
 * @param rawName - The raw member name from TCGC (e.g., `"1.25"`, `"Hello"`).
 * @param namePolicy - The active C# name policy for delegating normal names.
 * @returns A valid C# identifier for the enum member.
 */
export function fixedEnumMemberName(
  rawName: string,
  namePolicy: ReturnType<typeof useCSharpNamePolicy>,
): string {
  if (/^\d/.test(rawName)) {
    // Remove all non-alphanumeric characters (e.g., decimal points) and prefix with '_'
    return `_${rawName.replace(/[^a-zA-Z0-9]/g, "")}`;
  }
  return namePolicy.getName(rawName, "enum-member");
}

/**
 * Returns the XML doc description for an enum member.
 *
 * Uses the TCGC summary or doc string when available, falling back to
 * the member name followed by a period — matching the legacy C# generator's
 * `DocHelpers.GetFormattableDescription()` behavior.
 *
 * @param member - The TCGC enum value type to extract documentation from.
 * @returns A description string suitable for use in a `<summary>` XML doc tag.
 */
function getEnumMemberDescription(member: SdkEnumValueType): string {
  return member.summary ?? member.doc ?? `${member.name}.`;
}

/**
 * Returns the XML doc description for a fixed enum type declaration, or
 * `undefined` when the TypeSpec definition has no documentation.
 *
 * Uses the TCGC summary or doc string, applying `ensureTrailingPeriod` to
 * match the legacy emitter's `XmlDocStatement.GetPeriodOrEmpty()` behavior
 * (single-line summaries always end with a period).
 *
 * @param sdkEnum - The TCGC enum type to extract documentation from.
 * @returns A description string with trailing period, or `undefined` if no doc exists.
 */
function getEnumDescription(sdkEnum: SdkEnumType): string | undefined {
  const raw = sdkEnum.summary ?? sdkEnum.doc;
  return raw ? ensureTrailingPeriod(raw) : undefined;
}

/**
 * Determines whether a fixed enum is backed by an integer type.
 *
 * Only int-backed fixed enums include explicit initialization values in the
 * generated C# enum (e.g., `One = 1`). String-backed and float-backed enums
 * omit values because C# enums cannot hold string or float constants —
 * serialization is handled by separate extension methods instead.
 *
 * @param sdkEnum - The TCGC enum type to inspect.
 * @returns `true` if the enum's underlying value type is an integer kind.
 */
function isIntValueType(sdkEnum: SdkEnumType): boolean {
  return isSdkIntKind(sdkEnum.valueType.kind);
}

/**
 * Generates a C# source file containing a fixed (non-extensible) enum declaration.
 *
 * Fixed enums map to standard C# `enum` types. Int-backed enums include explicit
 * integer initialization values (e.g., `One = 1`). String-backed and float-backed
 * enums omit values — serialization is handled by extension methods in a separate
 * serialization file.
 *
 * The generated file includes the standard license header, namespace declaration,
 * and XML documentation comments for each enum member.
 *
 * @example Generated output for a string-backed enum:
 * ```csharp
 * // <auto-generated/>
 *
 * #nullable disable
 *
 * namespace MyNamespace
 * {
 *     public enum DaysOfWeek
 *     {
 *         /// <summary> Monday. </summary>
 *         Monday,
 *         /// <summary> Tuesday. </summary>
 *         Tuesday
 *     }
 * }
 * ```
 *
 * @example Generated output for an int-backed enum:
 * ```csharp
 * public enum Priority
 * {
 *     /// <summary> Low. </summary>
 *     Low = 0,
 *     /// <summary> High. </summary>
 *     High = 1
 * }
 * ```
 */
export function FixedEnumFile(props: FixedEnumFileProps) {
  const header = getLicenseHeader(props.options);
  const namePolicy = useCSharpNamePolicy();
  const enumName = namePolicy.getName(props.type.name, "enum");
  const hasIntValues = isIntValueType(props.type);
  const enumDescription = getEnumDescription(props.type);

  return (
    <SourceFile path={`src/Generated/Models/${enumName}.cs`}>
      {header}
      {"\n\n"}
      <Namespace name={props.type.namespace}>
        {enumDescription
          ? `/// <summary> ${formatDocLines(enumDescription)} </summary>\n`
          : ""}
        <EnumDeclaration
          public
          name={enumName}
          refkey={declarationRefkeys(refkey(props.type), props.type.__raw)}
        >
          <For each={props.type.values} joiner={",\n"}>
            {(member) => {
              const memberName = fixedEnumMemberName(member.name, namePolicy);
              const description = getEnumMemberDescription(member);
              return (
                <>
                  {`/// <summary> ${description} </summary>`}
                  {"\n"}
                  {memberName}
                  {hasIntValues ? ` = ${member.value}` : ""}
                </>
              );
            }}
          </For>
        </EnumDeclaration>
      </Namespace>
    </SourceFile>
  );
}
