import type { ResolvedCSharpEmitterOptions } from "../options.js";

/**
 * Generates the standard C# file header for generated source files.
 *
 * The header includes license comment lines (when configured), the
 * `// <auto-generated/>` marker, and the `#nullable disable` directive.
 * This matches the format produced by the legacy C# generator:
 *
 * ```
 * // Copyright (c) {company}. All rights reserved.
 * // Licensed under the {name}.
 *
 * // <auto-generated/>
 *
 * #nullable disable
 * ```
 *
 * When no license options are provided, only the auto-generated marker and
 * nullable directive are emitted.
 *
 * The returned string is intended for use as the `header` prop on Alloy's
 * `SourceFile` component, which renders it before `using` directives.
 *
 * @param options - Resolved emitter options containing license configuration.
 * @returns The formatted header string with embedded newlines.
 */
export function getLicenseHeader(
  options: ResolvedCSharpEmitterOptions,
): string {
  const lines: string[] = [];

  if (options.license?.header) {
    // The raw header string contains lines without comment prefixes.
    // Split on line endings and prepend "// " to each non-empty line,
    // matching the legacy CodeWriter.ToString behavior.
    const headerLines = options.license.header.split(/\r?\n/);
    for (const line of headerLines) {
      lines.push(line.trim() ? `// ${line}` : "");
    }
  } else if (options.license) {
    // Construct from individual fields when no raw header is provided.
    if (options.license.company) {
      lines.push(
        `// Copyright (c) ${options.license.company}. All rights reserved.`,
      );
    }
    lines.push(`// Licensed under the ${options.license.name}.`);
  }

  // Blank line separator after license comment, if present
  if (lines.length > 0) {
    lines.push("");
  }

  // Auto-generated marker — always present in every generated file
  lines.push("// <auto-generated/>");

  // Blank line before nullable directive
  lines.push("");

  // Nullable disable — required for generated C# code compatibility
  lines.push("#nullable disable");

  return lines.join("\n");
}
