/**
 * Reorders the license/auto-generated header to appear before `using` directives
 * in rendered C# source file content.
 *
 * The Alloy C# `SourceFile` component renders auto-detected `using` directives
 * before children content. Since the license header is placed as children, it ends
 * up after the usings. The golden file format requires the header before usings:
 *
 * ```csharp
 * // Copyright (c) Microsoft. All rights reserved.
 * // Licensed under the MIT License.
 *
 * // <auto-generated/>
 *
 * #nullable disable
 *
 * using System;
 * using System.Collections.Generic;
 *
 * namespace MyService
 * {
 *     ...
 * }
 * ```
 *
 * This function detects when `using` directives precede the header block and
 * reorders them. Files that already have the correct ordering (e.g., those
 * using explicit string usings) are left unchanged.
 *
 * @param content - The rendered C# file content to reorder.
 * @returns The content with header before usings, or unchanged if already correct.
 */
export function reorderFileHeader(content: string): string {
  // Split content into lines for analysis
  const lines = content.split("\n");

  // Find the extent of leading `using` directives (possibly preceded by blank lines)
  let usingBlockStart = -1;
  let usingBlockEnd = -1;
  for (let i = 0; i < lines.length; i++) {
    const trimmed = lines[i].trim();
    if (trimmed.startsWith("using ") && trimmed.endsWith(";")) {
      if (usingBlockStart === -1) usingBlockStart = i;
      usingBlockEnd = i;
    } else if (trimmed === "" && usingBlockStart === -1) {
      // skip leading blank lines
      continue;
    } else if (usingBlockStart !== -1 && trimmed === "") {
      // blank line after usings — end of using block
      break;
    } else {
      // Non-using, non-blank line before any usings means no leading using block
      break;
    }
  }

  // No leading using block — file is already in correct order (or has no usings)
  if (usingBlockStart === -1) {
    return content;
  }

  // Find the header block after the using block.
  // The header starts with `//` (comment) or `#nullable` and ends with `#nullable disable`.
  let headerBlockStart = -1;
  let headerBlockEnd = -1;
  for (let i = usingBlockEnd + 1; i < lines.length; i++) {
    const trimmed = lines[i].trim();
    if (trimmed === "") {
      // Skip blank lines between usings and header
      if (headerBlockStart !== -1) {
        // Blank lines within the header block are part of it
        continue;
      }
      continue;
    }
    if (
      trimmed.startsWith("//") ||
      trimmed.startsWith("#nullable") ||
      trimmed.startsWith("#pragma")
    ) {
      if (headerBlockStart === -1) headerBlockStart = i;
      headerBlockEnd = i;
      // Stop after finding `#nullable disable`
      if (trimmed === "#nullable disable") {
        break;
      }
    } else {
      // Non-header line — stop searching
      break;
    }
  }

  // No header block found after usings — nothing to reorder
  if (headerBlockStart === -1 || headerBlockEnd === -1) {
    return content;
  }

  // Verify the header block contains `#nullable disable` (our end marker)
  const headerLines = lines.slice(headerBlockStart, headerBlockEnd + 1);
  if (!headerLines.some((l) => l.trim() === "#nullable disable")) {
    return content;
  }

  // Extract the blocks
  const beforeUsings = lines.slice(0, usingBlockStart);
  const usingLines = lines.slice(usingBlockStart, usingBlockEnd + 1);
  const afterHeader = lines.slice(headerBlockEnd + 1);

  // Reorder: header first, then blank line, then usings, then rest
  // Include blank lines within the header block (they're part of the format)
  const result = [
    ...beforeUsings,
    ...headerLines,
    "", // blank line between header and usings
    ...usingLines,
    ...afterHeader,
  ];

  return result.join("\n");
}

/**
 * Walks an output directory tree and reorders file headers in all .cs files.
 *
 * @param dir - The output directory tree from Alloy's `renderAsync`.
 */
export function reorderAllFileHeaders(
  dir: import("@alloy-js/core").OutputDirectory,
): void {
  for (const item of dir.contents) {
    if ("contents" in item) {
      if (Array.isArray(item.contents)) {
        // Subdirectory — recurse
        reorderAllFileHeaders(item as import("@alloy-js/core").OutputDirectory);
      } else if (
        typeof item.contents === "string" &&
        item.path.endsWith(".cs")
      ) {
        // C# source file — reorder header
        (item as import("@alloy-js/core").ContentOutputFile).contents =
          reorderFileHeader(item.contents);
      }
    }
  }
}
