import {
  Attribute,
  ClassDeclaration,
  Namespace,
  SourceFile,
  useCSharpNamePolicy,
} from "@alloy-js/csharp";
import { code, type Refkey } from "@alloy-js/core";
import type { SdkModelType } from "@azure-tools/typespec-client-generator-core";
import { SystemClientModelPrimitives } from "../../builtins/system-client-model.js";
import type { ResolvedCSharpEmitterOptions } from "../../options.js";
import { getLicenseHeader } from "../../utils/header.js";
import { efCsharpRefkey, unknownModelRefkey } from "../../utils/refkey.js";
import { hasDiscriminatedSubtypes } from "../models/ModelConstructors.js";

/**
 * Props for the {@link ModelReaderWriterContextFile} component.
 */
export interface ModelReaderWriterContextFileProps {
  /** All models from the SDK package to register as buildable types. */
  models: SdkModelType[];
  /** The resolved package name, used for the context class name and namespace. */
  packageName: string;
  /** Resolved emitter options used for generating the file header. */
  options: ResolvedCSharpEmitterOptions;
}

/**
 * Entry representing a single buildable model type for the context class.
 * Contains the C# type name (for sorting) and the Alloy refkey (for rendering).
 */
interface BuildableEntry {
  /** The simple C# type name used for alphabetical sorting. */
  name: string;
  /** The Alloy refkey for the type declaration, used in typeof() expressions. */
  refkey: Refkey;
}

/**
 * Generates a `{PackageName}Context.cs` file containing a class that inherits
 * from `ModelReaderWriterContext` and registers all serializable model types
 * via `[ModelReaderWriterBuildable(typeof(T))]` attributes.
 *
 * This class is used by System.ClientModel's source generation to discover
 * all model types that support serialization/deserialization at compile time,
 * enabling AOT-compatible model reader/writer operations.
 *
 * The context class name is derived from the package name by removing dots
 * and appending "Context" (e.g., `SampleTypeSpec` → `SampleTypeSpecContext`,
 * `_Type.Model.Usage` → `_TypeModelUsageContext`).
 *
 * Buildable types include:
 * - All models from the SDK package (classes and structs that implement IJsonModel/IPersistableModel)
 * - Unknown discriminator variant classes (e.g., `UnknownAnimal` for abstract `Animal`)
 *
 * Types are sorted alphabetically by simple type name to produce deterministic output,
 * matching the legacy emitter's `ModelReaderWriterContextDefinition.cs` behavior.
 *
 * @example Generated output:
 * ```csharp
 * // <auto-generated/>
 *
 * #nullable disable
 *
 * using System.ClientModel.Primitives;
 *
 * namespace SampleTypeSpec
 * {
 *     [ModelReaderWriterBuildable(typeof(Dog))]
 *     [ModelReaderWriterBuildable(typeof(Pet))]
 *     [ModelReaderWriterBuildable(typeof(UnknownPet))]
 *     public partial class SampleTypeSpecContext : ModelReaderWriterContext
 *     {
 *     }
 * }
 * ```
 */
export function ModelReaderWriterContextFile(
  props: ModelReaderWriterContextFileProps,
) {
  const header = getLicenseHeader(props.options);
  const namePolicy = useCSharpNamePolicy();

  // Context class name: remove dots from package name and append "Context".
  // Matches legacy emitter's RemovePeriods(PrimaryNamespace) + "Context".
  const contextClassName = props.packageName.replace(/\./g, "") + "Context";

  // Collect all buildable model entries: regular models + Unknown discriminator variants.
  const entries: BuildableEntry[] = [];

  for (const model of props.models) {
    const modelName = namePolicy.getName(model.name, "class");
    entries.push({
      name: modelName,
      refkey: efCsharpRefkey(model.__raw!),
    });

    // Abstract base models with discriminated subtypes also generate an
    // Unknown{BaseName} fallback class that needs to be registered.
    if (hasDiscriminatedSubtypes(model)) {
      entries.push({
        name: `Unknown${modelName}`,
        refkey: unknownModelRefkey(model.__raw!),
      });
    }
  }

  // No buildable types means no context file is needed.
  if (entries.length === 0) {
    return false;
  }

  // Sort alphabetically by simple type name for deterministic output.
  entries.sort((a, b) => a.name.localeCompare(b.name));

  // Build [ModelReaderWriterBuildable(typeof(T))] attributes for each entry.
  const attributes = entries.map((entry) => (
    <Attribute
      name={SystemClientModelPrimitives.ModelReaderWriterBuildableAttribute}
      args={[code`typeof(${entry.refkey})`]}
    />
  ));

  return (
    <SourceFile path={`src/Generated/Models/${contextClassName}.cs`}>
      {header}
      {"\n\n"}
      <Namespace name={props.packageName}>
        <ClassDeclaration
          public
          partial
          name={contextClassName}
          baseType={SystemClientModelPrimitives.ModelReaderWriterContext}
          attributes={attributes}
        />
      </Namespace>
    </SourceFile>
  );
}
