import {
  ClassDeclaration,
  Namespace,
  SourceFile,
  useCSharpNamePolicy,
} from "@alloy-js/csharp";
import { type Children, For } from "@alloy-js/core";
import type { SdkModelType } from "@azure-tools/typespec-client-generator-core";
import type { ResolvedCSharpEmitterOptions } from "../../options.js";
import { getLicenseHeader } from "../../utils/header.js";
import { efCsharpRefkey } from "../../utils/refkey.js";
import { isModelAbstract, ModelConstructors } from "./ModelConstructors.js";
import { ModelProperty } from "./ModelProperty.js";

/**
 * Props for the {@link ModelFile} component.
 */
export interface ModelFileProps {
  /** The TCGC SDK model type representing a TypeSpec model. */
  type: SdkModelType;
  /** Resolved emitter options used for generating the file header. */
  options: ResolvedCSharpEmitterOptions;
  /** Optional children rendered inside the class body. */
  children?: Children;
}

/**
 * Generates a C# source file containing a model class declaration.
 *
 * This component produces the file-level skeleton for a model: the license
 * header, namespace, and a `partial class` declaration. The class uses the
 * access modifier from the TCGC model type (`public` or `internal`).
 *
 * Child components can render additional class members (properties,
 * constructors, fields) inside the class body — those are handled by
 * subsequent tasks (1.2.2–1.2.7).
 *
 * The generated file follows the legacy emitter's golden file format:
 *
 * @example Generated output for a simple model:
 * ```csharp
 * // <auto-generated/>
 *
 * #nullable disable
 *
 * namespace MyNamespace.Models
 * {
 *     public partial class Thing
 *     {
 *     }
 * }
 * ```
 */
export function ModelFile(props: ModelFileProps) {
  const header = getLicenseHeader(props.options);
  const namePolicy = useCSharpNamePolicy();
  const modelName = namePolicy.getName(props.type.name, "class");
  const isPublic = props.type.access === "public";

  const isAbstract = isModelAbstract(props.type);

  return (
    <SourceFile path={`src/Generated/Models/${modelName}.cs`}>
      {header}
      {"\n\n"}
      <Namespace name={props.type.namespace}>
        <ClassDeclaration
          public={isPublic}
          internal={!isPublic}
          abstract={isAbstract}
          partial
          name={modelName}
          refkey={efCsharpRefkey(props.type.__raw!)}
        >
          <ModelConstructors type={props.type} />
          {props.type.properties.length > 0 ? "\n\n" : ""}
          <For each={props.type.properties} hardline>
            {(p) => (
              <ModelProperty property={p} modelUsage={props.type.usage} />
            )}
          </For>
          {props.children}
        </ClassDeclaration>
      </Namespace>
    </SourceFile>
  );
}
