/**
 * Spector E2E Test Orchestrator
 *
 * This vitest test orchestrates the C# build and test pipeline:
 * 1. Builds the test project with `dotnet build`
 * 2. Runs the NUnit tests with `dotnet test` against the Spector mock server
 * 3. Validates that no tests were unexpectedly skipped or failed
 *
 * The test project links test files from the legacy emitter's submodule,
 * running them against code generated by the new emitter.
 *
 * The SpectorTestAttribute silently skips tests whose generated client is
 * "stubbed" (not fully implemented). To prevent regressions from hiding
 * behind silent skips or known failures, we maintain:
 *   - `.expected-skips` — tests expected to be skipped (auto-skip by SpectorTestAttribute)
 *   - `.expected-failures` — tests expected to fail (API differences, emitter bugs)
 *
 * The run fails if:
 *   - A test is skipped/fails that is NOT in the expected list (unexpected regression)
 *   - A test in the expected list actually passed (stale entry — remove it)
 *
 * Prerequisites:
 *   - Run `pnpm emit:e2e` first to generate C# client projects
 *   - The Spector mock server is started by vitest globalSetup (vitest.config.e2e.ts)
 *
 * Usage:
 *   pnpm test:e2e   # runs emit:e2e + this test via vitest.config.e2e.ts
 */
import { execSync } from "node:child_process";
import { existsSync, readFileSync } from "node:fs";
import { resolve } from "node:path";
import { describe, it, expect } from "vitest";

const REPO_ROOT = resolve(import.meta.dirname, "../..");
const TEST_PROJECT = resolve(
  import.meta.dirname,
  "Spector.Tests/Spector.Tests.csproj",
);
const GENERATED_ROOT = resolve(REPO_ROOT, "temp/e2e/Spector/http");
const EXPECTED_SKIPS_FILE = resolve(import.meta.dirname, ".expected-skips");
const EXPECTED_FAILURES_FILE = resolve(
  import.meta.dirname,
  ".expected-failures",
);

/** Port matching the vitest global-setup server (test/e2e/setup/global-setup.ts). */
const SERVER_PORT = "3002";

function hasDotnet(): boolean {
  try {
    execSync("dotnet --version", { stdio: "pipe" });
    return true;
  } catch {
    return false;
  }
}

function dotnetBuild(): { success: boolean; output: string } {
  try {
    const output = execSync(
      `dotnet build "${TEST_PROJECT}" --verbosity quiet`,
      {
        cwd: REPO_ROOT,
        encoding: "utf-8",
        stdio: ["pipe", "pipe", "pipe"],
        timeout: 300_000, // 5 minutes
      },
    );
    return { success: true, output };
  } catch (e: unknown) {
    const err = e as { stdout?: string; stderr?: string };
    return {
      success: false,
      output: `${err.stdout ?? ""}\n${err.stderr ?? ""}`.trim(),
    };
  }
}

function dotnetTest(): { success: boolean; output: string } {
  try {
    const output = execSync(
      `dotnet test "${TEST_PROJECT}" --no-build --verbosity normal`,
      {
        cwd: REPO_ROOT,
        encoding: "utf-8",
        stdio: ["pipe", "pipe", "pipe"],
        timeout: 600_000, // 10 minutes
        env: {
          ...process.env,
          SPECTOR_SERVER_PORT: SERVER_PORT,
        },
      },
    );
    return { success: true, output };
  } catch (e: unknown) {
    const err = e as { stdout?: string; stderr?: string };
    return {
      success: false,
      output: `${err.stdout ?? ""}\n${err.stderr ?? ""}`.trim(),
    };
  }
}

/**
 * Parses `dotnet test --verbosity normal` output for skipped, passed, and failed test names.
 * NUnit3TestAdapter outputs lines like:
 *   Skipped TestProjects.Spector.Tests.Http.Type.Array.ArrayTests.SomeTest [< 1 ms]
 *   Passed  TestProjects.Spector.Tests.Http.Type.Array.ArrayTests.SomeTest [50 ms]
 *   Failed  TestProjects.Spector.Tests.Http.Type.Array.ArrayTests.SomeTest [50 ms]
 */
function parseTestResults(output: string): {
  skipped: string[];
  passed: string[];
  failed: string[];
} {
  const skipped: string[] = [];
  const passed: string[] = [];
  const failed: string[] = [];

  for (const line of output.split("\n")) {
    const skipMatch = line.match(/^\s+Skipped\s+([\w.]+(?:\(.*?\))?)/);
    if (skipMatch) {
      skipped.push(skipMatch[1]);
      continue;
    }
    const passMatch = line.match(/^\s+Passed\s+([\w.]+(?:\(.*?\))?)/);
    if (passMatch) {
      passed.push(passMatch[1]);
      continue;
    }
    const failMatch = line.match(/^\s+Failed\s+([\w.]+(?:\(.*?\))?)/);
    if (failMatch) {
      failed.push(failMatch[1]);
    }
  }

  return { skipped, passed, failed };
}

/**
 * Loads the `.expected-skips` file. Returns an empty array if the file is missing.
 */
function loadExpectedSkips(): string[] {
  return loadExpectedList(EXPECTED_SKIPS_FILE);
}

/**
 * Loads the `.expected-failures` file. Returns an empty array if the file is missing.
 */
function loadExpectedFailures(): string[] {
  return loadExpectedList(EXPECTED_FAILURES_FILE);
}

/**
 * Loads a newline-delimited list file (comments start with #, blank lines ignored).
 */
function loadExpectedList(filePath: string): string[] {
  try {
    const content = readFileSync(filePath, "utf-8");
    return content
      .split(/\r?\n/)
      .filter((line) => line.trim() && !line.startsWith("#"))
      .map((line) => line.trim());
  } catch {
    return [];
  }
}

describe(
  "Spector E2E tests",
  { timeout: 900_000 }, // 15 minutes total
  () => {
    const dotnetAvailable = hasDotnet();

    // Shared state: populated by the "run tests" step, consumed by "skip analysis"
    let testOutput = "";
    let testRan = false;

    it.skipIf(!dotnetAvailable)(
      "should have generated C# projects from http-spec scenarios",
      () => {
        expect(
          existsSync(GENERATED_ROOT),
          "Generated output not found. Run `pnpm emit:e2e` first.",
        ).toBe(true);
      },
    );

    it.skipIf(!dotnetAvailable)("should build the test project", () => {
      const result = dotnetBuild();
      if (!result.success) {
        const errorLines = result.output
          .split("\n")
          .filter((l) => l.includes("error CS"))
          .slice(0, 20);
        const summary = errorLines.join("\n");
        const suffix = errorLines.length >= 20 ? "\n... and more errors" : "";
        expect.unreachable(`dotnet build failed:\n${summary}${suffix}`);
      }
    });

    it.skipIf(!dotnetAvailable)(
      "should run Spector tests against the mock server",
      () => {
        const result = dotnetTest();
        testOutput = result.output;
        testRan = true;

        console.log("\n=== Spector E2E Test Results ===");
        console.log(result.output);

        // dotnet test returns non-zero when any test fails.
        // We allow expected failures — unexpected ones are caught in the analysis step.
        if (!result.success) {
          const { failed } = parseTestResults(result.output);
          const expectedFailures = new Set(loadExpectedFailures());
          const unexpectedFailures = failed.filter(
            (name) => !expectedFailures.has(name),
          );

          if (unexpectedFailures.length > 0) {
            expect.unreachable(
              `dotnet test had ${unexpectedFailures.length} unexpected failure(s):\n` +
                unexpectedFailures.map((n) => `  ${n}`).join("\n") +
                `\n\nEither fix the emitter or add them to test/e2e/.expected-failures`,
            );
          }
        }
      },
    );

    it.skipIf(!dotnetAvailable)(
      "should not have unexpected skipped or failed tests",
      () => {
        if (!testRan) {
          return; // previous step didn't run — nothing to analyze
        }

        const { skipped, passed, failed } = parseTestResults(testOutput);
        const expectedSkips = new Set(loadExpectedSkips());
        const expectedFailures = new Set(loadExpectedFailures());

        const unexpectedSkips = skipped.filter(
          (name) => !expectedSkips.has(name),
        );
        const staleSkipEntries = [...expectedSkips].filter(
          (name) => passed.includes(name) && !skipped.includes(name),
        );

        const unexpectedFailures = failed.filter(
          (name) => !expectedFailures.has(name),
        );
        // A stale failure entry is one that appears in expected-failures but
        // now passes WITHOUT also failing. Test names may appear in multiple
        // test classes, so we only flag as stale if the name passed but did NOT
        // also fail (i.e., ALL tests with that name now pass).
        const failedSet = new Set(failed);
        const staleFailureEntries = [...expectedFailures].filter(
          (name) => passed.includes(name) && !failedSet.has(name),
        );

        // Build a report
        const lines: string[] = [];

        lines.push(`\n=== Test Analysis ===`);
        lines.push(`Total passed: ${passed.length}`);
        lines.push(`Total skipped: ${skipped.length}`);
        lines.push(`Total failed: ${failed.length}`);
        lines.push(
          `Expected skips (in .expected-skips): ${expectedSkips.size}`,
        );
        lines.push(
          `Expected failures (in .expected-failures): ${expectedFailures.size}`,
        );
        lines.push(`Unexpected skips: ${unexpectedSkips.length}`);
        lines.push(`Unexpected failures: ${unexpectedFailures.length}`);
        lines.push(
          `Stale skip entries (now passing): ${staleSkipEntries.length}`,
        );
        lines.push(
          `Stale failure entries (now passing): ${staleFailureEntries.length}`,
        );

        if (unexpectedSkips.length > 0) {
          lines.push(
            `\n❌ Unexpected skips — these tests were skipped but are NOT in .expected-skips:`,
          );
          lines.push(
            `   Either fix the emitter to cover them, or add them to test/e2e/.expected-skips:\n`,
          );
          for (const name of unexpectedSkips) {
            lines.push(`   ${name}`);
          }
        }

        if (unexpectedFailures.length > 0) {
          lines.push(
            `\n❌ Unexpected failures — these tests failed but are NOT in .expected-failures:`,
          );
          lines.push(
            `   Either fix the emitter, or add them to test/e2e/.expected-failures:\n`,
          );
          for (const name of unexpectedFailures) {
            lines.push(`   ${name}`);
          }
        }

        if (staleSkipEntries.length > 0) {
          lines.push(
            `\n❌ Stale entries — these tests are in .expected-skips but now pass:`,
          );
          lines.push(`   Remove them from test/e2e/.expected-skips:\n`);
          for (const name of staleSkipEntries) {
            lines.push(`   ${name}`);
          }
        }

        if (staleFailureEntries.length > 0) {
          lines.push(
            `\n❌ Stale entries — these tests are in .expected-failures but now pass:`,
          );
          lines.push(`   Remove them from test/e2e/.expected-failures:\n`);
          for (const name of staleFailureEntries) {
            lines.push(`   ${name}`);
          }
        }

        console.log(lines.join("\n"));

        expect(
          unexpectedSkips.length,
          `${unexpectedSkips.length} test(s) were unexpectedly skipped.\n` +
            `Add them to test/e2e/.expected-skips or fix the emitter.\n` +
            `Skipped tests:\n${unexpectedSkips.map((n) => `  ${n}`).join("\n")}`,
        ).toBe(0);

        expect(
          unexpectedFailures.length,
          `${unexpectedFailures.length} test(s) unexpectedly failed.\n` +
            `Add them to test/e2e/.expected-failures or fix the emitter.\n` +
            `Failed tests:\n${unexpectedFailures.map((n) => `  ${n}`).join("\n")}`,
        ).toBe(0);

        expect(
          staleSkipEntries.length,
          `${staleSkipEntries.length} test(s) in .expected-skips now pass.\n` +
            `Remove them from test/e2e/.expected-skips:\n${staleSkipEntries.map((n) => `  ${n}`).join("\n")}`,
        ).toBe(0);

        expect(
          staleFailureEntries.length,
          `${staleFailureEntries.length} test(s) in .expected-failures now pass.\n` +
            `Remove them from test/e2e/.expected-failures:\n${staleFailureEntries.map((n) => `  ${n}`).join("\n")}`,
        ).toBe(0);
      },
    );
  },
);
