/**
 * Spector E2E Test Orchestrator
 *
 * This vitest test orchestrates the full e2e pipeline:
 * 1. Generates C# client projects from http-specs using the new emitter
 * 2. Builds the test project with `dotnet build`
 * 3. Runs the NUnit tests with `dotnet test` against the Spector mock server
 *
 * The test project links test files from the legacy emitter's submodule,
 * running them against code generated by the new emitter.
 *
 * Usage:
 *   pnpm test:e2e                          # run full pipeline
 *   E2E_SKIP_GENERATE=true pnpm test:e2e   # skip generation (reuse existing output)
 */
import { execSync } from "node:child_process";
import { existsSync } from "node:fs";
import { resolve } from "node:path";
import { describe, it, expect, beforeAll } from "vitest";

const REPO_ROOT = resolve(import.meta.dirname, "../..");
const TEST_PROJECT = resolve(
  import.meta.dirname,
  "Spector.Tests/Spector.Tests.csproj",
);
const GENERATED_ROOT = resolve(REPO_ROOT, "temp/e2e/Spector/http");

function hasDotnet(): boolean {
  try {
    execSync("dotnet --version", { stdio: "pipe" });
    return true;
  } catch {
    return false;
  }
}

function runGenerate(): string {
  return execSync("npx tsx test/e2e/generate.ts --clean", {
    cwd: REPO_ROOT,
    encoding: "utf-8",
    stdio: ["pipe", "pipe", "pipe"],
    timeout: 600_000, // 10 minutes
  });
}

function dotnetBuild(): { success: boolean; output: string } {
  try {
    const output = execSync(
      `dotnet build "${TEST_PROJECT}" --verbosity quiet`,
      {
        cwd: REPO_ROOT,
        encoding: "utf-8",
        stdio: ["pipe", "pipe", "pipe"],
        timeout: 300_000, // 5 minutes
      },
    );
    return { success: true, output };
  } catch (e: unknown) {
    const err = e as { stdout?: string; stderr?: string };
    return {
      success: false,
      output: `${err.stdout ?? ""}\n${err.stderr ?? ""}`.trim(),
    };
  }
}

function dotnetTest(): { success: boolean; output: string } {
  try {
    const output = execSync(
      `dotnet test "${TEST_PROJECT}" --no-build --verbosity normal`,
      {
        cwd: REPO_ROOT,
        encoding: "utf-8",
        stdio: ["pipe", "pipe", "pipe"],
        timeout: 600_000, // 10 minutes
      },
    );
    return { success: true, output };
  } catch (e: unknown) {
    const err = e as { stdout?: string; stderr?: string };
    return {
      success: false,
      output: `${err.stdout ?? ""}\n${err.stderr ?? ""}`.trim(),
    };
  }
}

describe(
  "Spector E2E tests",
  { timeout: 900_000 }, // 15 minutes total
  () => {
    const skipGenerate = process.env.E2E_SKIP_GENERATE === "true";
    const dotnetAvailable = hasDotnet();

    beforeAll(() => {
      if (!dotnetAvailable) {
        console.warn("Skipping e2e tests: dotnet CLI not found");
        return;
      }

      if (!skipGenerate) {
        console.log("Generating C# projects from http-specs...");
        const output = runGenerate();
        console.log(output);
      } else {
        console.log("Skipping generation (E2E_SKIP_GENERATE=true)");
        if (!existsSync(GENERATED_ROOT)) {
          throw new Error(
            "Generated output not found. Run without E2E_SKIP_GENERATE first.",
          );
        }
      }
    });

    it.skipIf(!dotnetAvailable)(
      "should generate C# projects from all http-spec scenarios",
      () => {
        expect(existsSync(GENERATED_ROOT)).toBe(true);
      },
    );

    it.skipIf(!dotnetAvailable)("should build the test project", () => {
      const result = dotnetBuild();
      if (!result.success) {
        // Log build errors but don't fail — some generated projects may have
        // emitter bugs. The test runner will skip tests for uncompilable clients.
        console.warn("dotnet build had errors (expected during development):");
        // Show just the error summary
        const errorLines = result.output
          .split("\n")
          .filter((l) => l.includes("error CS"))
          .slice(0, 20);
        console.warn(errorLines.join("\n"));
        if (errorLines.length > 20) {
          console.warn(`... and more errors`);
        }
      }
      // Don't assert on build success — generated code may have errors
      // The SpectorTestAttribute will skip tests for uncompilable scenarios
    });

    it.skipIf(!dotnetAvailable)(
      "should run Spector tests against the mock server",
      () => {
        // First ensure build is attempted (even with errors)
        dotnetBuild();

        const result = dotnetTest();
        console.log("\n=== Spector E2E Test Results ===");
        console.log(result.output);

        // The test run itself should succeed (individual tests may be skipped)
        // We report results but don't fail the vitest — the purpose is tracking.
        if (!result.success) {
          console.warn(
            "Some Spector tests failed. This is expected during development.",
          );
          console.warn(
            "Review the output above to see which tests passed/failed/skipped.",
          );
        }
      },
    );
  },
);
