/**
 * Spector E2E Test Orchestrator
 *
 * This vitest test orchestrates the C# build and test pipeline:
 * 1. Builds the test project with `dotnet build`
 * 2. Runs the NUnit tests with `dotnet test` against the Spector mock server
 *
 * The test project links test files from the legacy emitter's submodule,
 * running them against code generated by the new emitter.
 *
 * Prerequisites:
 *   - Run `pnpm emit:e2e` first to generate C# client projects
 *   - The Spector mock server is started by vitest globalSetup (vitest.config.e2e.ts)
 *
 * Usage:
 *   pnpm test:e2e   # runs emit:e2e + this test via vitest.config.e2e.ts
 */
import { execSync } from "node:child_process";
import { existsSync } from "node:fs";
import { resolve } from "node:path";
import { describe, it, expect } from "vitest";

const REPO_ROOT = resolve(import.meta.dirname, "../..");
const TEST_PROJECT = resolve(
  import.meta.dirname,
  "Spector.Tests/Spector.Tests.csproj",
);
const GENERATED_ROOT = resolve(REPO_ROOT, "temp/e2e/Spector/http");

function hasDotnet(): boolean {
  try {
    execSync("dotnet --version", { stdio: "pipe" });
    return true;
  } catch {
    return false;
  }
}

function dotnetBuild(): { success: boolean; output: string } {
  try {
    const output = execSync(
      `dotnet build "${TEST_PROJECT}" --verbosity quiet`,
      {
        cwd: REPO_ROOT,
        encoding: "utf-8",
        stdio: ["pipe", "pipe", "pipe"],
        timeout: 300_000, // 5 minutes
      },
    );
    return { success: true, output };
  } catch (e: unknown) {
    const err = e as { stdout?: string; stderr?: string };
    return {
      success: false,
      output: `${err.stdout ?? ""}\n${err.stderr ?? ""}`.trim(),
    };
  }
}

function dotnetTest(): { success: boolean; output: string } {
  try {
    const output = execSync(
      `dotnet test "${TEST_PROJECT}" --no-build --verbosity normal`,
      {
        cwd: REPO_ROOT,
        encoding: "utf-8",
        stdio: ["pipe", "pipe", "pipe"],
        timeout: 600_000, // 10 minutes
      },
    );
    return { success: true, output };
  } catch (e: unknown) {
    const err = e as { stdout?: string; stderr?: string };
    return {
      success: false,
      output: `${err.stdout ?? ""}\n${err.stderr ?? ""}`.trim(),
    };
  }
}

describe(
  "Spector E2E tests",
  { timeout: 900_000 }, // 15 minutes total
  () => {
    const dotnetAvailable = hasDotnet();

    it.skipIf(!dotnetAvailable)(
      "should have generated C# projects from http-spec scenarios",
      () => {
        expect(
          existsSync(GENERATED_ROOT),
          "Generated output not found. Run `pnpm emit:e2e` first.",
        ).toBe(true);
      },
    );

    it.skipIf(!dotnetAvailable)("should build the test project", () => {
      const result = dotnetBuild();
      if (!result.success) {
        const errorLines = result.output
          .split("\n")
          .filter((l) => l.includes("error CS"))
          .slice(0, 20);
        const summary = errorLines.join("\n");
        const suffix = errorLines.length >= 20 ? "\n... and more errors" : "";
        expect.unreachable(
          `dotnet build failed:\n${summary}${suffix}`,
        );
      }
    });

    it.skipIf(!dotnetAvailable)(
      "should run Spector tests against the mock server",
      () => {
        const result = dotnetTest();
        console.log("\n=== Spector E2E Test Results ===");
        console.log(result.output);

        expect(result.success, `dotnet test failed:\n${result.output}`).toBe(
          true,
        );
      },
    );
  },
);
